Repository phpbb/phpbb, pull requests merged in 2018-06, with the labels that each got.

#5134 [ticket/15553] Add method to get direct link
  phpBB/phpbb/storage/adapter/adapter_interface.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/storage.php
Labels: 3.3 (Proteus)

#5226 [ticket/15504] Fix warning message
  phpBB/phpbb/debug/error_handler.php
Labels: 3.2 (Rhea)

#5192 [ticket/15629] Add info to RECAPTCHA_LANG and change to en-GB
  phpBB/language/en/captcha_recaptcha.php
Labels: 3.2 (Rhea)

#5191 [ticket/15630] ACP_COOKIE_SETTINGS_EXPLAIN change <b> to <strong>
  phpBB/language/en/acp/board.php
Labels: 3.2 (Rhea)

#4968 [ticket/15371] Split uploaded files into subdirectories
  phpBB/includes/acp/acp_storage.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/storage.php
  phpBB/phpbb/db/migration/data/v330/storage_adapter_local_depth.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/provider/local.php
  tests/storage/adapter/local_test.php
Labels: 3.3 (Proteus)

#5218 [ticket/15657] Add MCP queue events
  phpBB/includes/mcp/mcp_queue.php
Labels: 3.2 (Rhea), Event

#5246 [ticket/15633] Double space to single space
  phpBB/language/en/acp/groups.php
Labels: 3.2 (Rhea)

#5245 [ticket/15693] Fix get_rand_string()
  phpBB/includes/functions.php
  tests/random/gen_rand_string_test.php
Labels: 3.2 (Rhea)

#5241 [ticket/15686] Update homestead
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Proteus)

#5259 [ticket/15695] Fix gen_rand_string returning less characters than expected
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5233 [ticket/15678] Fix PHP warning in filesystem.php
  phpBB/phpbb/filesystem/filesystem.php
Labels: 3.2 (Rhea)

#5227 [ticket/15671] Limit accepted formats for avatar upload
  phpBB/adm/style/acp_avatar_options_upload.html
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/styles/prosilver/template/ucp_avatar_options_upload.html
Labels: 3.3 (Proteus)

#5242 [ticket/15688] Fix event location in attachments download
  phpBB/download/file.php
Labels: 3.3 (Proteus)
