Repository phpbb/phpbb, pull requests merged in 2018-11, with the labels that each got.

#5448 [ticket/15875] Fix PHP fatal error on BBCode parsing
  phpBB/includes/bbcode.php
  phpBB/includes/functions_content.php
Labels: 3.2 (Rhea)

#5436 [ticket/15863] Add core.viewforum_modify_sort_direction
  phpBB/viewforum.php
Labels: Event

#5441 [ticket/15870] Add core.viewtopic_modify_forum_id
  phpBB/viewtopic.php
Labels: Event

#5445 [ticket/15873] Add core.mcp_report_template_data
  phpBB/includes/mcp/mcp_reports.php
Labels: Event

#5433 [ticket/15542] Always append assets versions to assets
  phpBB/phpbb/template/twig/node/includeasset.php
Labels: 3.2 (Rhea)

#5454 [ticket/15881] Reset login keys for new password activation
  phpBB/includes/ucp/ucp_activate.php
Labels: 3.2 (Rhea)

#5432 [ticket/15859] Add core.viewforum_modify_topic_ordering
  phpBB/viewforum.php
Labels: 3.2 (Rhea), Event

#5450 [ticket/15665] Fix MSSQL crashes if upload dir>2GB
  phpBB/phpbb/db/driver/mssql_base.php
Labels: 3.2 (Rhea)

#5427 [ticket/15858] Unapproved User(s) appearing as Guest in Team Page
  phpBB/memberlist.php
Labels: 3.2 (Rhea)

#5451 [ticket/15867] Add class for message field in the contact form
  phpBB/styles/prosilver/template/memberlist_email.html
Labels: 3.2 (Rhea), Styles 🎨

#5455 [ticket/15879] Add core.posting_modify_default_variables
  phpBB/posting.php
Labels: Event
