Repository phpbb/phpbb, pull requests merged in 2018-07, with the labels that each got.

#5229 [ticket/15613] Fix Notification dropdown said to be not RTL compliant
  phpBB/assets/javascript/core.js
Labels: 3.2 (Rhea)

#5217 [ticket/15656] Add "View post" link in the mod logs on the ACP
  phpBB/includes/acp/acp_logs.php
Labels: 3.2 (Rhea)

#5214 [ticket/15638] Add word-break for overflowing.
  phpBB/adm/style/admin.css
Labels: 3.2 (Rhea), Styles 🎨

#5183 [ticket/15605] Correct Right-Margin for ribbon image
  phpBB/styles/prosilver/theme/responsive.css
Labels: 3.3 (Proteus), Styles 🎨

#5185 [ticket/15611] Fix misaligned text in responsive user profile
  phpBB/styles/prosilver/theme/responsive.css
Labels: 3.2 (Rhea), Styles 🎨

#5157 [ticket/15583] Update session time in AJAX request only once a minute
  phpBB/phpbb/session.php
Labels: 3.2 (Rhea)

#5136 [ticket/15522] Improve color palette syntax
  phpBB/adm/style/acp_contact.html
  phpBB/adm/style/acp_groups.html
  phpBB/adm/style/acp_users_signature.html
  phpBB/assets/javascript/core.js
  phpBB/styles/prosilver/template/posting_buttons.html
  phpBB/styles/prosilver/template/ucp_groups_manage.html
Labels: 3.3 (Proteus), JS :scroll:

#5119 [ticket/15545] Fix no vertical space between format buttons
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/forms.css
Labels: 3.3 (Proteus), Styles 🎨

#4986 [ticket/15388] List boxes internal corners rounded
  phpBB/styles/prosilver/theme/content.css
Labels: 3.3 (Proteus), Styles 🎨

#5280 [ticket/15718] Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: 3.3 (Proteus)

#5278 [ticket/15673] Fix Duplicated links in QuickLinks and main nav bar
  phpBB/styles/prosilver/theme/common.css
Labels: 3.2 (Rhea), Styles 🎨

#5266 [ticket/12624] Add debug.load_time parameter
  phpBB/common.php
  phpBB/config/development/config.yml
  phpBB/includes/functions.php
  phpBB/phpbb/db/driver/driver.php
  phpBB/phpbb/db/driver/driver_interface.php
  phpBB/phpbb/db/driver/factory.php
  phpBB/phpbb/db/driver/mssql_odbc.php
  phpBB/phpbb/db/driver/mssqlnative.php
  phpBB/phpbb/db/driver/mysql.php
  phpBB/phpbb/db/driver/mysqli.php
  phpBB/phpbb/db/driver/oracle.php
  phpBB/phpbb/db/driver/postgres.php
  phpBB/phpbb/db/driver/sqlite3.php
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/install/module/install_filesystem/task/create_config_file.php
  tests/mock/container_builder.php
  vagrant/after.sh
Labels: 3.3 (Proteus)

#5262 [ticket/15606] Hide viewprofile link when unavailable
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea)

#5261 [ticket/15670] Group forum permission: Can see forum gives NO SQL ERROR
  phpBB/viewforum.php
Labels: 3.2 (Rhea)

#5258 [ticket/15628] Add topic link to newtopic_notify.txt
  phpBB/language/en/email/newtopic_notify.txt
Labels: 3.2 (Rhea)

#5257 [ticket/15651] Remove unnecessary condition
  phpBB/phpbb/db/migration/data/v320/add_help_phpbb.php
Labels: 3.2 (Rhea)

#5256 [ticket/13043] Improve HTML5
  phpBB/styles/prosilver/template/mcp_ban.html
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/styles/prosilver/template/plupload.html
  phpBB/styles/prosilver/template/posting_buttons.html
  phpBB/styles/prosilver/template/posting_smilies.html
  phpBB/styles/prosilver/template/posting_topic_review.html
  phpBB/styles/prosilver/template/simple_footer.html
  phpBB/styles/prosilver/template/ucp_agreement.html
  phpBB/styles/prosilver/template/ucp_pm_history.html
  phpBB/styles/prosilver/template/ucp_prefs_personal.html
  phpBB/styles/prosilver/template/ucp_register.html
Labels: 3.2 (Rhea), Styles 🎨

#5255 [ticket/15694] Ignore lang files in prosilver/theme dir
  .gitignore
Labels: 3.3 (Proteus)

#5254 [ticket/15620] Use separate local avatar cache file for every lang
  phpBB/phpbb/avatar/driver/local.php
Labels: 3.2 (Rhea)

#5253 [ticket/15618] Display The team link only to users with permission
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5252 [ticket/15674] Edit language lines in file en\acp\profile.php
  phpBB/language/en/acp/profile.php
Labels: 3.2 (Rhea)

#5250 [ticket/15666] Language system is not fully supported in Twig
  phpBB/phpbb/template/twig/extension.php
Labels: 3.2 (Rhea)

#5249 [ticket/15659] Fix retrieve_block_vars()
  phpBB/phpbb/template/context.php
  tests/template/context_test.php
Labels: 3.2 (Rhea)

#5244 [ticket/15678] Fix build and cache flow for container
  phpBB/phpbb/di/container_builder.php
  phpBB/phpbb/filesystem/filesystem.php
Labels: 3.2 (Rhea)

#5239 [ticket/15683] Better error message when commit message has CRLF
  git-tools/hooks/commit-msg
Labels: 3.2 (Rhea)

#5238 [ticket/15680] Point to 3.2 documentation
  phpBB/docs/INSTALL.html
Labels: 3.2 (Rhea)

#5271 [ticket/15286] Download remote attachments properly
  phpBB/includes/functions_download.php
Labels: 3.3 (Proteus)

#5232 [ticket/15677] Update symfony to 2.8.42, others to latest
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5283 [ticket/15677] Update composer dependencies to latest -- Master version
  phpBB/composer.lock
Labels: 3.3 (Proteus)

#5306 [ticket/15725] Fix installing ext in tests for master branch
  tests/functional/extension_acp_test.php
  tests/test_framework/phpbb_functional_test_case.php
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.3 (Proteus)

#5298 [ticket/15731] Fix language string parameters
  phpBB/includes/acp/acp_search.php
  phpBB/language/en/acp/search.php
Labels: 3.2 (Rhea)

#5304 [ticket/11847] Add depends_on() to auth_provider_oauth
  phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php
Labels: 3.2 (Rhea)
