Repository phpbb/phpbb, pull requests merged in 2018-02, with the labels that each got.

#5081 [ticket/15492] Fix permission role combobox in RTL
  phpBB/adm/style/admin.css
  phpBB/adm/style/permission_mask.html
  phpBB/adm/style/tooltip.js
  phpBB/assets/javascript/core.js
Labels: JS, Styles

#5105 [ticket/15398] Add core.oauth_login_after_check_if_provider_id_has_match
  phpBB/phpbb/auth/provider/oauth/oauth.php
Labels: 3.2 (Rhea), Event

#5107 [ticket/15522] Allow multiple color palettes on one page
  phpBB/assets/javascript/core.js
Labels: JS

#5127 [ticket/15547] Add file object to event
  phpBB/phpbb/avatar/driver/upload.php
Labels: 3.2 (Rhea), Event

#5137 [ticket/15558] Fix wrongly assigned uid and bitfield
  phpBB/phpbb/report/report_handler_post.php
Labels: 3.2 (Rhea)

#5128 [ticket/12579] Add "BUTTON_" strings for Post and PM buttons
  phpBB/language/en/common.php
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
  phpBB/styles/prosilver/template/viewtopic_body.html
Labels: 3.2 (Rhea), Styles

#5118 [ticket/15520] sql_build_query build subquery
  phpBB/phpbb/db/driver/driver.php
Labels: 3.2 (Rhea)

#5139 [ticket/15535] Fix quote font sizes
  phpBB/styles/prosilver/theme/content.css
Labels: 3.3 (Proteus), Styles

#5089 [ticket/15516] Add instructions for running UI tests
  tests/RUNNING_TESTS.md
Labels: 3.2 (Rhea)

#5094 [ticket/15518] Add a setting to toggle permission checks for pms in viewtopic
  phpBB/includes/acp/acp_board.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/phpbb/db/migration/data/v32x/enable_accurate_pm_button.php
  phpBB/viewtopic.php
Labels: 3.2 (Rhea)

#5138 [ticket/15559] Fix wrongly assigned uid and bitfield
  phpBB/phpbb/report/report_handler_pm.php
Labels: 3.2 (Rhea)

#5133 [ticket/15563] Check if database file is writable only if exists
  phpBB/phpbb/install/helper/database.php
Labels: 3.2 (Rhea)

#5131 [ticket/15561] Add events for adding columns to search index
  phpBB/phpbb/search/fulltext_mysql.php
  phpBB/phpbb/search/fulltext_native.php
  phpBB/phpbb/search/fulltext_postgres.php
Labels: Event

#5144 [ticket/15466] Update CREDITS.txt to reflect Nils leaving [ci skip]
  phpBB/docs/CREDITS.txt
Labels: 3.2 (Rhea)

#5145 [ticket/15568] Update dependencies to latest versions
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5146 [ticket/15570] Allow file downloader to use TLS greater than 1.0
  phpBB/phpbb/file_downloader.php
Labels: 3.2 (Rhea)

#5147 [ticket/15569] Suggest using file replacing instead of automatic updater
  phpBB/docs/INSTALL.html
  phpBB/language/en/install.php
Labels: 3.2 (Rhea)
