Repository phpbb/phpbb, pull requests merged in 2018-10, with the labels that each got.

#5152 [ticket/15579] Add ucp_front events
  phpBB/includes/ucp/ucp_main.php
Labels: 3.2 (Rhea), Event

#5215 [ticket/13128] Remove deprecated Sphinx options
  phpBB/docs/sphinx.sample.conf
  phpBB/phpbb/search/fulltext_sphinx.php
Labels: 3.2 (Rhea)

#5219 [ticket/15661] Add core.viewtopic_modify_poll_ajax_data
  phpBB/viewtopic.php
Labels: 3.2 (Rhea), Event

#5220 [ticket/15662] Add $this->template to core.modify_notification_message
  phpBB/includes/functions_messenger.php
Labels: 3.2 (Rhea), Event

#5251 [ticket/15668] Replace .load() with .on('load')
  phpBB/assets/javascript/core.js
  phpBB/styles/prosilver/template/forum_fn.js
Labels: 3.2 (Rhea), Styles 🎨

#5296 [ticket/15622] Fix quoting in PMs when BBCodes are disabled
  phpBB/includes/functions_content.php
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/posting.php
Labels: 3.2 (Rhea)

#5301 [ticket/11500] Remove unnamed input
  phpBB/adm/style/acp_profile.html
  tests/functional/acp_profile_field_test.php
Labels: 3.2 (Rhea)

#5338 [ticket/15420] Only update quote notification with original author
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea)

#5343 [ticket/15716] Remove OAuth data upon user deletion
  phpBB/includes/functions_user.php
  tests/console/user/base.php
  tests/functions/user_delete_test.php
  tests/functions_user/delete_user_test.php
Labels: 3.2 (Rhea)

#5346 [ticket/15768] Add a license to a repository
  LICENSE
Labels: 3.2 (Rhea)

#5353 [ticket/15607] Skip ban and disabled checks when deleting cookies
  phpBB/ucp.php
Labels: 3.2 (Rhea)

#5354 [ticket/15329] Parse drafts before saving them (and decode)
  phpBB/includes/ucp/ucp_main.php
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: 3.2 (Rhea)

#5355 [ticket/15770] Make sure sphinx limits are cast to int
  phpBB/phpbb/search/fulltext_sphinx.php
Labels: 3.2 (Rhea)

#5370 [ticket/15805] Add result to core.login_box_redirect
  phpBB/includes/functions.php
Labels: 3.2 (Rhea), Event

#5394 [ticket/12430] Remove hilit param from topic title link
  phpBB/viewtopic.php
Labels: 3.2 (Rhea)

#5004 [ticket/15410] Remove obsolete code from BBCodes ACP
  phpBB/includes/acp/acp_bbcodes.php
Labels: 3.3 (Proteus)

#5287 [ticket/15719] Add core events to viewtopic to edit the post_list sql query
  phpBB/viewtopic.php
Labels: 3.2 (Rhea)

#5313 [ticket/12628] Introduce debug.memory
  phpBB/config/development/config.yml
  phpBB/includes/functions.php
  phpBB/install/convert/convertor.php
  phpBB/phpbb/di/extension/container_configuration.php
Labels: 3.3 (Proteus)

#5366 [ticket/15799] Find correct poll for voting animation
  phpBB/styles/prosilver/template/ajax.js
Labels: 3.2 (Rhea), JS :scroll:

#5170 [ticket/15600] Escaped ban reasons in JavaScript code of mcp_warn.html
  phpBB/styles/prosilver/template/mcp_ban.html
Labels: 3.2 (Rhea), JS :scroll:

#5377 [ticket/15700] Use correct T_THEME_LANG_NAME
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5378 [ticket/15642] Replace > with &gt;
  phpBB/language/en/acp/board.php
Labels: 3.2 (Rhea)

#5382 [ticket/15596] Migrate from data-vocabulary.org to schema.org
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea)

#5386 [ticket/15809] Allow twig syntax for template events
  phpBB/phpbb/event/md_exporter.php
Labels: 3.2 (Rhea)

#5331 [ticket/12636] Add session.log_errors
  phpBB/config/development/config.yml
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/di/extension/core.php
  phpBB/phpbb/session.php
  tests/mock/container_builder.php
Labels: 3.3 (Proteus)

#5374 [ticket/15758] Show translated msg for INSECURE_REDIRECT
  phpBB/includes/functions.php
  tests/security/redirect_test.php
Labels: 3.2 (Rhea)

#5367 [ticket/15788] Fix return button for Privacy Policy
  phpBB/ucp.php
Labels: 3.2 (Rhea)

#5368 [ticket/15803] Add events on ucp_pm_compose for additional message list actions
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: 3.2 (Rhea), Event

#5371 [ticket/15792] Add confirm_delete_body_delete_reason_before
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/confirm_delete_body.html
Labels: 3.2 (Rhea), Event

#5373 [ticket/15771] Improve Q&A instructions
  phpBB/language/en/captcha_qa.php
Labels: 3.2 (Rhea)

#5375 [ticket/15706] Add mcp_post_report_buttons_top_* events
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/mcp_post.html
Labels: 3.2 (Rhea), Event

#5381 [ticket/15616] Remove jumpbox from login_forum.html
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5383 [ticket/15554] Add simple_footer_body_after
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/simple_footer.html
Labels: 3.2 (Rhea), Event

#5384 [ticket/15552] Call insert_single_user when appropriate
  phpBB/styles/prosilver/template/forum_fn.js
Labels: 3.2 (Rhea)

#5409 [ticket/15494] Allow user to be removed from NEWLY_REGISTERED multiple times
  phpBB/includes/functions_user.php
Labels: 3.2 (Rhea)

#5397 [ticket/15824] Fix and update UI framework
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.2 (Rhea)

#5390 [ticket/15244] Remove unglobalise related code
  phpBB/language/en/posting.php
  phpBB/posting.php
  phpBB/styles/prosilver/template/posting_layout.html
Labels: 3.3 (Proteus)

#5421 [ticket/15848] Update plupload to 2.3.6
  phpBB/assets/plupload/plupload.full.min.js
Labels: 3.2 (Rhea)

#5376 [ticket/15701] Display signature in MCP
  phpBB/includes/mcp/mcp_post.php
  phpBB/includes/mcp/mcp_reports.php
Labels: 3.2 (Rhea)

#5379 [ticket/15621] Remove graphical inconsistencies
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/styles/prosilver/template/mcp_post.html
  phpBB/styles/prosilver/template/posting_pm_header.html
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Labels: 3.2 (Rhea)

#5403 [ticket/14812] Prune shadow topics during system cron too
  phpBB/phpbb/cron/task/core/prune_all_forums.php
Labels: 3.2 (Rhea)

#5388 [ticket/15819] Add core event to functions_posting to modify notifications
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea)

#5151 [ticket/15836] Event to send message via external transport
  phpBB/includes/functions_messenger.php
Labels: 3.2 (Rhea), Event

#5418 [ticket/15846] Fix Wrong id for downldable extensions group
  phpBB/install/schemas/schema_data.sql
Labels: 3.3 (Proteus)

#5420 [ticket/15850] Fix "Duplicate entry" for notification types
  phpBB/phpbb/notification/manager.php
  phpBB/phpbb/notification/method/board.php
Labels: 3.2 (Rhea)

#5424 [ticket/15849] Stop using php4 constructors
  build/build_helper.php
  phpBB/includes/acp/acp_inactive.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/acp/auth.php
  phpBB/includes/bbcode.php
  phpBB/includes/diff/diff.php
  phpBB/includes/diff/renderer.php
  phpBB/includes/functions_compress.php
  phpBB/includes/functions_content.php
  phpBB/includes/functions_messenger.php
  phpBB/includes/functions_module.php
  phpBB/includes/functions_transfer.php
  phpBB/includes/hooks/index.php
  phpBB/includes/mcp/mcp_logs.php
  phpBB/includes/mcp/mcp_main.php
  phpBB/includes/mcp/mcp_notes.php
  phpBB/includes/mcp/mcp_pm_reports.php
  phpBB/includes/mcp/mcp_queue.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/includes/mcp/mcp_warn.php
  phpBB/includes/message_parser.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/includes/sphinxapi.php
  phpBB/includes/ucp/ucp_main.php
  tests/cache/cache_memory.php
Labels: 3.2 (Rhea)

#5399 [ticket/15826] Add core.mcp_main_fork_sql_after
  phpBB/includes/mcp/mcp_main.php
Labels: Event

#5363 [ticket/14656] Add List-Unsubscribe header to emails
  phpBB/includes/functions_messenger.php
  phpBB/language/en/email/forum_notify.txt
  phpBB/language/en/email/newtopic_notify.txt
  phpBB/language/en/email/topic_notify.txt
Labels: 3.2 (Rhea)

#5380 [ticket/15619] Always display CPF legend
  phpBB/styles/prosilver/template/memberlist_body.html
Labels: 3.2 (Rhea)

#5387 [ticket/15593] Do not allow print view with direct URL
  phpBB/includes/ucp/ucp_pm.php
  phpBB/language/en/ucp.php
  phpBB/language/en/viewtopic.php
  phpBB/viewtopic.php
Labels: 3.2 (Rhea)

#5395 [ticket/15817] Fix installtion failed with Oracle
  phpBB/phpbb/install/helper/database.php
Labels: 3.2 (Rhea)

#5401 [ticket/15827] Add *_username_{prepend/append} template events
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/forumlist_body.html
  phpBB/styles/prosilver/template/memberlist_view.html
  phpBB/styles/prosilver/template/search_results.html
  phpBB/styles/prosilver/template/viewforum_body.html
  phpBB/styles/prosilver/template/viewonline_body.html
Labels: 3.2 (Rhea)

#5402 [ticket/15825] Add core.acp_manage_forums_move_content_sql_before
  phpBB/includes/acp/acp_forums.php
Labels: Event

#5404 [ticket/15830] Move event to a more useful place
  phpBB/includes/functions_messenger.php
Labels: 3.2 (Rhea), Event

#5406 [ticket/15831] Add core.acp_users_modify_signature_sql_ary event
  phpBB/includes/acp/acp_users.php
Labels: Event

#5407 [ticket/15832] Add core.acp_users_avatar_sql event
  phpBB/includes/acp/acp_users.php
Labels: 3.2 (Rhea), Event

#5414 [ticket/15837] Add core.ucp_register_welcome_email_before
  phpBB/includes/ucp/ucp_register.php
Labels: Event

#5415 [ticket/15838] Add core.ucp_register_register_after
  phpBB/includes/ucp/ucp_register.php
Labels: Event

#5408 [ticket/15833] Add core.avatar_manager_avatar_delete_after event
  phpBB/config/default/container/services_avatar.yml
  phpBB/phpbb/avatar/manager.php
  tests/avatar/manager_test.php
Labels: Event

#5425 [ticket/15857] Add rubencm to CREDITS.txt
  phpBB/docs/CREDITS.txt
Labels: 3.2 (Rhea)
