Repository phpbb/phpbb, pull requests merged in 2018-12, with the labels that each got.

#5465 [ticket/15892] Rename variable to commonly used $storage_attachment
  phpBB/includes/functions_content.php
Labels: 3.3 (Proteus), Blocker :warning:

#5336 [ticket/12629] Add debug.errors_show
  phpBB/config/development/config.yml
  phpBB/includes/functions.php
  phpBB/phpbb/di/extension/container_configuration.php
  tests/controller/common_helper_route.php
  tests/controller/controller_test.php
  tests/pagination/pagination_test.php
Labels: 3.3 (Proteus)

#5466 [ticket/15893] Pass needed language class directly to format quote
  phpBB/includes/functions_content.php
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/posting.php
  tests/functions_content/phpbb_format_quote_test.php
Labels: 3.2 (Rhea), Blocker :warning:

#5470 [ticket/15888] Changing ACP link from 3.1 to 3.2 docs
  phpBB/language/en/acp/permissions.php
Labels: 3.2 (Rhea)

#5479 [ticket/15904] Fix counting empty template blocks
  phpBB/phpbb/template/context.php
Labels: 3.2 (Rhea)

#5481 [ticket/15910] Pass object arguments by reference implicitly
  phpBB/includes/acp/acp_inactive.php
  phpBB/includes/acp/acp_permissions.php
  phpBB/includes/acp/acp_profile.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions_compatibility.php
  phpBB/includes/functions_mcp.php
  phpBB/includes/mcp/mcp_logs.php
  phpBB/includes/mcp/mcp_main.php
  phpBB/includes/mcp/mcp_notes.php
  phpBB/includes/mcp/mcp_pm_reports.php
  phpBB/includes/mcp/mcp_queue.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/includes/mcp/mcp_warn.php
  phpBB/includes/ucp/ucp_main.php
  phpBB/phpbb/captcha/plugins/gd.php
  phpBB/phpbb/captcha/plugins/gd_wave.php
  phpBB/phpbb/captcha/plugins/nogd.php
  phpBB/phpbb/captcha/plugins/qa.php
  phpBB/phpbb/captcha/plugins/recaptcha.php
  phpBB/phpbb/files/upload.php
  tests/upload/filespec_test.php
Labels: 3.2 (Rhea)

#5456 [ticket/15876] MySQL 5.7+ support for Q&A captcha plugin
  phpBB/phpbb/captcha/plugins/qa.php
Labels: 3.2 (Rhea)

#5359 [ticket/15509] Don't show disabled board when in install
  phpBB/phpbb/user.php
Labels: 3.2 (Rhea)

#5482 [ticket/15914] Add core.modify_memberlist_viewprofile_group* events
  phpBB/memberlist.php
Labels: Event

#5468 [ticket/15898] Add core.ucp_pm_compose_template
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: Event

#5490 [ticket/15921] Fix master build
  phpBB/composer.lock
Labels: 3.3 (Proteus), Blocker :warning:
