Repository phpbb/phpbb, pull requests merged in 2018-09, with the labels that each got.

#5345 [ticket/15746] Update to Symfony 2.8.45
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5347 [ticket/15746] Update symfony to latest on master
  phpBB/composer.lock
  phpBB/phpbb/di/container_builder.php
Labels: 3.3 (Proteus)

#5330 [ticket/12623] Add allow_install_dir
  phpBB/config/development/config.yml
  phpBB/config/test/config.yml
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/di/extension/core.php
  phpBB/phpbb/user.php
Labels: 3.3 (Proteus)

#5324 [ticket/15760] Fix write_stream
  phpBB/includes/acp/acp_database.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/files/filespec_storage.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/storage.php
Labels: 3.3 (Proteus)

#5114 [ticket/15536] Catalog: adds satis.phpbb.com to repositories
  phpBB/phpbb/composer/installer.php
  phpBB/phpbb/db/migration/data/v330/extensions_composer_2.php
Labels: 3.3 (Proteus)

#5349 [ticket/15566] Set category to none if extension don't exist
  phpBB/includes/acp/acp_attachments.php
Labels: 3.2 (Rhea)

#5339 [ticket/15748] Fix toggle alt text
  phpBB/assets/javascript/core.js
Labels: 3.2 (Rhea)

#5352 [ticket/15744] Remove useless sql_freeresults
  phpBB/phpbb/db/migration/data/v320/remove_outdated_media.php
Labels: 3.2 (Rhea)

#5350 [ticket/15767] Fix effictively_installed condition for oauth_tokens
  phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php
Labels: 3.2 (Rhea)

#5342 [ticket/15721] Make plupload more versatile
  phpBB/assets/javascript/plupload.js
Labels: 3.2 (Rhea)

#5160 [ticket/15590] Add events core.acp_bbcodes_(modify_create|delete)_after
  phpBB/includes/acp/acp_bbcodes.php
Labels: 3.2 (Rhea), Event

#5288 [ticket/15413] Login redirect to previous page
  phpBB/includes/functions.php
Labels: 3.3 (Proteus)

#5289 [ticket/15720] Don't escape ampersands on redirections
  phpBB/cron.php
  phpBB/feed.php
  phpBB/report.php
Labels: 3.3 (Proteus)

#5248 [ticket/15692] Move checks if file exists from adapter to storage
  phpBB/includes/functions_download.php
  phpBB/language/en/common.php
  phpBB/phpbb/db/migration/data/v330/storage_track.php
  phpBB/phpbb/storage/adapter/adapter_interface.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/storage.php
  tests/attachment/delete_test.php
  tests/attachment/upload_test.php
  tests/avatar/manager_test.php
  tests/notification/submit_post_base.php
  tests/privmsgs/delete_user_pms_test.php
Labels: 3.3 (Proteus), GSOC 🎓

#5362 [ticket/15791] fix php 7.2 count() bug in memory cache driver
  phpBB/phpbb/cache/driver/memory.php
Labels: 3.2 (Rhea)

#5303 [ticket/11838] OAuth registration from ucp_register
  phpBB/includes/ucp/ucp_register.php
  phpBB/language/en/ucp.php
  phpBB/phpbb/auth/provider/oauth/oauth.php
  phpBB/styles/prosilver/template/ucp_register.html
Labels: 3.3 (Proteus)

#5300 [ticket/11453] Improve performance of notification.method.messenger_base
  phpBB/phpbb/notification/method/messenger_base.php
  phpBB/phpbb/user_loader.php
Labels: 3.2 (Rhea)

#5312 [ticket/15541] Explicitly explain how to add lang files in core.user_…
  phpBB/phpbb/user.php
Labels: 3.2 (Rhea)

#5292 [ticket/15723] Rewrite gen_rand_string() and gen_rand_string_friendly()
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5319 [ticket/15751] Fix warning when update with CLI
  phpBB/phpbb/install/module/requirements/task/check_update.php
Labels: 3.2 (Rhea)

#5328 [ticket/15255] Move language strings from acp/common to common
  phpBB/language/en/acp/common.php
  phpBB/language/en/common.php
  phpBB/phpbb/filesystem/filesystem.php
Labels: 3.3 (Proteus)

#5364 [ticket/15795] Fix broken migration, $config is not a method
  phpBB/phpbb/db/migration/data/v330/extensions_composer_2.php
Labels: 3.3 (Proteus)

#5356 [ticket/15772] Hide warning in acp when allow_install_dir is true
  phpBB/includes/acp/acp_main.php
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.3 (Proteus)
