Repository phpbb/phpbb, pull requests merged in 2019-11, with the labels that each got.

#5723 [ticket/16196] Remove paragonie/random_compat
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Rhea) 🌑

#5724 [ticket/16190] Deprecate phpbb's checkdnsrr wrapper
  phpBB/includes/functions.php
  phpBB/includes/functions_compatibility.php
  phpBB/includes/functions_user.php
  phpBB/phpbb/session.php
  tests/functions/get_remote_file_test.php
  tests/network/checkdnsrr_test.php
  tests/version/version_fetch_test.php
Labels: 3.3 (Rhea) 🌑

#5719 [ticket/15958] Standarize create forums default options
  phpBB/includes/acp/acp_forums.php
  phpBB/install/schemas/schema_data.sql
Labels: 3.3 (Rhea) 🌑

#5720 [ticket/16188] fix acp responsive stats
  phpBB/adm/style/admin.css
Labels: 3.3 (Rhea) 🌑, CSS 📐, Styles 🎨

#5722 [ticket/16195] Copy forum permissions' missing paragraph
  phpBB/adm/style/permission_forum_copy.html
Labels: 3.3 (Rhea) 🌑

#5717 [ticket/16187] Correctly display registration using external services
  phpBB/styles/prosilver/template/ucp_register.html
Labels: Styles 🎨

#5729 [ticket/16199] Init guest posting CAPTCHA only if guest posting is allowed
  phpBB/posting.php
Labels: 3.2 (Rhea)

#5736 [ticket/16210] Ensure terms of use is not skipped by enforcing form token
  phpBB/includes/ucp/ucp_register.php
Labels: 3.2 (Rhea)

#5733 [ticket/16206] Remove no longer needed workaround for PHP bug #66834
  phpBB/phpbb/di/service_collection.php
Labels: 3.3 (Rhea) 🌑

#5735 [ticket/16205] Fix undefined $zebra variable
  phpBB/search.php
Labels: 3.3 (Rhea) 🌑

#5740 [ticket/16216] Disable xdebug on travis
  travis/setup-php-extensions.sh
Labels: 3.2 (Rhea)

#5742 [ticket/16216] Ignore not being able to disable xdebug
  travis/setup-php-extensions.sh
Labels: 3.3 (Rhea) 🌑

#5741 [ticket/16217] Enable opcache on travis tests again
  travis/setup-php-extensions.sh
Labels: 3.2 (Rhea)

#5750 [ticket/12539] Rebind live member search navigation
  phpBB/assets/javascript/core.js
Labels: 3.3 (Rhea) 🌑

#5747 [ticket/16228] Fix BBCodes merging
  phpBB/phpbb/textformatter/s9e/bbcode_merger.php
  tests/text_formatter/s9e/bbcode_merger_test.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑

#5749 [ticket/16227] Fix undefined vars on login
  phpBB/includes/functions.php
Labels: 3.3 (Rhea) 🌑

#5730 [ticket/16203] Enable Emojis and rich text in sent Emails
  phpBB/includes/functions_messenger.php
Labels: php 🐘
