Repository phpbb/phpbb, pull requests merged in 2019-04, with the labels that each got.

#5560 [ticket/16009] Display OAuth login's buttons in a row
  phpBB/styles/prosilver/template/login_body_oauth.html
Labels: 3.2 (Rhea)

#5558 [ticket/16006] Create unique ID's for OAuth (un)linking
  phpBB/phpbb/auth/provider/oauth/oauth.php
  phpBB/styles/prosilver/template/ucp_auth_link_oauth.html
Labels: 3.2 (Rhea)

#5554 [ticket/16001] Append data to the OAuth's redirect URL
  phpBB/phpbb/auth/provider/oauth/oauth.php
Labels: Event 🔌

#5552 [ticket/15995] Add core.memberlist_modify_sort_pagination_params
  phpBB/memberlist.php
Labels: 3.2 (Rhea), Event 🔌

#5538 [ticket/15972] Add core.markread_after
  phpBB/includes/functions.php
Labels: 3.2 (Rhea), Event 🔌

#5519 [ticket/15949] Add ucp_profile_signature_posting_editor_options_prepend
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_profile_signature.html
Labels: 3.2 (Rhea), Event 🔌

#5516 [ticket/15944] Add core.posting_modify_quote_attributes
  phpBB/posting.php
Labels: 3.2 (Rhea), Event 🔌

#5484 [ticket/15915] Add template events to posting_attach_body.html
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/posting_attach_body.html
Labels: Event 🔌

#5567 [ticket/16018] Update composer to 1.8.5, symfony & dependencies to latest
  composer.phar
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5570 [ticket/16020] Fix some mistake from PHPBB3-15827
  phpBB/styles/prosilver/template/viewforum_body.html
Labels: 3.2 (Rhea), Event 🔌

#5576 [ticket/16027] Force clearing of cache folder on install for functional
  tests/test_framework/phpbb_functional_test_case.php
Labels: 3.2 (Rhea), Blocker :warning:
