Repository phpbb/phpbb, pull requests merged in 2019-01, with the labels that each got.

#5495 [ticket/15924] Fix stylelint after switching to trusty builds
  travis/check-stylesheet.sh
Labels: 3.3 (Proteus)

#5485 [ticket/15919] Don't run lint test against node_modules
  tests/lint_test.php
Labels: 3.2 (Rhea), 3.3 (Proteus)

#5049 [ticket/15462] add bidi.css to stylesheet.css
  phpBB/styles/prosilver/template/overall_header.html
  phpBB/styles/prosilver/template/simple_header.html
  phpBB/styles/prosilver/theme/stylesheet.css
Labels: 3.3 (Proteus), Styles 🎨

#5497 [ticket/15927] Fix acp style tables width issue
  phpBB/adm/style/acp_main.html
  phpBB/adm/style/admin.css
Labels: 3.3 (Proteus), Styles 🎨

#5508 [ticket/15935] Don't install APCu if it's already installed
  travis/setup-php-extensions.sh
Labels: 3.2 (Rhea), Blocker :warning:

#5469 [ticket/15899] Add core.modify_attachment_sql_ary_on_* events
  phpBB/includes/message_parser.php
Labels: 3.2 (Rhea), Event

#5510 [ticket/15931] Fix PM report emails
  phpBB/language/en/email/report_pm.txt
  phpBB/phpbb/notification/type/report_pm.php
Labels: 3.2 (Rhea)
