Repository phpbb/phpbb, pull requests merged in 2019-08, with the labels that each got.

#5647 [ticket/16119] Prevent error message for Poll Title
  phpBB/styles/prosilver/template/posting_poll_body.html
Labels: Styles 🎨

#5649 [ticket/16126] Downgrade chocolatey to a working version
  .appveyor.yml
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, 4.0 (Proteus) 🔮

#5634 [ticket/16111] Add core.message_history_modify_sql_ary
  phpBB/includes/functions_privmsgs.php
Labels: 3.2 (Rhea), Event 🔌

#5651 [ticket/15897] Fix Emojis' SQL Error in Attachment Comment
  phpBB/includes/functions_posting.php
  phpBB/language/en/posting.php
Labels: 3.2 (Rhea), Language/Text 🌐, php 🐘

#5643 [ticket/16113] Add core.mcp_topic_modify_sql_ary
  phpBB/includes/mcp/mcp_topic.php
Labels: 3.2 (Rhea), Event 🔌

#5637 [ticket/16054] Restore ability to login from any template.
  phpBB/includes/functions.php
  phpBB/index.php
  phpBB/viewforum.php
Labels: 3.2 (Rhea)

#5645 [ticket/16124] Fix users search by last visit time in memberlist.php
  phpBB/memberlist.php
Labels: 3.2 (Rhea)

#5648 [ticket/16109] Fix Custom Profile Field visibility's explain
  phpBB/language/en/acp/profile.php
Labels: 3.2 (Rhea), Language/Text 🌐

#5655 [ticket/16093] Ensure attach row is visible after upload with javascript
  phpBB/assets/javascript/plupload.js
Labels: 3.2 (Rhea), Blocker :warning:, Styles 🎨

#5653 [ticket/16129] Enhance attachment's ALT tag
  phpBB/styles/prosilver/template/attachment.html
Labels: 3.2 (Rhea), Styles 🎨

#5658 [ticket/13175] Check if account is already linked when using OAuth
  phpBB/language/en/common.php
  phpBB/phpbb/auth/provider/oauth/oauth.php
Labels: 3.2 (Rhea)

#5662 [ticket/16134] Exclude group leaders on group member purge
  phpBB/includes/acp/acp_prune.php
Labels: 3.2 (Rhea), Blocker :warning:

#5661 [ticket/16136] Reword sentence for account already linked
  phpBB/language/en/common.php
Labels: 3.2 (Rhea), Blocker :warning:
