Repository phpbb/phpbb, pull requests merged in 2019-06, with the labels that each got.

#5614 [ticket/16072] Update s9e/text-formatter
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/phpbb/textformatter/s9e/bbcode_merger.php
Labels: 3.3 (Rhea) 🌑

#5613 [ticket/16071] Undefined index for custom attachments groups
  phpBB/includes/acp/acp_attachments.php
Labels: 3.2 (Rhea)

#5607 [ticket/15974] Remove Back to previous page link
  phpBB/styles/prosilver/template/ucp_agreement.html
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, HMTL 📝

#5612 [ticket/15932] Disallow deleting locked attachments
  phpBB/includes/ucp/ucp_attachments.php
  phpBB/language/en/ucp.php
  phpBB/styles/prosilver/template/ucp_attachments.html
Labels: 3.2 (Rhea)

#5615 [ticket/16073] Fix warning in ACP version check
  phpBB/includes/acp/acp_update.php
Labels: 3.2 (Rhea)

#5617 [ticket/16078] Use chrome as webdriver
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.2 (Rhea)

#5603 [ticket/16000] Link to php's date()
  phpBB/language/en/acp/board.php
  phpBB/language/en/ucp.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, Language/Text 🌐

#5573 [ticket/16024] Add core.topic_review_modify_sql_ary
  phpBB/includes/functions_posting.php
Labels: Event 🔌

#5594 [ticket/16061] Migrator to drop unique indexes when needed
  phpBB/phpbb/db/tools/tools.php
Labels: 3.2 (Rhea)

#5595 [ticket/16063] Remove board_dst config value since unused
  phpBB/phpbb/db/migration/data/v32x/timezone_p3.php
Labels: 3.2 (Rhea)

#5597 [ticket/16065] Add user_ip to SQL query
  phpBB/phpbb/auth/provider/oauth/oauth.php
Labels: 3.2 (Rhea)

#5599 [ticket/16068] Adjust DocBlock @param's
  phpBB/includes/functions_messenger.php
  phpBB/phpbb/auth/provider/provider_interface.php
Labels: 3.2 (Rhea)

#5600 [ticket/16047] Improve wording for PM permissions
  phpBB/language/en/acp/permissions_phpbb.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, Language/Text 🌐

#5602 [ticket/16003] Fix num_posts sync
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑

#5604 [ticket/15984] Use private cache-control
  phpBB/includes/functions_download.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑

#5616 [ticket/16074] Fix Twemoji URL for ZWJ sequences
  phpBB/composer.lock
  tests/text_processing/tickets_data/PHPBB3-16074.html
  tests/text_processing/tickets_data/PHPBB3-16074.txt
Labels: 3.2 (Rhea)

#5620 [ticket/16075] Fix warning in PM filter
  phpBB/includes/functions_privmsgs.php
Labels: 3.2 (Rhea)

#5608 [ticket/15967] Improve admin activate email wording
  phpBB/language/en/email/admin_activate.txt
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, Language/Text 🌐

#5582 Make sure $phpbb_container is not null before trying to get anything …
  phpBB/includes/functions.php
Labels: 4.0 (Proteus) 🔮

#5623 [ticket/16078] Use headless chrome and disable gpu acceleration
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.2 (Rhea)
