Repository phpbb/phpbb, pull requests merged in 2019-09, with the labels that each got.

#5659 [ticket/16131] Force vagrant to install phpBB with php7.2
  vagrant/after.sh
Labels: 3.3 (Rhea) 🌑

#5666 [ticket/16084] Remove redundant backup radio button
  phpBB/adm/style/acp_database.html
  phpBB/includes/acp/acp_database.php
Labels: 3.2 (Rhea)

#5693 [ticket/16160] Add script for generating package json file
  build/generate_package_json.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑, 4.0 (Proteus) 🔮

#5688 [ticket/16156] Fix bots seeing register and logout links
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea)

#5687 [ticket/16157] Fix FORM_INVALID error in the sending email form
  phpBB/phpbb/message/form.php
Labels: 3.2 (Rhea)

#5673 [ticket/15643] Fix open_basedir warnings
  phpBB/phpbb/filesystem/filesystem.php
Labels: 3.2 (Rhea)

#5669 [ticket/16143] Add new events before and after move topics
  phpBB/includes/functions_admin.php
Labels: 3.2 (Rhea)

#5665 [ticket/16139] Add core.viewtopic_modify_quick_reply_template_vars
  phpBB/viewtopic.php
Labels: Event 🔌, php 🐘

#5676 [ticket/15422] Remove redundant BBCode helpline
  phpBB/adm/style/acp_posting_buttons.html
  phpBB/assets/javascript/editor.js
  phpBB/includes/functions_display.php
  phpBB/styles/prosilver/template/posting_buttons.html
Labels: 3.2 (Rhea)

#5677 [ticket/14815] Enable contact links in memberlist
  phpBB/memberlist.php
  phpBB/styles/prosilver/template/memberlist_body.html
Labels: 3.2 (Rhea)

#5678 [ticket/16148] Add template events to acp_groups.html
  phpBB/adm/style/acp_groups.html
  phpBB/docs/events.md
Labels: 3.2 (Rhea), Event 🔌

#5694 [ticket/15436] Remove folder icons code from index
  phpBB/index.php
Labels: 3.3 (Rhea) 🌑

#5511 [ticket/15940] Expose user_id to notif method's is_available()
  phpBB/phpbb/notification/type/approve_post.php
  phpBB/phpbb/notification/type/approve_topic.php
Labels: 3.3 (Rhea) 🌑

#5699 [ticket/15905] Adjust tests for twig extensions for master branch
  tests/template/extension_test.php
Labels: 4.0 (Proteus) 🔮
