Repository phpbb/phpbb, pull requests merged in 2019-10, with the labels that each got.

#5701 [ticket/15922] Remove driver for discontinued APC cache
  phpBB/phpbb/cache/driver/apc.php
  tests/RUNNING_TESTS.md
  tests/cache/apc_driver_test.php
Labels: 3.3 (Rhea) 🌑

#5702 [ticket/14465] Remove setting for maximum password length
  phpBB/includes/acp/acp_board.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/includes/ucp/ucp_register.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/ucp.php
  phpBB/phpbb/console/command/user/add.php
  phpBB/phpbb/db/migration/data/v330/remove_max_pass_chars.php
  phpBB/phpbb/ucp/controller/reset_password.php
  tests/console/user/base.php
Labels: 3.3 (Rhea) 🌑

#5700 [ticket/16175] Update composer dependencies for 3.3.0-b1
  phpBB/composer.lock
Labels: 3.3 (Rhea) 🌑

#5714 [ticket/16043] Check if not null before getting anything from the container
  phpBB/includes/functions.php
Labels: 3.3 (Rhea) 🌑

#5712 [ticket/16184] Don't entity-encode & character in AJAX response
  phpBB/includes/functions_display.php
  phpBB/viewforum.php
Labels: 3.2 (Rhea)

#5715 [ticket/16078] Try using retries for timeout issue
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.2 (Rhea)

#5710 [ticket/16182] Add core.generate_smilies_modify_rowset
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea)

#5703 [ticket/16174] Add core.set_cookie
  phpBB/phpbb/session.php
Labels: 3.2 (Rhea), Event 🔌

#5704 [ticket/16172] Add group rank label to group view
  phpBB/styles/prosilver/template/memberlist_body.html
Labels: 3.2 (Rhea)

#5716 [ticket/15437] Update jQuery and cookie consent to latest
  phpBB/adm/style/installer_footer.html
  phpBB/adm/style/overall_footer.html
  phpBB/adm/style/simple_footer.html
  phpBB/assets/cookieconsent/cookieconsent.min.css
  phpBB/assets/cookieconsent/cookieconsent.min.js
  phpBB/assets/javascript/jquery-3.4.1.min.js
  phpBB/assets/javascript/jquery.min.js
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/phpbb/db/migration/data/v330/jquery_update.php
  phpBB/phpbb/install/controller/helper.php
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/styles/prosilver/template/simple_footer.html
Labels: 3.3 (Rhea) 🌑, JS ☕

#5674 [ticket/16147] Updated tokens legend in BBCodes ACP
  phpBB/language/en/acp/posting.php
Labels: 3.2 (Rhea)

#5711 [ticket/16183] Add core.generate_smilies_count_sql_before
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea)

#5695 [ticket/16161] Enable BBcodes without closing tag
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/language/en/acp/posting.php
Labels: php 🐘

#5721 [ticket/16192] Fix CLI extension not enableable messages
  phpBB/phpbb/console/command/extension/enable.php
Labels: 3.3 (Rhea) 🌑

#5672 [ticket/16146] New core event: after move forum
  phpBB/includes/acp/acp_forums.php
Labels: 3.2 (Rhea), Event 🔌

#5682 [ticket/16151] Enable Emojis and rich text in forum name
  phpBB/includes/acp/acp_forums.php
  phpBB/includes/utf/utf_tools.php
Labels: php 🐘

#5709 [ticket/16181] Enforce string for OAuth provider id
  phpBB/phpbb/auth/provider/oauth/oauth.php
Labels: 3.2 (Rhea)
