Repository phpbb/phpbb, pull requests merged in 2019-07, with the labels that each got.

#5625 [ticket/16093] Do not display attach-row-tpl
  phpBB/styles/prosilver/template/posting_attach_body.html
  phpBB/styles/prosilver/theme/plupload.css
Labels: 3.2 (Rhea), Styles 🎨

#5572 [ticket/16023] Add core.message_history_modify_template_vars
  phpBB/includes/functions_privmsgs.php
Labels: Event 🔌

#5618 [ticket/16081] Remove eAccelerator cache driver
  phpBB/phpbb/cache/driver/eaccelerator.php
Labels: 3.3 (Rhea) 🌑

#5619 [ticket/16082] Remove XCache as it does not support PHP 7
  phpBB/phpbb/cache/driver/xcache.php
Labels: 3.3 (Rhea) 🌑

#5606 [ticket/15976] Reset user_passchg only if user changed password
  phpBB/includes/ucp/ucp_profile.php
Labels: 3.2 (Rhea)

#5609 [ticket/15946] Add core.posting_modify_row_data
  phpBB/posting.php
Labels: 3.2 (Rhea), Event 🔌

#5624 [ticket/16089] Add core.confirm_box_ajax_before
  phpBB/includes/functions.php
Labels: 3.2 (Rhea), Event 🔌

#5610 [ticket/16070] Remove support for WebSTAR and Xitami
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5565 [ticket/16016] Add a base class for native password hashing
  phpBB/phpbb/passwords/driver/argon2i.php
  phpBB/phpbb/passwords/driver/base_native.php
Labels: 3.3 (Rhea) 🌑

#5629 [ticket/16102] Add core.posting_modify_post_subject
  phpBB/posting.php
Labels: 3.2 (Rhea), Event 🔌

#5630 [ticket/16103] Add core.pm_modify_message_subject
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: 3.2 (Rhea), Event 🔌

#5631 [ticket/16106] Add core.mcp_main_before
  phpBB/includes/mcp/mcp_main.php
Labels: 3.2 (Rhea), Event 🔌

#5626 [ticket/16096] Use InnoDB fulltext limits for InnoDB tables
  phpBB/phpbb/search/fulltext_mysql.php
Labels: 3.2 (Rhea)

#5601 [ticket/16013] Allow admins to use disallowed username
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions_user.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑

#5494 [ticket/15885] Display group rank on memberlist_body
  phpBB/memberlist.php
Labels: 3.2 (Rhea), 3.3 (Rhea) 🌑

#5636 [ticket/15886] Use getMockBuilder instead of removed getMock()
  tests/group/helper_test_case.php
  tests/notification/group_request_test.php
Labels: 3.3 (Rhea) 🌑, 4.0 (Proteus) 🔮

#5627 [ticket/16097] Add core.viewtopic_gen_sort_selects_before
  phpBB/viewtopic.php
Labels: 3.2 (Rhea), Event 🔌

#5638 [ticket/16112] Update composer dependencies for 3.2.x
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5639 [ticket/16112] Update composer dependencies for 3.3.x
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Rhea) 🌑

#5640 [ticket/16112] Update composer dependencies in master
  phpBB/composer.json
  phpBB/composer.lock
  tests/notification/group_request_test.php
Labels: 4.0 (Proteus) 🔮

#5635 [ticket/16066] Fix FORM_INVALID always returned for banned user.
  phpBB/includes/functions.php
Labels: 3.2 (Rhea)

#5628 [ticket/16101] Add Referrer-Policy header to phpBB's headers
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
Labels: 3.2 (Rhea)

#5644 [ticket/16115] Add PHP 7.4snapshot to travis CI build matrix
  .travis.yml
Labels: 3.3 (Rhea) 🌑, 4.0 (Proteus) 🔮

#5641 [ticket/16040] Forum list won't display topic icons containing a space.
  phpBB/styles/prosilver/template/viewforum_body.html
Labels: 3.2 (Rhea), Styles 🎨
