Repository phpbb/phpbb, pull requests merged in 2019-03, with the labels that each got.

#5539 [ticket/15975] Remove user notification data upon user deletion
  phpBB/includes/functions_user.php
  tests/console/user/base.php
  tests/functions/user_delete_test.php
  tests/functions_user/delete_user_test.php
Labels: 3.2 (Rhea)

#5542 [ticket/15980] update and move all npm dependencies to dev
  .stylelintrc
  package-lock.json
  package.json
  phpBB/styles/prosilver/theme/icons.css
  phpBB/styles/prosilver/theme/plupload.css
Labels: 4.0 (Proteus) 🌚, Blocker :warning:, Chameleon 🦄

#5533 [ticket/15965] Fix hardcoded directory [3.2.x only]
  phpBB/config/default/container/services_console.yml
  phpBB/phpbb/console/command/thumbnail/delete.php
  phpBB/phpbb/console/command/thumbnail/generate.php
  tests/console/thumbnail_test.php
Labels: 3.2 (Rhea)

#5512 [ticket/15941] Replace MAX to speed up query in update_post_information
  phpBB/includes/functions_posting.php
Labels: 3.2 (Rhea)

#5509 [ticket/15939] Fix Pagination docblocks
  phpBB/phpbb/pagination.php
Labels: 3.2 (Rhea)

#5544 [ticket/15986] Add missing language key for posting.php
  phpBB/language/en/posting.php
Labels: 3.2 (Rhea)

#5520 [ticket/15950] Add SQL transactions to mcp_main.php
  phpBB/includes/mcp/mcp_main.php
Labels: 3.2 (Rhea)

#5549 [ticket/15992] Fix breadcrumb structured data
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea), HMTL 📝, Styles 🎨

#5536 [ticket/15957] Disabling both choice
  phpBB/adm/style/acp_users_prefs.html
Labels: 3.2 (Rhea)

#5464 [ticket/15891] Add core.memberlist_modify_view_profile_template_vars
  phpBB/memberlist.php
Labels: Event 🔌

#5551 [ticket/15996] Rename dataProvider to not start with test_
  tests/dbal/migrator_tool_permission_test.php
Labels: 3.2 (Rhea)

#5553 [ticket/15997] Use higher than default timeout for webdriver connections
  tests/test_framework/phpbb_ui_test_case.php
Labels: 3.2 (Rhea)

#5460 [ticket/15889] Add core.memberlist_modify_memberrow_sql
  phpBB/memberlist.php
Labels: Event 🔌

#5524 [ticket/15953] add reported pm message borders
  phpBB/includes/ucp/ucp_pm_viewfolder.php
  phpBB/language/en/ucp.php
  phpBB/styles/prosilver/theme/cp.css
Labels: 3.2 (Rhea), Styles 🎨

#5541 [ticket/15978] Add core.index_mark_notification_after
  phpBB/index.php
Labels: 3.2 (Rhea), Event 🔌
