Repository phpbb/phpbb, pull requests merged in 2019-02, with the labels that each got.

#5530 [ticket/15959] Fix invalid CNAME record
  tests/network/checkdnsrr_test.php
Labels: 3.2 (Rhea)

#5529 [ticket/15960] Add SQL transactions to functions_admin.php
  phpBB/includes/functions_admin.php
Labels: 3.2 (Rhea)

#5487 [ticket/15918] Fix addslashes in mcp_ban.html
  phpBB/styles/prosilver/template/mcp_ban.html
Labels: JS :scroll:

#5507 [ticket/15938] Update classes in backupStaticAttributesBlacklist
  tests/test_framework/phpbb_database_test_case.php
  tests/test_framework/phpbb_test_case.php
Labels: 3.3 (Proteus)
