Repository phpbb/phpbb, pull requests merged in 2020-08, with the labels that each got.

#6032 [ticket/16559] Ensure event variables are defined in mcp_queue
  phpBB/includes/mcp/mcp_queue.php
Labels: 3.3 (Proteus) 🌑

#5938 [ticket/16430] Sort permissions
  phpBB/includes/acp/auth.php
Labels: 3.3 (Proteus) 🌑

#5969 [ticket/16472] [3.3.x] Remove UI tests
  .appveyor.yml
  .travis.yml
  phpunit.xml.dist
  tests/RUNNING_TESTS.md
  tests/bootstrap.php
  tests/test_framework/phpbb_ui_test_case.php
  tests/ui/permission_roles_test.php
  tests/ui/quick_links_test.php
  travis/phpunit-mariadb-travis.xml
  travis/phpunit-mysqli-travis.xml
  travis/phpunit-postgres-travis.xml
  travis/phpunit-sqlite3-travis.xml
Labels: 3.3 (Proteus) 🌑

#5970 [ticket/16472] [Master] Remove UI tests and php-webdriver/webdriver
  .appveyor.yml
  .travis.yml
  phpBB/composer.json
  phpBB/composer.lock
  phpunit.xml.dist
  tests/RUNNING_TESTS.md
  tests/bootstrap.php
  tests/test_framework/phpbb_ui_test_case.php
  tests/ui/permission_roles_test.php
  tests/ui/quick_links_test.php
  travis/phpunit-mariadb-travis.xml
  travis/phpunit-mysqli-travis.xml
  travis/phpunit-postgres-travis.xml
  travis/phpunit-sqlite3-travis.xml
Labels: 4.0 (Triton) 🔮

#6030 [ticket/16557] Support piping tracker XML to build_changelog.php
  build/build_changelog.php
Labels: 3.3 (Proteus) 🌑

#6035 [ticket/16571] Update s9e/text-formatter to 2.7.3
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6033 [ticket/16568] Fix responsive tabs
  phpBB/adm/style/admin.js
  phpBB/styles/prosilver/template/forum_fn.js
Labels: 3.3 (Proteus) 🌑

#6034 [ticket/16569] Fix massive margin between zoomed posts
  phpBB/styles/prosilver/theme/responsive.css
Labels: 3.3 (Proteus) 🌑

#6036 [ticket/16572] Update node modules to latest versions
  package-lock.json
  package.json
Labels: 4.0 (Triton) 🔮

#6012 [ticket/16533] Add autologin keys management UCP module events
  phpBB/docs/events.md
  phpBB/includes/ucp/ucp_profile.php
  phpBB/phpbb/session.php
  phpBB/styles/prosilver/template/ucp_profile_autologin_keys.html
  tests/functional/ucp_profile_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6039 [ticket/16583] Fix cancel button
  phpBB/adm/style/acp_search.html
  phpBB/includes/acp/acp_search.php
Labels: 3.3 (Proteus) 🌑

#6041 [ticket/16588] Updates link to plural rules from 3.2.x to 3.3.x
  phpBB/docs/coding-guidelines.html
  phpBB/includes/functions_compatibility.php
  phpBB/language/en/common.php
Labels: 3.3 (Proteus) 🌑

#6019 [ticket/16488] Fix not displaying min input element attribute when 0
  phpBB/includes/functions_acp.php
  tests/functions_acp/build_cfg_template_test.php
Labels: 3.3 (Proteus) 🌑

#5335 [ticket/15765] Add debug.url_generator
  phpBB/config/default/container/services_routing.yml
  phpBB/config/development/config.yml
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/routing/router.php
  tests/controller/common_helper_route.php
  tests/controller/controller_test.php
  tests/pagination/pagination_test.php
Labels: 4.0 (Triton) 🔮

#6007 [ticket/16526] Correctly handle ACP CSV settings
  phpBB/includes/acp/acp_board.php
  phpBB/includes/functions_acp.php
  phpBB/language/en/acp/common.php
  tests/functional/acp_post_settings_test.php
Labels: 3.3 (Proteus) 🌑

#5334 [ticket/12630] Add debug.url_matcher
  phpBB/config/default/container/services_routing.yml
  phpBB/config/development/config.yml
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/routing/router.php
  tests/controller/common_helper_route.php
  tests/controller/controller_test.php
  tests/pagination/pagination_test.php
Labels: 4.0 (Triton) 🔮
