Repository phpbb/phpbb, pull requests merged in 2020-01, with the labels that each got.

#5799 [ticket/15592] Fix attachments place inline button if BBCode is disabled
  phpBB/styles/prosilver/template/posting_attach_body.html
Labels: 3.2 (Rhea)

#5803 [ticket/16282] Adjust jQuery cdn url in schema_data
  phpBB/install/schemas/schema_data.sql
Labels: 3.2 (Rhea)

#5804 [ticket/16282] Adjust jQuery cdn url in schema_data
  phpBB/install/schemas/schema_data.sql
Labels: 3.3 (Rhea) 🌑

#5806 [ticket/16281] Fix Ajax refresh-data for extensions' Tab
  phpBB/adm/style/acp_ext_actions.html
  phpBB/includes/acp/acp_extensions.php
Labels: 3.3 (Rhea) 🌑

#5807 [ticket/16273] Check whether the index exists in memberlist - PHP 7.4
  phpBB/memberlist.php
Labels: 3.3 (Rhea) 🌑

#5809 [ticket/16285] Add sanity checks to migrations for 3.3
  phpBB/phpbb/db/migration/data/v330/add_display_unapproved_posts_config.php
  phpBB/phpbb/db/migration/data/v330/remove_attachment_flash.php
  phpBB/phpbb/db/migration/data/v330/v330b2.php
Labels: 3.3 (Rhea) 🌑

#5820 [ticket/16293] Do not update to hashes that don't support combined hashing
  phpBB/phpbb/cron/task/core/update_hashes.php
Labels: 3.3 (Rhea) 🌑, Blocker :warning:

#5817 [ticket/16290] Update to new SVG logo in package docs
  phpBB/docs/CHANGELOG.html
  phpBB/docs/FAQ.html
  phpBB/docs/INSTALL.html
  phpBB/docs/README.html
  phpBB/docs/assets/css/stylesheet.css
  phpBB/docs/assets/images/site_logo.gif
  phpBB/docs/assets/images/site_logo.svg
  phpBB/docs/auth_api.html
  phpBB/docs/coding-guidelines.html
Labels: 3.3 (Rhea) 🌑

#5818 [ticket/16266] Remove extra declaration of constants
  phpBB/phpbb/passwords/driver/argon2i.php
Labels: 3.3 (Rhea) 🌑

#5731 [ticket/16204] Remove hooks system
  phpBB/common.php
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_hook.yml
  phpBB/includes/functions.php
  phpBB/includes/hooks/index.php
  phpBB/phpbb/hook/finder.php
  phpBB/phpbb/template/base.php
  phpBB/phpbb/template/twig/twig.php
  phpBB/phpbb/user.php
Labels: 4.0 (Proteus) 🔮

#5824 [ticket/16311] Fix password length ACP setting explanation
  phpBB/language/en/acp/board.php
Labels: 3.3 (Proteus) 🌑

#5823 [ticket/16309] Fix smilies with a left square bracket
  phpBB/composer.lock
  tests/text_processing/tickets_data/PHPBB3-16309.html
  tests/text_processing/tickets_data/PHPBB3-16309.txt
  tests/text_processing/tickets_data/PHPBB3-16309.xml
Labels: 3.3 (Proteus) 🌑

#5826 [ticket/16308] Fix UCP reset password
  phpBB/styles/prosilver/template/ucp_reset_password.html
Labels: 3.3 (Proteus) 🌑

#5819 [ticket/16291] Add missing report time
  phpBB/styles/prosilver/template/mcp_front.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5808 [ticket/16284] Move 4.0 migrations to v400 folder
  phpBB/config/default/container/services_migrator.yml
  phpBB/config/installer/container/services_install_database.yml
  phpBB/develop/create_schema_files.php
  phpBB/phpbb/db/migration/data/v330/acp_storage_module.php
  phpBB/phpbb/db/migration/data/v330/add_storage_permission.php
  phpBB/phpbb/db/migration/data/v330/extensions_composer.php
  phpBB/phpbb/db/migration/data/v330/remove_attachment_download_mode.php
  phpBB/phpbb/db/migration/data/v330/storage_adapter_local_subfolders.php
  phpBB/phpbb/db/migration/data/v330/storage_attachment.php
  phpBB/phpbb/db/migration/data/v330/storage_avatar.php
  phpBB/phpbb/db/migration/data/v330/storage_backup.php
  phpBB/phpbb/db/migration/data/v400/acp_storage_module.php
  phpBB/phpbb/db/migration/data/v400/add_storage_permission.php
  phpBB/phpbb/db/migration/data/v400/dev.php
  phpBB/phpbb/db/migration/data/v400/extensions_composer.php
  phpBB/phpbb/db/migration/data/v400/extensions_composer_2.php
  phpBB/phpbb/db/migration/data/v400/remove_attachment_download_mode.php
  phpBB/phpbb/db/migration/data/v400/storage_adapter_local_subfolders.php
  phpBB/phpbb/db/migration/data/v400/storage_attachment.php
  phpBB/phpbb/db/migration/data/v400/storage_avatar.php
  phpBB/phpbb/db/migration/data/v400/storage_backup.php
  phpBB/phpbb/db/migration/data/v400/storage_track.php
  phpBB/phpbb/db/migration/migration.php
  phpBB/phpbb/db/migration/schema_generator.php
  phpBB/phpbb/db/migrator.php
  phpBB/phpbb/install/module/install_database/task/create_schema.php
  phpBB/phpbb/install/module/install_database/task/create_schema_file.php
  tests/dbal/migrator_test.php
  tests/extension/manager_test.php
  tests/extension/metadata_manager_test.php
  tests/migrator/convert_timezones_test.php
  tests/migrator/get_callable_from_step_test.php
  tests/migrator/schema_generator_test.php
  tests/notification/convert_test.php
  tests/test_framework/phpbb_database_test_case.php
  tests/test_framework/phpbb_database_test_connection_manager.php
  tests/test_framework/phpbb_functional_test_case.php
  tests/test_framework/phpbb_ui_test_case.php
Labels: 4.0 (Triton) 🔮

#5828 [ticket/16323] Replace the spaceless tag with its homologue filter
  phpBB/phpbb/template/twig/lexer.php
  phpBB/styles/prosilver/template/navbar_footer.html
Labels: 3.3 (Proteus) 🌑

#5830 [ticket/16328] Inform admins about PHP requirements in phpBB 3.3
  phpBB/includes/acp/acp_main.php
Labels: 3.2 (Rhea)

#5821 [ticket/16296] Adjust form token check for mark actions
  phpBB/includes/functions_privmsgs.php
  phpBB/includes/ucp/ucp_pm.php
  phpBB/includes/ucp/ucp_pm_viewfolder.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5813 [ticket/15712] Fix Emoji and rich text in PM subject & draft
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5814 [ticket/15079] Fix Emoji and rich text in subject of post draft
  phpBB/posting.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5822 [ticket/16307] Fix SQL time reporting when debug.sql_explain parameter is set
  phpBB/phpbb/db/driver/driver.php
Labels: 3.3 (Proteus) 🌑

#5836 [ticket/16316] Fix breadcrumbs markup validation
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5825 [ticket/16313] Remove http block from sample Nginx configuration file
  phpBB/docs/nginx.sample.conf
  travis/setup-webserver.sh
Labels: 3.3 (Proteus) 🌑

#5834 [ticket/15370] Loading indicator when submitting permissions
  phpBB/adm/style/ajax.js
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5843 [ticket/16342] Increase default hashing costs for Argon2 passwords
  phpBB/config/default/container/services_password.yml
  phpBB/phpbb/passwords/driver/argon2i.php
  tests/passwords/drivers_test.php
Labels: 3.3 (Proteus) 🌑
