Repository phpbb/phpbb, pull requests merged in 2020-06, with the labels that each got.

#5994 [ticket/16500] Fix attachments ordering for copy topic feature
  phpBB/includes/mcp/mcp_main.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5993 [ticket/16503] Fix WhoIs lookup
  phpBB/includes/functions_user.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5990 [ticket/16496] Fix html special chars in custom BBcode help line
  phpBB/adm/style/acp_posting_buttons.html
  phpBB/styles/prosilver/template/posting_buttons.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5996 [ticket/16506] Update credits to latest state
  phpBB/docs/CREDITS.txt
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5997 [ticket/16507] Fix incorrect call to sphinx_clean_search_string()
  phpBB/phpbb/search/fulltext_sphinx.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#6001 [ticket/16511] Fix typo when checking for phpbb_delete_users_pms()
  phpBB/includes/functions_user.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5995 [ticket/16505] Fix use of count() on non-Countable
  phpBB/phpbb/language/language.php
Labels: 3.2 (Rhea)

#5999 [ticket/16510] [3.2.x] Add config values to schema_data.sql
  phpBB/install/schemas/schema_data.sql
  phpBB/phpbb/db/migration/data/v32x/add_missing_config.php
  phpBB/phpbb/db/migration/data/v32x/font_awesome_update_cdn.php
  phpBB/phpbb/db/migration/data/v32x/font_awesome_update_cdn_fix_depends_on.php
  phpBB/phpbb/db/migrator.php
Labels: 3.2 (Rhea)

#5998 [ticket/16508] Fix WhoIs lookup
  phpBB/includes/functions_user.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#6000 [ticket/16510] [3.3.x] Add config values to schema_data.sql
  phpBB/install/schemas/schema_data.sql
  phpBB/phpbb/db/migration/data/v330/.htaccess
  phpBB/phpbb/db/migration/data/v33x/.htaccess
  tests/functional/feed_test.php
  tests/migrations/migrations_check_config_added_test.php
Labels: 3.3 (Proteus) 🌑

#6003 [ticket/16514] Move google_recaptcha_v3 migration from v330 to v33x
  phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php
Labels: 3.3 (Proteus) 🌑

#6004 [ticket/16510] [3.3.x] Add migration that makes sure config entry exists
  phpBB/phpbb/db/migration/data/v33x/fix_display_unapproved_posts_config.php
Labels: 3.3 (Proteus) 🌑

#5977 [ticket/16477] Restore .icon class selector in icons.css
  phpBB/styles/prosilver/theme/icons.css
Labels: 4.0 (Triton) 🔮, Styles 🎨

#5946 [ticket/16441] Remove deprecated core.ucp_register_agreement event
  phpBB/includes/ucp/ucp_register.php
Labels: 4.0 (Triton) 🔮, Event 🔌

#6008 [ticket/16397] Add method for retrieving user ID
  phpBB/phpbb/install/module/install_finish/task/install_extensions.php
  phpBB/phpbb/install/module/install_finish/task/notify_user.php
  phpBB/phpbb/session.php
  phpBB/phpbb/user.php
Labels: 3.3 (Proteus) 🌑

#6010 [ticket/16530] Ensure extensions can be installed during installation
  phpBB/phpbb/install/module/install_finish/task/install_extensions.php
Labels: 3.3 (Proteus) 🌑, Blocker :warning:

#6013 [ticket/16534] Add conversion prefix to all passwords that need conversion
  phpBB/phpbb/db/migration/data/v310/passwords_convert_p1.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑, Blocker :warning:
