Repository phpbb/phpbb, pull requests merged in 2020-10, with the labels that each got.

#6057 [ticket/16608] Modernize readme
  README.md
  phpBB/styles/all/imgs/svg/phpbb_logo_large_cosmic.svg
Labels: 3.3 (Proteus) 🌑

#6051 [ticket/16605] Fix possible SQL error on user registration
  phpBB/includes/ucp/ucp_register.php
Labels: 3.3 (Proteus) 🌑

#6049 [ticket/16604] Display warning messages on avatar upload setting issues
  phpBB/includes/acp/acp_board.php
  phpBB/language/en/common.php
  tests/functional/acp_avatar_settings_test.php
Labels: 3.3 (Proteus) 🌑

#6053 [ticket/16562] Add password requirements to reset
  phpBB/phpbb/ucp/controller/reset_password.php
  phpBB/styles/prosilver/template/ucp_reset_password.html
Labels: 3.3 (Proteus) 🌑

#6054 [ticket/16593] Define params in the constructor
  phpBB/phpbb/install/module/install_data/task/create_search_index.php
Labels: 3.3 (Proteus) 🌑

#6060 [ticket/16604] Remove checks for avatar upload path in avatar settings
  phpBB/includes/acp/acp_board.php
  tests/functional/acp_avatar_settings_test.php
Labels: 4.0 (Triton) 🔮

#6061 [ticket/16615] Update xo, yargs-parser, and dependencies
  package-lock.json
  package.json
Labels: 4.0 (Triton) 🔮

#6058 [ticket/16612] Restructure HTML of Terms PP COPPA
  phpBB/language/en/ucp.php
  phpBB/styles/prosilver/template/ucp_agreement.html
  phpBB/styles/prosilver/theme/content.css
Labels: 3.3 (Proteus) 🌑

#6062 [ticket/16616] Update composer dependencies to latest versions
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6063 [ticket/16616] Update composer dependencies to latest versions
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#5291 [ticket/15722] Allow forum topicrow pagination to use topicrow values
  phpBB/viewforum.php
Labels: 3.3 (Proteus) 🌑

#6068 [ticket/16619] Corrected spelling of non-existant
  phpBB/language/en/common.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6014 [ticket/16538] Add MySQL 8 tests
  .travis.yml
  phpBB/includes/functions_posting.php
  phpBB/install/convert/convertor.php
  phpBB/phpbb/db/driver/driver_interface.php
  phpBB/phpbb/db/driver/factory.php
  phpBB/phpbb/db/driver/mssql_base.php
  phpBB/phpbb/db/driver/mysqli.php
  phpBB/phpbb/db/driver/oracle.php
  phpBB/phpbb/db/driver/postgres.php
  phpBB/phpbb/db/driver/sqlite3.php
  tests/functional/smilies_test.php
  travis/setup-mysql8.sh
  travis/setup-phpbb.sh
Labels: 3.3 (Proteus) 🌑

#6069 [ticket/16625] Add mbstring to install docs
  phpBB/docs/INSTALL.html
Labels: 3.3 (Proteus) 🌑
