Repository phpbb/phpbb, pull requests merged in 2020-12, with the labels that each got.

#6089 [ticket/16613] Remove phpbb_ui_test_case.php
  tests/test_framework/phpbb_ui_test_case.php
Labels: 4.0 (Triton) 🔮

#6095 [ticket/16659] Use Github Actions for continuous integration
  .github/check-doctum-parse-errors.sh
  .github/check-executable-files.sh
  .github/check-image-icc-profiles.sh
  .github/ext-sniff.sh
  .github/ldap/base.ldif
  .github/ldap/slapd.conf
  .github/phing-sniff.sh
  .github/phpunit-mariadb-github.xml
  .github/phpunit-mssql-github.xml
  .github/phpunit-mysql-github.xml
  .github/phpunit-postgres-github.xml
  .github/phpunit-sqlite3-github.xml
  .github/prepare-extension.sh
  .github/setup-database.sh
  .github/setup-exiftool.sh
  .github/setup-ldap.sh
  .github/setup-phpbb.sh
  .github/setup-unbuffer.sh
  .github/setup-webserver.sh
  .github/workflows/tests.yml
  tests/functional/search/mysql_test.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6052 [ticket/16607] Update Oracle DBAL driver OCI8 aliases and functions
  phpBB/phpbb/db/driver/oracle.php
Labels: 3.3 (Proteus) 🌑

#6081 [ticket/16640] Show MCP link in menu
  phpBB/mcp.php
Labels: 3.3 (Proteus) 🌑

#6083 [ticket/16582] Fix SQL error on registration with Numbers CPF with no default value set
  phpBB/phpbb/profilefields/manager.php
  tests/functional/registration_test.php
Labels: 3.3 (Proteus) 🌑

#6098 [ticket/16667] Remove unused installer task
  phpBB/phpbb/install/module/install_database/task/create_schema.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6097 [ticket/16665] Fix Emoji for strings in board settings + new event
  phpBB/includes/acp/acp_board.php
Labels: 3.3 (Proteus) 🌑
