Repository phpbb/phpbb, pull requests merged in 2020-11, with the labels that each got.

#6071 [ticket/16630] Restore clean_formatting()'s behaviour
  phpBB/includes/functions_content.php
  phpBB/phpbb/textformatter/s9e/utils.php
  phpBB/phpbb/textformatter/utils_interface.php
  tests/text_formatter/s9e/utils_test.php
Labels: 3.3 (Proteus) 🌑

#6072 [ticket/16632] Update to composer version 2
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6073 [ticket/16632] Update to composer version 2 -- Master version
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6070 [ticket/16629] Fix ACP get_database_size() for MySql 8
  phpBB/includes/functions_admin.php
  tests/functional/acp_main_test.php
Labels: 3.3 (Proteus) 🌑

#6075 [ticket/16633] Update pull request template to remove 3.2.x
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6076 [ticket/16629] Fix ACP get_database_size() for MySql 8
  phpBB/includes/functions_admin.php
Labels: 3.3 (Proteus) 🌑

#6077 [ticket/16636] Add PHP 8.0 builds to TravisCI
  .travis.yml
  travis/setup-phpbb.sh
Labels: 3.3 (Proteus) 🌑

#5523 [ticket/15951] Add core events to mcp
  phpBB/includes/mcp/mcp_main.php
  phpBB/mcp.php
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6078 [ticket/16617] Add events to override message/PM BBCode status indications
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/posting.php
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6079 [ticket/16606] Add template events to ucp_pm_viewmessage.html
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6080 [ticket/16178] Make container_builder use same cache directory as Container
  phpBB/phpbb/di/container_builder.php
  tests/di/container_cache_directory_test.php
Labels: 3.3 (Proteus) 🌑
