Repository phpbb/phpbb, pull requests merged in 2020-07, with the labels that each got.

#6017 [ticket/16543] Update query-string in stylesheet.css to hashes
  build/update_stylesheet_querystrings.php
  phpBB/styles/prosilver/theme/stylesheet.css
Labels: 3.3 (Proteus) 🌑

#6015 [ticket/16539] Fix general SQL error for smilies mode on posting
  phpBB/includes/functions_posting.php
  tests/functional/smilies_test.php
Labels: 3.2 (Rhea)

#6025 [ticket/16550] Fix undefined variable url in PMs [3.2.x]
  phpBB/includes/functions_privmsgs.php
Labels: 3.2 (Rhea)

#6016 [ticket/16540] Fix wrong postbody margin RTL
  phpBB/styles/prosilver/theme/bidi.css
Labels: 3.3 (Proteus) 🌑

#6021 [ticket/16550] Fix undefined variable url in PMs
  phpBB/includes/functions_privmsgs.php
Labels: 3.3 (Proteus) 🌑

#6023 [ticket/16554] Align all .htaccess files to support Apache 2.4 directives
  phpBB/cache/.htaccess
  phpBB/config/.htaccess
  phpBB/files/.htaccess
  phpBB/images/avatars/upload/.htaccess
  phpBB/includes/.htaccess
  phpBB/store/.htaccess
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#6026 [ticket/16552] Roll back to FontAwesome 4.7
  phpBB/adm/style/admin.css
  phpBB/adm/style/overall_header.html
  phpBB/assets/css/font-awesome.min.css
  phpBB/assets/css/phpbb-fontawesome-v4-shims.min.css
  phpBB/assets/fonts/FontAwesome.otf
  phpBB/assets/fonts/fontawesome-webfont.eot
  phpBB/assets/fonts/fontawesome-webfont.svg
  phpBB/assets/fonts/fontawesome-webfont.ttf
  phpBB/assets/fonts/fontawesome-webfont.woff
  phpBB/assets/fonts/fontawesome-webfont.woff2
  phpBB/assets/webfonts/fa-brands-400.eot
  phpBB/assets/webfonts/fa-brands-400.svg
  phpBB/assets/webfonts/fa-brands-400.ttf
  phpBB/assets/webfonts/fa-brands-400.woff
  phpBB/assets/webfonts/fa-brands-400.woff2
  phpBB/assets/webfonts/fa-regular-400.eot
  phpBB/assets/webfonts/fa-regular-400.svg
  phpBB/assets/webfonts/fa-regular-400.ttf
  phpBB/assets/webfonts/fa-regular-400.woff
  phpBB/assets/webfonts/fa-regular-400.woff2
  phpBB/assets/webfonts/fa-solid-900.eot
  phpBB/assets/webfonts/fa-solid-900.svg
  phpBB/assets/webfonts/fa-solid-900.ttf
  phpBB/assets/webfonts/fa-solid-900.woff
  phpBB/assets/webfonts/fa-solid-900.woff2
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/phpbb/db/migration/data/v33x/font_awesome_5_rollback.php
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/styles/prosilver/template/overall_header.html
  phpBB/styles/prosilver/template/simple_header.html
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/icons.css
  phpBB/styles/prosilver/theme/stylesheet.css
  tests/functional/forum_style_test.php
Labels: 3.3 (Proteus) 🌑

#6006 [ticket/16524] Fix using out-of-bounds UTF8 characters in profile fields
  phpBB/phpbb/profilefields/manager.php
  tests/functional/ucp_profile_test.php
Labels: 3.2 (Rhea)

#6028 [ticket/16417] Fix CLI database migration for phpBB 3.0.x
  phpBB/bin/phpbbcli.php
  phpBB/install/phpbbcli.php
  phpBB/phpbb/console/application.php
Labels: 3.2 (Rhea)

#6027 [ticket/16555] Update jQuery to 3.5.1
  phpBB/adm/style/installer_footer.html
  phpBB/adm/style/overall_footer.html
  phpBB/adm/style/simple_footer.html
  phpBB/assets/javascript/jquery-3.4.1.min.js
  phpBB/assets/javascript/jquery-3.5.1.min.js
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/install/schemas/schema_data.sql
  phpBB/phpbb/db/migration/data/v33x/jquery_update.php
  phpBB/phpbb/install/controller/helper.php
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/styles/prosilver/template/simple_footer.html
Labels: 3.3 (Proteus) 🌑, JS ☕
