Repository phpbb/phpbb, pull requests merged in 2020-03, with the labels that each got.

#5855 [ticket/10506] Preserve attachments on not-saving PM draft
  phpBB/includes/ucp/ucp_pm_compose.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5856 [ticket/16356] Delete attachments on saving a draft
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/posting.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5879 [ticket/15887] Reposition email after passwords in registration form
  phpBB/styles/prosilver/template/ucp_register.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5863 [ticket/16368] Container isFresh check order
  phpBB/phpbb/di/container_builder.php
Labels: 3.3 (Proteus) 🌑

#5864 [ticket/16376] Add default for display_subforum_limit
  phpBB/includes/functions_display.php
Labels: 3.3 (Proteus) 🌑

#5866 [ticket/16379] Update deprecated event dispatcher class
  phpBB/phpbb/event/dispatcher.php
Labels: 3.3 (Proteus) 🌑

#5867 [ticket/16378] Update deprecated console exception_subscriber event
  phpBB/phpbb/console/exception_subscriber.php
Labels: 3.3 (Proteus) 🌑

#5868 [ticket/16380] Exception_interface extends \Throwable
  phpBB/phpbb/exception/exception_interface.php
Labels: 3.3 (Proteus) 🌑

#5869 [ticket/16382] Update deprecated Twig_ classes
  phpBB/config/default/container/services_twig.yml
  phpBB/phpbb/feed/controller/feed.php
  phpBB/phpbb/template/twig/environment.php
  phpBB/phpbb/template/twig/extension.php
  phpBB/phpbb/template/twig/extension/avatar.php
  phpBB/phpbb/template/twig/extension/config.php
  phpBB/phpbb/template/twig/extension/username.php
  phpBB/phpbb/template/twig/lexer.php
  phpBB/phpbb/template/twig/loader.php
  phpBB/phpbb/template/twig/node/definenode.php
  phpBB/phpbb/template/twig/node/event.php
  phpBB/phpbb/template/twig/node/expression/binary/equalequal.php
  phpBB/phpbb/template/twig/node/expression/binary/notequalequal.php
  phpBB/phpbb/template/twig/node/includeasset.php
  phpBB/phpbb/template/twig/node/includenode.php
  phpBB/phpbb/template/twig/node/includephp.php
  phpBB/phpbb/template/twig/node/php.php
  phpBB/phpbb/template/twig/tokenparser/defineparser.php
  phpBB/phpbb/template/twig/tokenparser/event.php
  phpBB/phpbb/template/twig/tokenparser/includecss.php
  phpBB/phpbb/template/twig/tokenparser/includejs.php
  phpBB/phpbb/template/twig/tokenparser/includeparser.php
  phpBB/phpbb/template/twig/tokenparser/includephp.php
  phpBB/phpbb/template/twig/tokenparser/php.php
  phpBB/phpbb/template/twig/twig.php
Labels: 3.3 (Proteus) 🌑

#5870 [ticket/16381] Add core event to Modify Topics SQL
  phpBB/viewforum.php
Labels: Event 🔌

#5871 [ticket/16383] Add core events to modify friends list
  phpBB/ucp.php
Labels: Event 🔌

#5872 [ticket/16384] Add template events friends list username {prepend/append}
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_header.html
Labels: Event 🔌

#5875 [ticket/16289] Correct ampersand in report notification email
  phpBB/phpbb/notification/type/report_pm.php
  phpBB/phpbb/notification/type/report_post.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5876 [ticket/16163] Notice when no posts inside MCP topic
  phpBB/styles/prosilver/template/mcp_topic.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5878 [ticket/16377] Rename navlinks loop variable
  phpBB/styles/prosilver/template/navbar_header.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5873 [ticket/16325] Ensure lock file is opened for updating
  phpBB/phpbb/lock/flock.php
Labels: 3.3 (Proteus) 🌑

#5857 [ticket/16358] Hide attachment tab with no filters and display ACP notice
  phpBB/adm/style/acp_attachments.html
  phpBB/includes/acp/acp_attachments.php
  phpBB/language/en/acp/attachments.php
  phpBB/styles/prosilver/template/posting_editor.html
  phpBB/styles/prosilver/template/posting_layout.html
  phpBB/styles/prosilver/template/posting_pm_layout.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5880 [ticket/15438] Correct log language strings: from > for
  phpBB/language/en/acp/common.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5845 [ticket/16363] Allow replying to locked topics if user has m_lock permissions
  phpBB/posting.php
  phpBB/viewtopic.php
Labels: 3.3 (Proteus) 🌑

#5862 [ticket/16370] Add core events for Notification
  phpBB/includes/ucp/ucp_notifications.php
  phpBB/phpbb/notification/manager.php
Labels: Event 🔌

#5882 [ticket/16392] Update composer dependencies for 3.2
  composer.phar
  phpBB/composer.lock
Labels: 3.2 (Rhea)

#5883 [ticket/16392] Update composer dependencies for 3.3
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#5884 [ticket/16392] Update composer dependencies for master
  composer.phar
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#5877 [ticket/16121] Footer classes in simple_footer
  phpBB/styles/prosilver/template/simple_footer.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑, Styles 🎨

#5886 [ticket/16396] Use new php-webdriver instead facebook webdriver
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#5887 [ticket/16396] Use new php-webdriver instead of facebook webdriver
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#5885 [ticket/16394] Fix access array offset in MCP topic approval - PHP 7.4
  phpBB/mcp.php
Labels: 3.3 (Proteus) 🌑

#5888 [ticket/16388] Add online_list_before template events
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/viewforum_body.html
  phpBB/styles/prosilver/template/viewtopic_body.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5897 [ticket/16245] Cast attachment filesize to bigint
  phpBB/includes/acp/acp_attachments.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5898 [ticket/16225] Display style version in ACP
  phpBB/adm/style/acp_styles.html
  phpBB/includes/acp/acp_styles.php
Labels: 3.3 (Proteus) 🌑

#5910 [ticket/16405] Update npm dependencies to latest versions
  package-lock.json
  package.json
Labels: 4.0 (Triton) 🔮

#5904 [ticket/13914] Cast to INT mixed style ID data in user setup
  phpBB/phpbb/user.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5903 [ticket/16403] Fix attachment icon in MCP reports
  phpBB/styles/prosilver/template/mcp_reports.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5895 [ticket/16399] Fix Emoji in topic title for MCP split topic
  phpBB/includes/mcp/mcp_topic.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5889 [ticket/15609] MCP Queue and Report forum and topic identifiers
  phpBB/includes/mcp/mcp_queue.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/styles/prosilver/template/mcp_reports.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5890 [ticket/15979] Fix restoring/deleting when editing soft-deleted post
  phpBB/includes/functions_posting.php
  phpBB/posting.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5899 [ticket/16400] Add posting_editor_* events
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/posting_editor.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5893 [ticket/15275] Fix IP lookup pagination
  phpBB/includes/mcp/mcp_post.php
  phpBB/styles/prosilver/template/mcp_post.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5911 [ticket/16406] Fix Core Event of notification
  phpBB/phpbb/notification/manager.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5915 [ticket/16222] Fix timezone suggestion for 00:00
  phpBB/assets/javascript/core.js
Labels: 3.2 (Rhea), JS ☕

#5912 [ticket/16407] Fix MCP Post reported message
  phpBB/styles/prosilver/template/mcp_post.html
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑, HTML📝, Styles 🎨

#5891 [ticket/16391] Add extensions info_acp_ lang file to MCP logs
  phpBB/includes/mcp/mcp_logs.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑

#5928 [ticket/16419] Add mrgoldy to CREDITS.txt
  phpBB/docs/CREDITS.txt
Labels: Do not merge :hand:

#5901 [ticket/16122] Display user rank in MCP user notes
  phpBB/includes/mcp/mcp_notes.php
Labels: 3.2 (Rhea), 3.3 (Proteus) 🌑
