Repository phpbb/phpbb, pull requests merged in 2021-03, with the labels that each got.

#6149 [ticket/16712] Implement thumbnails for WEBP images in attachments
  phpBB/includes/functions_posting.php
Labels: 3.3 (Proteus) 🌑

#6148 [ticket/16711] Fix PHP 8.1 builds
  .github/setup-webserver.sh
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6091 [ticket/16654] Upgrade Twig to version 3
  phpBB/adm/style/acp_storage.html
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/phpbb/template/twig/environment.php
  phpBB/phpbb/template/twig/lexer.php
  phpBB/phpbb/template/twig/loader.php
  phpBB/phpbb/template/twig/node/event.php
  phpBB/phpbb/template/twig/node/expression/binary/equalequal.php
  phpBB/phpbb/template/twig/node/expression/binary/notequalequal.php
  phpBB/phpbb/template/twig/node/includenode.php
  phpBB/phpbb/template/twig/tokenparser/defineparser.php
  phpBB/phpbb/template/twig/tokenparser/includeparser.php
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
  tests/template/template_test.php
Labels: 4.0 (Triton) 🔮, dependencies

#4951 [ticket/15298] Makes sure CLI exceptions are never suppressed by Symfony
  phpBB/phpbb/console/exception_subscriber.php
Labels: 4.0 (Triton) 🔮

#6152 [ticket/16717] Set posts_table in indexing installer task
  phpBB/phpbb/install/module/install_data/task/create_search_index.php
Labels: 4.0 (Triton) 🔮

#6154 [ticket/16719] Fix PHP notice/warning on installation
  phpBB/install/app.php
Labels: 3.3 (Proteus) 🌑

#6141 [ticket/16705] Fix check_disk_space function - PHP 8
  phpBB/phpbb/attachment/upload.php
  tests/attachment/upload_test.php
Labels: 3.3 (Proteus) 🌑

#6158 [ticket/16724] Add some template events
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/mcp_forum.html
  phpBB/styles/prosilver/template/search_results.html
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6159 [ticket/16725] Add MCP core event
  phpBB/includes/mcp/mcp_forum.php
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6161 [ticket/16728] Add search result template event
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/search_results.html
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6160 [ticket/16726] Update composer & vendor packages to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6162 [ticket/16707] Disable unstable PHP 8.1 builds
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6168 [ticket/16732] Fix vagrant
  vagrant/after.sh
  vagrant/bootstrap.yaml
  vagrant/phpbb-install-config.yml
Labels: 4.0 (Triton) 🔮

#6170 [ticket/16736] Add sniffer for visibilitiy qualifiers before static keyword
  build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
  build/code_sniffer/ruleset-php-legacy.xml
  phpBB/phpbb/db/migration/data/v330/add_display_unapproved_posts_config.php
  phpBB/phpbb/db/migration/data/v330/remove_attachment_flash.php
  phpBB/phpbb/db/migration/data/v330/remove_max_pass_chars.php
  phpBB/phpbb/db/migration/data/v33x/default_search_return_chars.php
  phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php
  phpBB/phpbb/db/tools/mssql.php
  phpBB/phpbb/db/tools/postgres.php
  phpBB/phpbb/debug/debug.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6171 [ticket/16736] Fix static declarations on master
  phpBB/phpbb/composer/io/html_output_formatter.php
  phpBB/phpbb/config_php_file.php
  phpBB/phpbb/db/doctrine/connection_factory.php
  phpBB/phpbb/db/doctrine/connection_parameter_factory.php
  phpBB/phpbb/db/doctrine/driver_convertor.php
  phpBB/phpbb/db/migration/schema_generator.php
  phpBB/phpbb/filesystem/helper.php
  phpBB/phpbb/install/database_task.php
Labels: 4.0 (Triton) 🔮, Blocker :warning:

#6163 [ticket/16730] Don't do additional sorting or output without any tickets
  build/build_changelog.php
Labels: 3.3 (Proteus) 🌑

#6088 [ticket/16639] Pass absolute paths to make_path_relative
  phpBB/phpbb/filesystem/filesystem.php
  phpBB/phpbb/filesystem/filesystem_interface.php
  phpBB/phpbb/filesystem/helper.php
  phpBB/phpbb/storage/adapter/adapter_interface.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/stream_interface.php
  tests/filesystem/realpath_test.php
  tests/storage/adapter/local_subfolders_test.php
  tests/storage/adapter/local_test.php
  tests/storage/adapter/local_test_case.php
Labels: 4.0 (Triton) 🔮

#5543 [ticket/15515] Overhaul JS linting/testing with xo/eslint
  .jscsrc
  .jshintrc
  phpBB/adm/style/admin.js
  travis/check-js.sh
Labels: 4.0 (Triton) 🔮, Chameleon 🦄, JS ☕

#6175 [ticket/16675] Use github base branch head rev for commit message check
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6177 [ticket/16743] Properly check if TMP file exists - PHP 8
  phpBB/phpbb/files/filespec.php
Labels: 3.3 (Proteus) 🌑

#6169 [ticket/16735] Fix access array offset on value of type bool on login
  phpBB/phpbb/auth/provider/db.php
Labels: 3.3 (Proteus) 🌑
