Repository phpbb/phpbb, pull requests merged in 2021-01, with the labels that each got.

#6102 [ticket/16671] Code style fixes
  phpBB/phpbb/attachment/delete.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/phpbb/composer/extension_manager.php
  phpBB/phpbb/console/command/extension/install.php
  phpBB/phpbb/console/command/extension/manage.php
  phpBB/phpbb/console/command/extension/remove.php
  phpBB/phpbb/console/command/extension/update.php
  phpBB/phpbb/filesystem/helper.php
  phpBB/phpbb/install/module/install_data/task/add_modules.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/adapter_factory.php
  phpBB/phpbb/storage/file_info.php
  phpBB/phpbb/storage/storage.php
Labels: 4.0 (Triton) 🔮, Blocker :warning:

#6082 [ticket/16641] Fix config.php validation in ACP - PHP 8
  phpBB/includes/acp/acp_main.php
  phpBB/phpbb/filesystem/filesystem.php
Labels: 3.3 (Proteus) 🌑

#6103 Fix code sniffer bugs
  build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php
  phpBB/phpbb/attachment/delete.php
  phpBB/phpbb/attachment/resync.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/console/command/update/check.php
  phpBB/phpbb/controller/helper.php
  phpBB/phpbb/controller/resolver.php
  phpBB/phpbb/cron/event/cron_runner_listener.php
  phpBB/phpbb/cron/manager.php
  phpBB/phpbb/db/driver/factory.php
  phpBB/phpbb/db/extractor/mssql_extractor.php
  phpBB/phpbb/db/extractor/mysql_extractor.php
  phpBB/phpbb/db/extractor/postgres_extractor.php
  phpBB/phpbb/db/extractor/sqlite3_extractor.php
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/di/service_collection.php
  phpBB/phpbb/files/upload.php
  phpBB/phpbb/install/console/command/install/install.php
  phpBB/phpbb/install/console/command/update/update.php
  phpBB/phpbb/install/controller/helper.php
  phpBB/phpbb/install/helper/container_factory.php
  phpBB/phpbb/install/helper/database.php
  phpBB/phpbb/install/helper/iohandler/factory.php
  phpBB/phpbb/install/installer.php
  phpBB/phpbb/install/installer_configuration.php
  phpBB/phpbb/install/module/install_data/task/add_modules.php
  phpBB/phpbb/install/module/install_finish/task/notify_user.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_admin_data.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_board_data.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_database_data.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_file_updater_method.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_update_ftp_data.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_update_settings.php
  phpBB/phpbb/install/updater_configuration.php
  phpBB/phpbb/language/language.php
  phpBB/phpbb/language/language_file_loader.php
  phpBB/phpbb/module/module_manager.php
  phpBB/phpbb/notification/method/email.php
  phpBB/phpbb/notification/method/messenger_base.php
  phpBB/phpbb/report/controller/report.php
  phpBB/phpbb/report/exception/factory_invalid_argument_exception.php
  phpBB/phpbb/report/exception/invalid_report_exception.php
  phpBB/phpbb/report/handler_factory.php
  phpBB/phpbb/report/report_handler.php
  phpBB/phpbb/report/report_handler_pm.php
  phpBB/phpbb/report/report_handler_post.php
  phpBB/phpbb/template/twig/twig.php
  phpBB/phpbb/textformatter/s9e/bbcode_merger.php
  phpBB/phpbb/textformatter/s9e/factory.php
Labels: 3.3 (Proteus) 🌑, Blocker :warning:

#6105 [ticket/16672] Fix invalid lang key content for delete backup in ACP
  phpBB/includes/acp/acp_database.php
  phpBB/language/en/acp/database.php
Labels: 4.0 (Triton) 🔮, Language/Text 🌐, php 🐘

#6084 [ticket/16645] Simplified text_reparser.poll_option
  phpBB/config/default/container/services_text_reparser.yml
  phpBB/phpbb/textreparser/plugins/poll_option.php
  tests/text_reparser/plugins/poll_option_test.php
Labels: 3.3 (Proteus) 🌑

#6085 [ticket/16646] Fix PHP fatal error on installation
  phpBB/phpbb/install/helper/container_factory.php
Labels: 3.3 (Proteus) 🌑

#6086 [ticket/16648] Fix possible Access to undeclared static property error in tests
  tests/test_framework/phpbb_test_case_helpers.php
Labels: 3.3 (Proteus) 🌑

#6090 [ticket/16653] Fix Recaptcha-v3 default request method
  phpBB/language/en/captcha_recaptcha.php
  phpBB/phpbb/captcha/plugins/recaptcha_v3.php
Labels: 3.3 (Proteus) 🌑

#6108 [ticket/16677] Copy event listeners and element data when populating dropdown
  phpBB/styles/prosilver/template/forum_fn.js
Labels: 3.3 (Proteus) 🌑, JS ☕

#6101 [ticket/16670] Fix ACP check-in for OAuth provider keys - PHP 8
  phpBB/includes/acp/acp_board.php
Labels: 3.3 (Proteus) 🌑

#6109 [ticket/16676] Cache composer dependencies for github actions
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6106 [ticket/16674] Update text-formatter
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑, dependencies

#6112 [ticket/16678] Allow using traits
  build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php
Labels: 3.3 (Proteus) 🌑, Blocker :warning:

#6111 [ticket/16675] Restore commit message checks
  .github/workflows/tests.yml
  git-tools/commit-msg-hook-range.sh
Labels: 3.3 (Proteus) 🌑

#6093 [ticket/16656] Fix ACP check-in for mbstring http_input & output
  phpBB/adm/style/acp_main.html
  phpBB/includes/acp/acp_main.php
  phpBB/language/en/acp/common.php
Labels: 3.3 (Proteus) 🌑

#6113 [ticket/16666] Exclude PGDATA directory in Windows Defender
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6099 [ticket/16668] Refactor schema_generator
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/phpbb/db/migration/schema_generator.php
  tests/dbal/migration/dummy_order_0.php
  tests/dbal/migration/dummy_order_1.php
  tests/dbal/migration/dummy_order_2.php
  tests/dbal/migration/dummy_order_3.php
  tests/dbal/migration/dummy_order_4.php
  tests/dbal/migration/dummy_order_5.php
Labels: 4.0 (Triton) 🔮, dependencies

#6117 [ticket/16675] Adjust checking commit messages
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6116 [ticket/16679] Respect "allow password reset" setting on login
  phpBB/includes/functions.php
  phpBB/index.php
Labels: 3.3 (Proteus) 🌑

#6122 [ticket/16686] Simplify get_database_size() SQL query for PostgreSQL
  phpBB/includes/functions_admin.php
Labels: 3.3 (Proteus) 🌑

#6121 [ticket/16685] Fix SQL error in ACP for DB name if not correctly escaped
  phpBB/includes/functions_admin.php
Labels: 3.3 (Proteus) 🌑

#6124 [ticket/16675] Restore rxu's fix
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6123 [ticket/16687] Add check stylesheet with stylelint to github workflow
  .github/check-stylesheet.sh
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮

#6119 [ticket/16650] Adjust code for retrieving packagist info for composer 2
  phpBB/phpbb/composer/installer.php
Labels: 4.0 (Triton) 🔮

#6118 [ticket/16681] Use Font Icons for ACP Action Buttons
  phpBB/adm/style/admin.css
  phpBB/adm/style/admin.js
  phpBB/includes/functions_acp.php
Labels: 3.3 (Proteus) 🌑, Styles 🎨

#6125 [ticket/16660] Remove not needed RESET button from MCP and UCP
  phpBB/styles/prosilver/template/mcp_ban.html
  phpBB/styles/prosilver/template/mcp_notes_front.html
  phpBB/styles/prosilver/template/mcp_notes_user.html
  phpBB/styles/prosilver/template/mcp_warn_front.html
  phpBB/styles/prosilver/template/mcp_warn_post.html
  phpBB/styles/prosilver/template/mcp_warn_user.html
  phpBB/styles/prosilver/template/memberlist_search.html
  phpBB/styles/prosilver/template/search_body.html
  phpBB/styles/prosilver/template/ucp_avatar_options.html
  phpBB/styles/prosilver/template/ucp_groups_manage.html
  phpBB/styles/prosilver/template/ucp_main_drafts.html
  phpBB/styles/prosilver/template/ucp_prefs_personal.html
  phpBB/styles/prosilver/template/ucp_prefs_post.html
  phpBB/styles/prosilver/template/ucp_prefs_view.html
  phpBB/styles/prosilver/template/ucp_profile_profile_info.html
  phpBB/styles/prosilver/template/ucp_profile_reg_details.html
  phpBB/styles/prosilver/template/ucp_profile_signature.html
  phpBB/styles/prosilver/template/ucp_register.html
  phpBB/styles/prosilver/template/ucp_resend.html
  phpBB/styles/prosilver/template/ucp_reset_password.html
  phpBB/styles/prosilver/template/ucp_zebra_foes.html
  phpBB/styles/prosilver/template/ucp_zebra_friends.html
Labels: 3.3 (Proteus) 🌑

#6133 [ticket/16691] Fix illegal offset for report_pm_closed notification
  phpBB/phpbb/notification/type/report_pm_closed.php
Labels: 3.3 (Proteus) 🌑

#6128 [ticket/16689] Fix SQL errors for Bitly OAuth
  phpBB/language/en/common.php
  phpBB/phpbb/auth/provider/oauth/service/bitly.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#4129 [ticket/10824] Use composer.json in styles/languages
  phpBB/adm/style/acp_language.html
  phpBB/adm/style/acp_styles.html
  phpBB/includes/acp/acp_language.php
  phpBB/includes/acp/acp_styles.php
  phpBB/includes/functions.php
  phpBB/includes/functions_compatibility.php
  phpBB/language/en/acp/language.php
  phpBB/language/en/acp/styles.php
  phpBB/language/en/composer.json
  phpBB/language/en/iso.txt
  phpBB/phpbb/cache/service.php
  phpBB/phpbb/db/migration/data/v310/style_update_p1.php
  phpBB/phpbb/db/migration/data/v31x/style_update.php
  phpBB/phpbb/json/sanitizer.php
  phpBB/phpbb/language/language_file_helper.php
  phpBB/phpbb/version_helper.php
  phpBB/styles/prosilver/composer.json
  phpBB/styles/prosilver/style.cfg
  tests/json/sanitizer_test.php
Labels: 4.0 (Triton) 🔮

#4453 [ticket/11063] Use HTTPS for phpBB's version check
  phpBB/phpbb/version_helper.php
Labels: 4.0 (Triton) 🔮, WIP :construction:
