Repository phpbb/phpbb, pull requests merged in 2021-09, with the labels that each got.

#6282 [ticket/16858] Fix coding style
  phpBB/phpbb/db/migration/data/v33x/jquery_update_v2.php
Labels: Blocker :warning:, 3.3 (Proteus) 🌑

#6284 [ticket/16867] Update symfony and text-formatter to latest versions
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6285 [ticket/16867] Update symfony and text-formatter to latest versions -- master version
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6288 [ticket/16870] Ensure to properly escape values when running db:migrate
  phpBB/phpbb/config/db.php
  phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php
Labels: 3.3 (Proteus) 🌑

#6295 [ticket/16878] Default to threads value of 1 when using argon with libsodium
  phpBB/phpbb/passwords/driver/argon2i.php
Labels: 3.3 (Proteus) 🌑

#6296 [ticket/16879] Add events to phpbb_mail()
  phpBB/includes/functions_messenger.php
Labels: Event 🔌, 3.3 (Proteus) 🌑
