Repository phpbb/phpbb, pull requests merged in 2021-06, with the labels that each got.

#6222 [ticket/16787] Properly check if fsockopen() is enabled - PHP 8
  phpBB/phpbb/file_downloader.php
Labels: 3.3 (Proteus) 🌑

#6221 [ticket/16786] Migrate phpunit xml configuration to latest schema
  phpunit.xml.dist
Labels: 4.0 (Triton) 🔮

#6227 [ticket/16793] Fix topic/post attachments visibility - PHP 8
  phpBB/download/file.php
  phpBB/includes/functions_download.php
Labels: 3.3 (Proteus) 🌑

#6229 [ticket/16746] Update node packages
  package-lock.json
Labels: 4.0 (Triton) 🔮

#6230 [ticket/16798] Scale down phpbb logo on readme
  README.md
Labels: 3.3 (Proteus) 🌑

#6226 [ticket/16795] Add template events around signature in viewtopic
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/viewtopic_body.html
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6207 [ticket/13700] Add method for initializing config after cache purge
  phpBB/phpbb/config/db.php
  phpBB/phpbb/console/command/db/migrate.php
Labels: 3.3 (Proteus) 🌑

#6223 [ticket/16788] Update s9e/text-formatter to 2.9.3
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6224 [ticket/16789] Update user_delete() doc-block
  phpBB/includes/functions_user.php
Labels: 3.3 (Proteus) 🌑

#6234 [ticket/16729] Fix Unknown named parameter in Log - PHP 8
  phpBB/phpbb/log/log.php
Labels: 3.3 (Proteus) 🌑
