Repository phpbb/phpbb, pull requests merged in 2021-04, with the labels that each got.

#6176 [ticket/16740] Add method for ensuring resource is not passed to cache
  .github/workflows/tests.yml
  phpBB/phpbb/db/driver/postgres.php
  phpBB/phpbb/db/tools/postgres.php
  tests/test_framework/phpbb_database_test_case.php
Labels: 3.3 (Proteus) 🌑

#6178 [ticket/16746] Update node modules to latest versions
  .github/check-stylesheet.sh
  package-lock.json
  package.json
Labels: 4.0 (Triton) 🔮

#6181 [ticket/16747] Fix typo in post_in_queue.txt email template
  phpBB/language/en/email/post_in_queue.txt
  phpBB/language/en/email/short/post_in_queue.txt
Labels: 3.3 (Proteus) 🌑

#6182 [ticket/16748] Adjust coding guidelines to put static after visibility
  build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
  phpBB/docs/coding-guidelines.html
Labels: 3.3 (Proteus) 🌑

#6167 [ticket/16719] Fix PHP notice/warnings on update/install - PHP 8
  phpBB/includes/constants.php
  phpBB/install/app.php
Labels: 3.3 (Proteus) 🌑

#6184 [ticket/16749] Explicitly set default MySQLi error mode
  phpBB/phpbb/db/driver/mysqli.php
Labels: 3.3 (Proteus) 🌑

#6172 [ticket/16737] Rewrite acp_search
  phpBB/adm/style/acp_search.html
  phpBB/adm/style/acp_search_index.html
  phpBB/adm/style/acp_search_index_inprogress.html
  phpBB/adm/style/acp_search_settings.html
  phpBB/includes/acp/acp_search.php
  phpBB/phpbb/search/backend/base.php
  phpBB/phpbb/search/backend/fulltext_sphinx.php
  phpBB/phpbb/search/backend/search_backend_interface.php
  phpBB/phpbb/storage/provider/local.php
  phpBB/phpbb/storage/provider/provider_interface.php
Labels: 4.0 (Triton) 🔮

#5778 [ticket/15233] Standardize avatar output variables
  phpBB/adm/style/acp_groups.html
  phpBB/adm/style/acp_users_avatar.html
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_avatar.yml
  phpBB/config/default/container/services_user.yml
  phpBB/includes/acp/acp_groups.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions.php
  phpBB/includes/functions_display.php
  phpBB/includes/mcp/mcp_notes.php
  phpBB/includes/mcp/mcp_warn.php
  phpBB/includes/ucp/ucp_groups.php
  phpBB/includes/ucp/ucp_pm_viewmessage.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/memberlist.php
  phpBB/phpbb/avatar/helper.php
  phpBB/phpbb/group/helper.php
  phpBB/phpbb/notification/type/base.php
  phpBB/phpbb/user_loader.php
  phpBB/styles/prosilver/template/mcp_notes_user.html
  phpBB/styles/prosilver/template/mcp_warn_post.html
  phpBB/styles/prosilver/template/mcp_warn_user.html
  phpBB/styles/prosilver/template/memberlist_body.html
  phpBB/styles/prosilver/template/memberlist_view.html
  phpBB/styles/prosilver/template/navbar_header.html
  phpBB/styles/prosilver/template/notification_dropdown.html
  phpBB/styles/prosilver/template/ucp_avatar_options.html
  phpBB/styles/prosilver/template/ucp_notifications.html
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
  phpBB/styles/prosilver/template/viewtopic_body.html
  phpBB/viewtopic.php
  tests/console/user/base.php
  tests/group/helper_test_case.php
  tests/notification/base.php
  tests/notification/group_request_test.php
  tests/notification/notification_method_email_test.php
  tests/notification/submit_post_base.php
  tests/notification/user_list_trim_test.php
  tests/user/user_loader_test.php
Labels: 4.0 (Triton) 🔮, Chameleon 🦄

#6186 [ticket/16752] Add exporter for event into to restructured text
  phpBB/develop/export_events_for_rst.php
  phpBB/phpbb/event/md_exporter.php
  phpBB/phpbb/event/php_exporter.php
  phpBB/phpbb/event/rst_exporter.php
  tests/event/php_exporter_test.php
Labels: 3.3 (Proteus) 🌑

#6185 [ticket/16751] add rank-img class to template files for consistency with area51 and .com
  phpBB/styles/prosilver/template/mcp_notes_user.html
  phpBB/styles/prosilver/template/mcp_warn_post.html
  phpBB/styles/prosilver/template/mcp_warn_user.html
  phpBB/styles/prosilver/template/memberlist_body.html
  phpBB/styles/prosilver/template/memberlist_view.html
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
  phpBB/styles/prosilver/template/viewtopic_body.html
  phpBB/styles/prosilver/theme/content.css
Labels: 4.0 (Triton) 🔮, HTML📝, Styles 🎨

#6188 [ticket/16754] Update doctum.phar to 5.4
  .github/workflows/tests.yml
  doctum.phar
  phpBB/includes/functions.php
  phpBB/includes/functions_admin.php
  phpBB/includes/functions_compatibility.php
  phpBB/includes/functions_convert.php
  phpBB/includes/functions_mcp.php
  phpBB/includes/functions_messenger.php
  phpBB/includes/functions_user.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/includes/utf/utf_tools.php
  phpBB/phpbb/mimetype/guesser_interface.php
  phpBB/phpbb/search/fulltext_postgres.php
  phpBB/phpbb/search/fulltext_sphinx.php
  phpBB/phpbb/template/template.php
  phpBB/phpbb/template/twig/twig.php
  phpBB/phpbb/user_loader.php
  phpBB/phpbb/version_helper.php
Labels: 3.3 (Proteus) 🌑

#6191 [ticket/16761] add missing closing a tag to page-jump
  phpBB/styles/prosilver/template/pagination.html
Labels: 4.0 (Triton) 🔮, Styles 🎨

#6192 [ticket/16762] fix topicrow paging
  phpBB/styles/prosilver/template/mcp_forum.html
  phpBB/styles/prosilver/template/ucp_main_bookmarks.html
  phpBB/styles/prosilver/template/ucp_main_front.html
  phpBB/styles/prosilver/template/ucp_main_subscribed.html
  phpBB/styles/prosilver/template/viewforum_body.html
Labels: 4.0 (Triton) 🔮

#6194 [ticket/16763] fix imageset mine pip alignment
  phpBB/styles/prosilver/theme/icons.css
Labels: 4.0 (Triton) 🔮, Styles 🎨

#6196 [ticket/16764] Remove remote avatar functionality
  phpBB/adm/style/acp_avatar_options_remote.html
  phpBB/adm/style/acp_avatar_options_upload.html
  phpBB/config/default/container/services_avatar.yml
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/install/convertors/convert_phpbb20.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/common.php
  phpBB/language/en/help/faq.php
  phpBB/language/en/ucp.php
  phpBB/phpbb/avatar/driver/remote.php
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/phpbb/avatar/manager.php
  phpBB/phpbb/db/migration/data/v400/remove_remote_avatar.php
  phpBB/styles/prosilver/template/ucp_avatar_options_remote.html
  phpBB/styles/prosilver/template/ucp_avatar_options_upload.html
  tests/avatar/manager_test.php
  tests/functional/avatar_acp_groups_test.php
  tests/functional/avatar_acp_users_test.php
  tests/functional/avatar_ucp_groups_test.php
  tests/functional/avatar_ucp_users_test.php
  tests/functional/common_avatar_test_case.php
  tests/functional/common_groups_test_case.php
Labels: 4.0 (Triton) 🔮

#6200 [ticket/16767] Report missing migration instead of dependency
  phpBB/phpbb/db/migrator.php
Labels: 3.3 (Proteus) 🌑

#6189 [ticket/16757] Properly handle RTL text in ACP QA Captcha HTML
  phpBB/adm/style/captcha_qa_acp.html
Labels: 3.3 (Proteus) 🌑, Styles 🎨

#6197 [ticket/16764] Remove unused services
  phpBB/config/default/container/services_files.yml
  phpBB/includes/acp/acp_board.php
  phpBB/includes/constants.php
  phpBB/includes/functions_convert.php
  phpBB/install/convertors/functions_phpbb20.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/posting.php
  phpBB/phpbb/db/migration/data/v310/avatar_types.php
  phpBB/phpbb/db/migration/data/v400/remove_remote_upload.php
  phpBB/phpbb/files/types/remote.php
  phpBB/phpbb/files/types/remote_storage.php
  phpBB/phpbb/files/upload.php
  tests/files/type_foo.php
  tests/files/types_remote_test.php
  tests/functional/fileupload_remote_test.php
Labels: 4.0 (Triton) 🔮

#6198 [ticket/16766] Show long error messages during install/update
  phpBB/install/startup.php
Labels: 3.3 (Proteus) 🌑
