Repository phpbb/phpbb, pull requests merged in 2021-05, with the labels that each got.

#6202 [ticket/16769] Update composer & dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6203 [ticket/16769] Update composer & dependencies to latest versions -- master
  composer.phar
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6204 [ticket/16770] Rearrange static qualifier in 3.3.4 migration
  phpBB/phpbb/db/migration/data/v33x/v334.php
Labels: 3.3 (Proteus) 🌑, 4.0 (Triton) 🔮

#6199 [ticket/16765] Check if ACP_CONTACT_SETTINGS module already installed
  phpBB/phpbb/db/migration/data/v310/contact_admin_acp_module.php
Labels: 3.3 (Proteus) 🌑

#6205 [ticket/16740] Remove no longer supported and duplicate runs
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮

#6208 [ticket/16292] Propagate more errors to the installer UI
  phpBB/install/startup.php
Labels: 3.3 (Proteus) 🌑

#6212 [ticket/16746] Update node dev dependencies to latest versions & fix gulp
  .postcss-sorting.json
  gulpfile.js
  package-lock.json
  package.json
Labels: 4.0 (Triton) 🔮

#6211 [ticket/16773] Add missing constraints in PostgreSQL backups
  phpBB/phpbb/db/extractor/postgres_extractor.php
Labels: 3.3 (Proteus) 🌑, php 🐘

#5505 [ticket/15925] Add core events for sync and mcp functions
  phpBB/includes/functions_admin.php
  phpBB/includes/functions_posting.php
  phpBB/includes/mcp/mcp_main.php
Labels: 3.3 (Proteus) 🌑, Event 🔌

#6209 [ticket/16771] Add MCP core events
  phpBB/includes/mcp/mcp_front.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/includes/mcp/mcp_topic.php
Labels: Event 🔌

#6215 [ticket/16771] Add missing phpbb_dispatcher to globals
  phpBB/includes/mcp/mcp_topic.php
Labels: 4.0 (Triton) 🔮

#6210 [ticket/16772] Fix Emoji for Email signature
  phpBB/includes/acp/acp_board.php
Labels: 3.3 (Proteus) 🌑

#6216 [ticket/16570] Support continuing update on manually merging files
  phpBB/phpbb/install/module/update_filesystem/task/diff_files.php
  phpBB/phpbb/install/module/update_filesystem/task/download_updated_files.php
  phpBB/phpbb/install/module/update_filesystem/task/update_files.php
Labels: 3.3 (Proteus) 🌑

#6214 [ticket/16778] fix stylesheet.css
  phpBB/styles/prosilver/theme/stylesheet.css
Labels: 4.0 (Triton) 🔮, CSS 📐

#5757 [ticket/16240] Remove deprecated LOG_ template/theme language strings
  phpBB/language/en/acp/common.php
Labels: 4.0 (Triton) 🔮

#6217 [ticket/16782] Use alternative template for mention BBCode
  phpBB/assets/javascript/mentions.js
Labels: 4.0 (Triton) 🔮, JS ☕

#6213 [ticket/16775] Run xo linter in GitHub Actions runs
  .github/check-js.sh
  .github/workflows/tests.yml
  gulpfile.js
  package-lock.json
  package.json
  phpBB/adm/style/timezone.js
  phpBB/styles/prosilver/template/timezone.js
Labels: 4.0 (Triton) 🔮

#6219 [ticket/16784] ignore .vscode
  .gitignore
Labels: 3.3 (Proteus) 🌑

#6220 [ticket/16785] Use correct versions in build.xml for 3.3.x branch
  build/build.xml
Labels: 3.3 (Proteus) 🌑

#6218 [ticket/16783] Remove structure only backup
  phpBB/adm/style/acp_database.html
  phpBB/includes/acp/acp_database.php
  phpBB/language/en/acp/database.php
Labels: 3.3 (Proteus) 🌑
