Repository phpbb/phpbb, pull requests merged in 2021-08, with the labels that each got.

#6266 [ticket/16840] Add more PHP 8.x builds to tests matrix
  .github/setup-webserver.sh
  .github/workflows/tests.yml
  phpBB/phpbb/db/driver/postgres.php
  tests/test_framework/phpbb_test_case_helpers.php
Labels: 4.0 (Triton) 🔮

#6271 [ticket/16850][3.3] Update webfont loader
  phpBB/styles/prosilver/template/overall_header.html
Labels: Styles 🎨, JS ☕, HTML📝

#6270 [ticket/16850][4.0] Update webfont loader
  phpBB/styles/prosilver/template/overall_header.html
Labels: Styles 🎨, JS ☕, HTML📝

#6261 [ticket/16831] fix tabs missing delimiters and remove commented class
  phpBB/styles/prosilver/theme/base.css
  phpBB/styles/prosilver/theme/bidi.css
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/colours.css
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/content.css
  phpBB/styles/prosilver/theme/cp.css
  phpBB/styles/prosilver/theme/forms.css
  phpBB/styles/prosilver/theme/icons.css
  phpBB/styles/prosilver/theme/links.css
  phpBB/styles/prosilver/theme/print.css
  phpBB/styles/prosilver/theme/responsive.css
  phpBB/styles/prosilver/theme/stylesheet.css
  phpBB/styles/prosilver/theme/utilities.css
Labels: 3.3 (Proteus) 🌑

#6264 [ticket/16835] Add missing template file in ACP
  phpBB/adm/style/mentions_templates.html
Labels: 4.0 (Triton) 🔮

#6256 [ticket/16825] Adjust handling of session ID when requiring cookies
  phpBB/includes/acp/acp_main.php
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/phpbb/session.php
  phpBB/styles/prosilver/template/index_body.html
  phpBB/styles/prosilver/template/login_body.html
  phpBB/styles/prosilver/template/viewforum_body.html
  phpBB/ucp.php
  tests/functional/auth_test.php
  tests/functional/mcp_test.php
  tests/functional/report_post_captcha_test.php
  tests/functional/ucp_profile_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6267 [ticket/16836] Use absolute paths in local adapter
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/stream_interface.php
  tests/functional/acp_storage_test.php
Labels: 4.0 (Triton) 🔮

#6268 [ticket/16833][4.0.x] Improve subscribe to forum or topic icons
  phpBB/styles/prosilver/template/navbar_footer.html
  phpBB/styles/prosilver/template/viewtopic_topic_tools.html
  phpBB/styles/prosilver/theme/icons.css
Labels: Styles 🎨, 4.0 (Triton) 🔮, HTML📝

#6262 [ticket/16832] Fix UCP attachments plural rules
  phpBB/includes/ucp/ucp_attachments.php
Labels: 3.3 (Proteus) 🌑

#5760 Ticket/16138 Eliminate redundant parameters from board URLs
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions.php
  phpBB/includes/functions_display.php
  phpBB/includes/functions_mcp.php
  phpBB/includes/functions_posting.php
  phpBB/includes/mcp/mcp_forum.php
  phpBB/includes/mcp/mcp_front.php
  phpBB/includes/mcp/mcp_main.php
  phpBB/includes/mcp/mcp_post.php
  phpBB/includes/mcp/mcp_queue.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/includes/mcp/mcp_topic.php
  phpBB/includes/mcp/mcp_warn.php
  phpBB/includes/ucp/ucp_attachments.php
  phpBB/includes/ucp/ucp_main.php
  phpBB/phpbb/feed/post_base.php
  phpBB/phpbb/feed/topic_base.php
  phpBB/phpbb/log/log.php
  phpBB/phpbb/message/topic_form.php
  phpBB/phpbb/notification/type/post.php
  phpBB/phpbb/notification/type/post_in_queue.php
  phpBB/phpbb/notification/type/report_post.php
  phpBB/phpbb/notification/type/topic.php
  phpBB/phpbb/notification/type/topic_in_queue.php
  phpBB/posting.php
  phpBB/search.php
  phpBB/viewforum.php
  phpBB/viewtopic.php
  tests/functional/download_test.php
  tests/functional/feed_test.php
  tests/functional/fileupload_form_test.php
  tests/functional/plupload_test.php
  tests/functional/posting_test.php
  tests/functional/visibility_disapprove_test.php
  tests/functional/visibility_reapprove_test.php
  tests/functions/build_url_test.php
  tests/log/function_view_log_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 3.3 (Proteus) 🌑

#6260 [ticket/16829] forumtitle and lastsubject text decoration hover
  phpBB/styles/prosilver/theme/links.css
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6258 [ticket/15729] Avoid unnecessary email headers encoding in Base64
  phpBB/includes/functions_messenger.php
Labels: 3.3 (Proteus) 🌑

#6056 [ticket/16574] Remove flash BBcode
  phpBB/adm/style/acp_contact.html
  phpBB/adm/style/acp_posting_buttons.html
  phpBB/adm/style/acp_users_prefs.html
  phpBB/adm/style/acp_users_signature.html
  phpBB/develop/add_permissions.php
  phpBB/develop/adjust_bbcodes.php
  phpBB/develop/check_flash_bbcodes.php
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/includes/acp/acp_board.php
  phpBB/includes/acp/acp_contact.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/bbcode.php
  phpBB/includes/compatibility_globals.php
  phpBB/includes/constants.php
  phpBB/includes/functions_content.php
  phpBB/includes/functions_convert.php
  phpBB/includes/mcp/mcp_warn.php
  phpBB/includes/message_parser.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/includes/ucp/ucp_main.php
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/includes/ucp/ucp_prefs.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/install/convertors/functions_phpbb20.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/acp/permissions_phpbb.php
  phpBB/language/en/posting.php
  phpBB/language/en/ucp.php
  phpBB/phpbb/db/migration/data/v400/remove_flash.php
  phpBB/phpbb/permissions.php
  phpBB/phpbb/textformatter/data_access.php
  phpBB/phpbb/textformatter/renderer_interface.php
  phpBB/phpbb/textformatter/s9e/factory.php
  phpBB/phpbb/textformatter/s9e/parser.php
  phpBB/phpbb/textformatter/s9e/renderer.php
  phpBB/phpbb/textreparser/base.php
  phpBB/phpbb/user.php
  phpBB/posting.php
  phpBB/styles/prosilver/template/bbcode.html
  phpBB/styles/prosilver/template/posting_buttons.html
  phpBB/styles/prosilver/template/posting_editor.html
  phpBB/styles/prosilver/template/ucp_prefs_view.html
  tests/bbcode/parser_test.php
  tests/test_framework/phpbb_test_case_helpers.php
  tests/text_formatter/s9e/factory_test.php
  tests/text_formatter/s9e/fixtures/styles/bar/template/bbcode.html
  tests/text_formatter/s9e/fixtures/styles/barplus/template/bbcode.html
  tests/text_formatter/s9e/fixtures/styles/foo/template/bbcode.html
  tests/text_formatter/s9e/fixtures/styles/prosilver/template/bbcode.html
  tests/text_formatter/s9e/fixtures/styles/unsafe/template/bbcode.html
  tests/text_formatter/s9e/renderer_test.php
  tests/text_processing/generate_text_for_display_test.php
  tests/text_processing/generate_text_for_storage_test.php
  tests/text_processing/message_parser_test.php
  tests/text_reparser/plugins/test_row_based_plugin.php
Labels: 4.0 (Triton) 🔮

#6274 [ticket/16853] Remove depreciated 3.2 css classes
  phpBB/styles/prosilver/theme/buttons.css
Labels: 4.0 (Triton) 🔮

#5762 [ticket/16243] Update template paths
  phpBB/phpbb/template/twig/twig.php
  tests/template/twig_test.php
Labels: 4.0 (Triton) 🔮, Chameleon 🦄

#6281 [ticket/16865] Update IRC + discord links in composer and documentati…
  git-tools/hooks/commit-msg
  phpBB/composer.json
  phpBB/docs/README.html
  phpBB/phpbb/composer.json
  tests/RUNNING_TESTS.md
Labels: 3.3 (Proteus) 🌑
