Repository phpbb/phpbb, pull requests merged in 2021-12, with the labels that each got.

#6336 [ticket/16921] Increase PHP requirements in the DOCS
  .github/workflows/tests.yml
  phpBB/docs/INSTALL.html
Labels: 3.3 (Proteus) 🌑

#6312 [ticket/16895] Fix role removal for migrator permission tool
  phpBB/language/en/migrator.php
  phpBB/phpbb/db/migration/data/v33x/remove_orphaned_roles.php
  phpBB/phpbb/db/migration/tool/permission.php
  tests/dbal/migrator_tool_permission_role_test.php
Labels: 3.3 (Proteus) 🌑

#6338 [ticket/16927] Update plupload to latest version
  phpBB/assets/plupload/plupload.full.min.js
Labels: 3.3 (Proteus) 🌑

#6339 [ticket/16928] Update composer and dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6340 [ticket/16928] Update composer and dependencies to latest versions -- master version
  composer.phar
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6337 [ticket/16924] Do not double escape values inserted into config table
  phpBB/phpbb/config/db.php
  tests/config/db_test.php
  tests/config/db_text_test.php
Labels: 3.3 (Proteus) 🌑

#6346 [ticket/16939] Wait for postgresql service to start on windows CI runners
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6318 [ticket/16899] Add SVG and WEBP to ranks, smilies and topic icons
  phpBB/adm/style/acp_icons.html
  phpBB/adm/style/acp_ranks.html
  phpBB/includes/acp/acp_icons.php
  phpBB/includes/acp/acp_ranks.php
  phpBB/includes/functions_admin.php
  phpBB/styles/prosilver/theme/content.css
Labels: Styles 🎨, 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6347 [ticket/16940] Optimize phpBB Native Search [3.3.x]
  phpBB/includes/acp/acp_search.php
Labels: 3.3 (Proteus) 🌑

#6348 [ticket/16940] Optimize phpBB Native Search [master]
  phpBB/phpbb/search/backend/base.php
Labels: 4.0 (Triton) 🔮
