Repository phpbb/phpbb, pull requests merged in 2021-07, with the labels that each got.

#6237 [ticket/16808] Make sure we have a container before using it
  phpBB/includes/functions.php
Labels: 3.3 (Proteus) 🌑

#6233 [ticket/16799] Fix OAuth external account linking PHP fatal error
  phpBB/phpbb/auth/provider/base.php
  phpBB/phpbb/auth/provider/oauth/oauth.php
  phpBB/phpbb/auth/provider/provider_interface.php
  tests/functional/auth_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 3.3 (Proteus) 🌑

#6238 [ticket/16809] Reset display options at the end of preferences test
  tests/functional/ucp_preferences_test.php
Labels: 3.3 (Proteus) 🌑

#6241 [ticket/16812] login_body.html missing dt tag for autologin
  phpBB/styles/prosilver/template/login_body.html
Labels: 3.3 (Proteus) 🌑, HTML📝, Styles 🎨

#6244 [ticket/16817] Adjust selectors and expected strings on oauth test
  tests/functional/auth_test.php
Labels: 4.0 (Triton) 🔮

#6242 [ticket/16816] acp style html validation fixes
  phpBB/adm/style/acp_inactive.html
  phpBB/adm/style/acp_styles.html
  phpBB/adm/style/overall_footer.html
  phpBB/styles/prosilver/template/simple_footer.html
Labels: 3.3 (Proteus) 🌑, ACP Style, HTML📝

#5446 [Ticket/14771] Support playing audio attachments
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/constants.php
  phpBB/includes/functions_content.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/attachments.php
  phpBB/phpbb/db/migration/data/v400/add_audio_files_attachment_group.php
  phpBB/phpbb/mimetype/extension_guesser.php
  phpBB/phpbb/storage/controller/attachment.php
  phpBB/styles/prosilver/template/attachment.html
  phpBB/styles/prosilver/theme/content.css
Labels: 4.0 (Triton) 🔮

#6245 [ticket/16657] Properly decode usernames in member list live-search
  phpBB/memberlist.php
Labels: 3.3 (Proteus) 🌑

#6246 [ticket/16821] Upgrade Symfony to the latest 5.x
  phpBB/composer.json
  phpBB/composer.lock
  tests/functional/extension_controller_test.php
Labels: 4.0 (Triton) 🔮

#6247 [ticket/16810] Fix No end tag in Custom BBCodes
  phpBB/includes/functions_display.php
Labels: 3.3 (Proteus) 🌑

#6251 [ticket/16822] Replace patchwork/utf8 with symfony/polyfill
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/includes/utf/utf_tools.php
Labels: 4.0 (Triton) 🔮

#6250 [ticket/16822] Replace patchwork/utf8 with symfony/polyfill
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/includes/utf/utf_tools.php
Labels: 3.3 (Proteus) 🌑

#6249 [ticket/12075] Add acp/modules language file to extensions page
  phpBB/includes/acp/acp_extensions.php
Labels: 3.3 (Proteus) 🌑

#6254 [ticket/16804] Extend bbcode help line tooltip
  phpBB/adm/style/acp_bbcodes.html
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/phpbb/db/migration/data/v33x/extend_bbcode_tooltip.php
Labels: 3.3 (Proteus) 🌑

#6255 [ticket/16804] Reorder static keyword to fit with guidelines
  phpBB/phpbb/db/migration/data/v33x/extend_bbcode_tooltip.php
Labels: 4.0 (Triton) 🔮

#6248 [ticket/16207] Require cookies for sessions
  phpBB/adm/index.php
  phpBB/config/test/config.yml
  phpBB/includes/acp/acp_prune.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions.php
  phpBB/includes/functions_display.php
  phpBB/includes/functions_posting.php
  phpBB/includes/mcp/mcp_forum.php
  phpBB/includes/mcp/mcp_topic.php
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/index.php
  phpBB/memberlist.php
  phpBB/phpbb/controller/helper.php
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/log/log.php
  phpBB/phpbb/session.php
  phpBB/search.php
  phpBB/viewforum.php
  phpBB/viewtopic.php
  tests/functional/extension_controller_test.php
  tests/functional/mcp_test.php
  tests/functions/build_url_test.php
  tests/mock/container_builder.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6252 [ticket/16823] Make datetime class correctly handle edge cases
  phpBB/phpbb/datetime.php
  tests/datetime/from_format_test.php
Labels: 3.3 (Proteus) 🌑
