Repository phpbb/phpbb, pull requests merged in 2022-12, with the labels that each got.

#6225 [ticket/16790] Remove unused code
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/includes/acp/acp_forums.php
  phpBB/includes/acp/acp_icons.php
  phpBB/includes/acp/acp_logs.php
  phpBB/includes/acp/acp_main.php
  phpBB/includes/acp/acp_modules.php
  phpBB/includes/acp/acp_permissions.php
  phpBB/includes/acp/acp_profile.php
  phpBB/includes/acp/acp_prune.php
  phpBB/includes/acp/acp_storage.php
  phpBB/includes/mcp/mcp_main.php
  phpBB/includes/mcp/mcp_pm_reports.php
  phpBB/includes/mcp/mcp_post.php
  phpBB/includes/mcp/mcp_queue.php
  phpBB/includes/mcp/mcp_reports.php
  phpBB/includes/ucp/ucp_login_link.php
  phpBB/includes/ucp/ucp_main.php
  phpBB/includes/ucp/ucp_pm.php
  phpBB/includes/ucp/ucp_pm_compose.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/includes/ucp/ucp_register.php
  phpBB/phpbb/console/command/thumbnail/recreate.php
  tests/console/cache/purge_test.php
  tests/console/config/config_test.php
  tests/console/cron/cron_list_test.php
  tests/console/cron/run_test.php
  tests/console/thumbnail_test.php
  tests/console/update/check_test.php
  tests/console/user/activate_test.php
  tests/console/user/add_test.php
  tests/console/user/base.php
  tests/console/user/delete_test.php
  tests/console/user/reclean_test.php
Labels: 4.0 (Triton) 🔮

#6428 [ticket/16105] Use Google reCAPTCHA globally
  phpBB/adm/style/captcha_recaptcha_acp.html
  phpBB/phpbb/captcha/plugins/recaptcha.php
  phpBB/phpbb/captcha/plugins/recaptcha_v3.php
Labels: 3.3 (Proteus) 🌑

#6432 [ticket/17065] Add utf8_encode_ucr to $usernotes
  phpBB/includes/mcp/mcp_notes.php
Labels: 3.3 (Proteus) 🌑

#5439 [ticket/12683] Add a CLI command to generate the search index
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_console.yml
  phpBB/config/default/container/services_posting.yml
  phpBB/config/default/container/services_search.yml
  phpBB/includes/acp/acp_main.php
  phpBB/includes/acp/acp_search.php
  phpBB/includes/functions_admin.php
  phpBB/includes/functions_posting.php
  phpBB/includes/mcp/mcp_main.php
  phpBB/includes/mcp/mcp_post.php
  phpBB/includes/mcp/mcp_topic.php
  phpBB/language/en/acp/search.php
  phpBB/language/en/cli.php
  phpBB/language/en/common.php
  phpBB/phpbb/console/command/reparser/list_all.php
  phpBB/phpbb/console/command/searchindex/create.php
  phpBB/phpbb/console/command/searchindex/delete.php
  phpBB/phpbb/console/command/searchindex/list_all.php
  phpBB/phpbb/cron/task/core/tidy_search.php
  phpBB/phpbb/di/exception/di_exception.php
  phpBB/phpbb/di/exception/multiple_service_definitions_exception.php
  phpBB/phpbb/di/exception/service_not_found_exception.php
  phpBB/phpbb/di/service_collection.php
  phpBB/phpbb/install/module/install_data/task/create_search_index.php
  phpBB/phpbb/posting/post_helper.php
  phpBB/phpbb/search/backend/base.php
  phpBB/phpbb/search/backend/fulltext_mysql.php
  phpBB/phpbb/search/backend/fulltext_native.php
  phpBB/phpbb/search/backend/fulltext_postgres.php
  phpBB/phpbb/search/exception/action_in_progress_exception.php
  phpBB/phpbb/search/exception/no_action_in_progress_exception.php
  phpBB/phpbb/search/exception/no_search_backend_found_exception.php
  phpBB/phpbb/search/exception/search_exception.php
  phpBB/phpbb/search/search_backend_factory.php
  phpBB/phpbb/search/state_helper.php
  phpBB/search.php
  tests/console/searchindex/create_test.php
  tests/console/searchindex/delete_test.php
  tests/console/searchindex/list_all_test.php
  tests/console/searchindex/phpbb_console_searchindex_base.php
  tests/di/service_collection_test.php
  tests/mock/search_backend_mock.php
  tests/mock/search_backend_mock_not_available.php
  tests/search/mysql_test.php
  tests/search/native_test.php
  tests/search/postgres_test.php
Labels: 4.0 (Triton) 🔮

#6433 [ticket/17066] Update actions to resolve deprecation warnings
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6423 [ticket/13291] Close notifications dropdown during mark all read
  phpBB/styles/prosilver/template/ajax.js
Labels: Styles 🎨, JS ☕, 3.3 (Proteus) 🌑

#6437 [ticket/17069] Fix duplicate key in array
  phpBB/phpbb/mimetype/extension_guesser.php
Labels: 4.0 (Triton) 🔮

#5979 [ticket/15769] Crop avatar on upload
  package.json
  phpBB/adm/style/acp_avatar_options_upload.html
  phpBB/adm/style/acp_groups.html
  phpBB/adm/style/acp_users_avatar.html
  phpBB/adm/style/admin.css
  phpBB/assets/css/cropper.css
  phpBB/assets/css/cropper.min.css
  phpBB/assets/javascript/cropper.js
  phpBB/assets/javascript/cropper.min.js
  phpBB/assets/javascript/hermite.js
  phpBB/assets/javascript/jquery-cropper.js
  phpBB/assets/javascript/jquery-cropper.min.js
  phpBB/assets/javascript/phpbb-avatars.js
  phpBB/includes/ucp/ucp_profile.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/ucp.php
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/phpbb/db/migration/data/v400/increase_avatar_size.php
  phpBB/styles/prosilver/template/ucp_avatar_options.html
  phpBB/styles/prosilver/template/ucp_avatar_options_upload.html
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/cp.css
  tests/functional/avatar_acp_groups_test.php
Labels: 4.0 (Triton) 🔮, JS ☕, Chameleon 🦄, HTML📝, CSS 📐
