Repository phpbb/phpbb, pull requests merged in 2022-04, with the labels that each got.

#6374 [ticket/16976] Fix search results count
  phpBB/phpbb/search/fulltext_mysql.php
  phpBB/phpbb/search/fulltext_native.php
  phpBB/phpbb/search/fulltext_postgres.php
  tests/functional/search/base.php
Labels: 3.3 (Proteus) 🌑

#6375 [ticket/16976] Fix search results count - master
  phpBB/phpbb/search/backend/fulltext_mysql.php
  phpBB/phpbb/search/backend/fulltext_native.php
  phpBB/phpbb/search/backend/fulltext_postgres.php
  tests/functional/search/base.php
Labels: 4.0 (Triton) 🔮

#6381 [ticket/16977] Fix cron-job img tag layout and accessibility - Master version
  phpBB/config/default/container/services_cron.yml
  phpBB/phpbb/controller/helper.php
  phpBB/phpbb/cron/manager.php
  phpBB/phpbb/cron/task/wrapper.php
  phpBB/styles/all/template/cron.html
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/viewforum.php
  tests/console/cron/cron_list_test.php
  tests/console/cron/run_test.php
  tests/controller/common_helper_route.php
  tests/cron/manager_test.php
  tests/pagination/pagination_test.php
Labels: 4.0 (Triton) 🔮

#6371 [ticket/19969] Hide flash status when post settings disallow [FLASH] …
  phpBB/styles/prosilver/template/posting_editor.html
Labels: 3.3 (Proteus) 🌑

#6386 [ticket/15947] Fix X out of 0 messages stored bug
  phpBB/language/en/common.php
Labels: 3.3 (Proteus) 🌑

#6385 [ticket/16871] Do not allow negative forum and topic IDs in page_header
  README.md
  phpBB/includes/functions.php
Labels: 3.3 (Proteus) 🌑

#6389 [ticket/16405] Update npm dependencies
  .stylelintrc
  package-lock.json
  package.json
  phpBB/adm/style/admin.css
  phpBB/assets/javascript/mentions.js
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/print.css
Labels: 4.0 (Triton) 🔮

#6387 [ticket/16987] Update composer and dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6388 [ticket/16987] Update composer and dependencies to latest versions - master version
  composer.phar
  phpBB/composer.lock
  phpBB/phpbb/composer/installer.php
  phpBB/phpbb/composer/io/html_output_formatter.php
Labels: 4.0 (Triton) 🔮

#6395 [ticket/16991] Add events for bookmarks and subscribed topics in UCP
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_main_bookmarks.html
  phpBB/styles/prosilver/template/ucp_main_subscribed.html
Labels: 3.3 (Proteus) 🌑

#6358 [ticket/16959] Remove redundant URL parameters from notification mails
  phpBB/phpbb/notification/type/forum.php
Labels: 3.3 (Proteus) 🌑

#6382 [ticket/16967] Deprecate PHP in templates
  phpBB/docs/coding-guidelines.html
Labels: 3.3 (Proteus) 🌑

#6369 [ticket/16967] Remove support for INCLUDEPHP and PHP/ENDPHP in templates
  phpBB/docs/coding-guidelines.html
  phpBB/includes/acp/acp_board.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/phpbb/db/migration/data/v400/remove_template_php.php
  phpBB/phpbb/template/twig/extension.php
  phpBB/phpbb/template/twig/lexer.php
  phpBB/phpbb/template/twig/node/includephp.php
  phpBB/phpbb/template/twig/node/php.php
  phpBB/phpbb/template/twig/tokenparser/includephp.php
  phpBB/phpbb/template/twig/tokenparser/php.php
  tests/template/extension_test.php
  tests/template/includephp_test.php
  tests/template/subdir/includephp_from_subdir_test.php
  tests/template/template_test.php
  tests/template/template_test_case.php
  tests/template/templates/includephp_relative.html
  tests/template/templates/includephp_variables.html
  tests/template/templates/php.html
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6377 [ticket/16981] Fix HTML-encoded emojis in email subject line
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/includes/acp/acp_board.php
  phpBB/includes/acp/acp_email.php
  phpBB/includes/acp/acp_help_phpbb.php
  phpBB/includes/acp/acp_inactive.php
  phpBB/includes/acp/acp_logs.php
  phpBB/includes/acp/acp_ranks.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions_compatibility.php
  phpBB/includes/functions_content.php
  phpBB/includes/functions_download.php
  phpBB/includes/functions_messenger.php
  phpBB/includes/functions_user.php
  phpBB/includes/mcp/mcp_logs.php
  phpBB/includes/mcp/mcp_notes.php
  phpBB/includes/message_parser.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/includes/ucp/ucp_activate.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/includes/ucp/ucp_register.php
  phpBB/includes/ucp/ucp_resend.php
  phpBB/memberlist.php
  phpBB/phpbb/auth/provider/apache.php
  phpBB/phpbb/auth/provider/ldap.php
  phpBB/phpbb/console/command/user/activate.php
  phpBB/phpbb/console/command/user/add.php
  phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
  phpBB/phpbb/install/helper/iohandler/iohandler_base.php
  phpBB/phpbb/install/module/install_finish/task/notify_user.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_server_data.php
  phpBB/phpbb/install/module/obtain_data/task/obtain_update_ftp_data.php
  phpBB/phpbb/message/message.php
  phpBB/phpbb/message/topic_form.php
  phpBB/phpbb/notification/type/admin_activate_user.php
  phpBB/phpbb/notification/type/disapprove_post.php
  phpBB/phpbb/notification/type/disapprove_topic.php
  phpBB/phpbb/notification/type/forum.php
  phpBB/phpbb/notification/type/group_request.php
  phpBB/phpbb/notification/type/pm.php
  phpBB/phpbb/notification/type/post.php
  phpBB/phpbb/notification/type/quote.php
  phpBB/phpbb/notification/type/report_pm.php
  phpBB/phpbb/notification/type/report_pm_closed.php
  phpBB/phpbb/notification/type/report_post.php
  phpBB/phpbb/notification/type/report_post_closed.php
  phpBB/phpbb/notification/type/topic.php
  phpBB/phpbb/plupload/plupload.php
  phpBB/phpbb/search/fulltext_mysql.php
  phpBB/phpbb/search/fulltext_native.php
  phpBB/phpbb/search/fulltext_postgres.php
  phpBB/phpbb/session.php
  phpBB/phpbb/textformatter/data_access.php
  phpBB/phpbb/ucp/controller/reset_password.php
  phpBB/search.php
  tests/email/email_parsing_test.php
Labels: 3.3 (Proteus) 🌑

#6391 [ticket/16800] Fix 'No Posts' bug when no date format supplied
  phpBB/includes/ucp/ucp_main.php
  phpBB/styles/prosilver/template/forumlist_body.html
  phpBB/styles/prosilver/template/ucp_main_subscribed.html
Labels: 3.3 (Proteus) 🌑
