Repository phpbb/phpbb, pull requests merged in 2023-12, with the labels that each got.

#6569 [ticket/17236] Update composer dependencies to improve PHP 8.3 compatibility
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6572 [ticket/17236] Update composer dependencies to impove PHP 8.3 compatibility -- master version
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6570 [ticket/17237] Use single quotes for QUICKMOD_ACTION_NOT_ALLOWED var
  phpBB/language/en/mcp.php
Labels: 3.3 (Proteus) 🌑

#6575 [ticket/17277] Add template events to UCP
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_footer.html
  phpBB/styles/prosilver/template/ucp_header.html
  phpBB/styles/prosilver/template/ucp_notifications.html
Labels: Event 🔌

#6576 [ticket/17277] Add template events to UCP - master version
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_footer.html
  phpBB/styles/prosilver/template/ucp_header.html
  phpBB/styles/prosilver/template/ucp_notifications.html
Labels: Event 🔌

#6578 [ticket/17280] Fall back to branch when no valid title found
  git-tools/hooks/prepare-commit-msg
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑
