Repository phpbb/phpbb, pull requests merged in 2023-11, with the labels that each got.

#6560 [ticket/17208] Skip profile field data update if youtube cpf doesn't exist
  phpBB/phpbb/db/migration/data/v33x/profilefield_youtube_update.php
  phpBB/phpbb/db/migration/data/v33x/profilefields_update.php
Labels: 3.3 (Proteus) 🌑

#6559 [ticket/17207] Lazily call get_web_root_path() in twig environment
  phpBB/phpbb/template/twig/environment.php
Labels: Blocker :warning:, 3.3 (Proteus) 🌑

#6561 [ticket/17209] Improve mentions migration and add fallback for permission role_exists
  phpBB/phpbb/db/migration/data/v330/add_mention_settings.php
  phpBB/phpbb/db/migration/data/v400/add_mention_settings.php
  phpBB/phpbb/db/migration/data/v400/add_storage_permission.php
  phpBB/phpbb/db/migration/tool/permission.php
Labels: 4.0 (Triton) 🔮

#6490 [ticket/16470] Update user last visit time on session begin
  phpBB/phpbb/session.php
Labels: 3.3 (Proteus) 🌑

#6557 [ticket/17204] Update composer dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6558 [ticket/17204] Update composer dependencies to latest versions -- master version
  composer.phar
  package-lock.json
  package.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6562 [ticket/14047] Check for stream close handshake before closing stream
  phpBB/includes/functions_jabber.php
Labels: 3.3 (Proteus) 🌑

#6518 [ticket/9687] Refactor banning
  phpBB/adm/style/acp_ban.html
  phpBB/adm/style/admin.css
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_ban.yml
  phpBB/config/default/container/tables.yml
  phpBB/includes/acp/acp_ban.php
  phpBB/includes/acp/acp_email.php
  phpBB/includes/constants.php
  phpBB/includes/functions_admin.php
  phpBB/includes/functions_display.php
  phpBB/includes/functions_user.php
  phpBB/includes/mcp/mcp_ban.php
  phpBB/index.php
  phpBB/install/convert/convertor.php
  phpBB/install/convertors/convert_phpbb20.php
  phpBB/language/en/acp/ban.php
  phpBB/language/en/acp/common.php
  phpBB/language/en/common.php
  phpBB/phpbb/ban/exception/invalid_length_exception.php
  phpBB/phpbb/ban/exception/no_valid_emails_exception.php
  phpBB/phpbb/ban/exception/no_valid_ips_exception.php
  phpBB/phpbb/ban/exception/no_valid_users_exception.php
  phpBB/phpbb/ban/exception/type_not_found_exception.php
  phpBB/phpbb/ban/manager.php
  phpBB/phpbb/ban/type/base.php
  phpBB/phpbb/ban/type/email.php
  phpBB/phpbb/ban/type/ip.php
  phpBB/phpbb/ban/type/type_interface.php
  phpBB/phpbb/ban/type/user.php
  phpBB/phpbb/db/migration/data/v400/ban_table_p1.php
  phpBB/phpbb/db/migration/data/v400/ban_table_p2.php
  phpBB/phpbb/session.php
  phpBB/phpbb/user.php
  phpBB/styles/prosilver/template/mcp_ban.html
  tests/ban/ban_manager_test.php
  tests/ban/fixtures/sessions_banlist.xml
  tests/bootstrap.php
  tests/dbal/boolean_processor_test.php
  tests/dbal/cross_join_test.php
  tests/dbal/fixtures/boolean_processor.xml
  tests/dbal/fixtures/massmail_crossjoin.xml
  tests/functions/fixtures/banned_users.xml
  tests/functions/fixtures/validate_email.xml
  tests/functions/phpbb_get_banned_user_ids.php
  tests/functions/validate_user_email_test.php
  tests/functions_user/delete_user_test.php
  tests/functions_user/fixtures/delete_user.xml
  tests/session/check_ban_test.php
  tests/session/fixtures/sessions_banlist.xml
  tests/session/fixtures/sessions_empty.xml
  tests/session/testable_factory.php
  tests/test_framework/phpbb_session_test_case.php
Labels: 4.0 (Triton) 🔮
