Repository phpbb/phpbb, pull requests merged in 2023-06, with the labels that each got.

#6486 [ticket/17139] Fix PHP fatal error for file transfer tool of updater
  phpBB/includes/functions_transfer.php
Labels: 3.3 (Proteus) 🌑

#6484 [ticket/17107] Fix viewonline page locations for posting modes - 3.3.x
  phpBB/config/default/container/services_content.yml
  phpBB/phpbb/viewonline_helper.php
  phpBB/viewonline.php
  tests/functional/viewonline_test.php
  tests/viewonline/helper_test.php
Labels: 3.3 (Proteus) 🌑

#6485 [ticket/17107] Fix viewonline page locations for posting modes - master
  phpBB/config/default/container/services_content.yml
  phpBB/phpbb/viewonline_helper.php
  phpBB/viewonline.php
  tests/functional/viewonline_test.php
  tests/viewonline/helper_test.php
Labels: 4.0 (Triton) 🔮

#6495 [ticket/17149] Update authors list and simplify pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  phpBB/docs/CREDITS.txt
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6489 [ticket/17142] Fix DBMS+cache related PHP warnings while installing - master
  phpBB/phpbb/cache/driver/base.php
  phpBB/phpbb/cache/driver/driver_interface.php
  phpBB/phpbb/db/driver/driver.php
  phpBB/phpbb/db/driver/driver_interface.php
  phpBB/phpbb/db/driver/factory.php
  phpBB/phpbb/db/driver/mssql_odbc.php
  phpBB/phpbb/db/driver/mssqlnative.php
  phpBB/phpbb/db/driver/mysqli.php
  phpBB/phpbb/db/driver/oracle.php
  phpBB/phpbb/db/driver/postgres.php
  phpBB/phpbb/db/driver/sqlite3.php
  tests/mock/cache.php
Labels: 4.0 (Triton) 🔮

#6491 Change static to private variable due to php81 inheritance
  phpBB/phpbb/db/migration/profilefield_base_migration.php
Labels: 3.3 (Proteus) 🌑

#6492 Fix 'undefined array key' php8 warning
  phpBB/phpbb/notification/method/jabber.php
Labels: 3.3 (Proteus) 🌑

#6493 [ticket/17148] Fix sql_table_exists() error for PostgreSQL 9.3 and earlier - 3.3.x
  .github/workflows/tests.yml
  phpBB/phpbb/db/tools/postgres.php
Labels: 3.3 (Proteus) 🌑

#6494 [ticket/17148] Fix sql_table_exists() error for PostgreSQL 9.3 and earlier - master
  phpBB/docs/INSTALL.html
Labels: 4.0 (Triton) 🔮

#6499 [ticket/17140] Add missing parameter phpbb_root_path
  phpBB/phpbb/db/migration/data/v30x/local_url_bbcode.php
Labels: 3.3 (Proteus) 🌑

#6498 [ticket/17141] Improve stability of path_helper and increase test coverage
  phpBB/phpbb/path_helper.php
  tests/path_helper/path_helper_test.php
Labels: 3.3 (Proteus) 🌑
