Repository phpbb/phpbb, pull requests merged in 2023-01, with the labels that each got.

#6443 [ticket/17074] Don't allow to create two roles with the same name
  phpBB/includes/acp/acp_permission_roles.php
Labels: 3.3 (Proteus) 🌑

#6444 [ticket/17075] Add template events to ACP footers after $SCRIPT
  phpBB/adm/style/overall_footer.html
  phpBB/adm/style/simple_footer.html
  phpBB/docs/events.md
Labels: 3.3 (Proteus) 🌑

#6445 [ticket/17081] Fix accept attribute in upload input
  phpBB/includes/functions_posting.php
Labels: 3.3 (Proteus) 🌑

#6448 [ticket/16938] Replace invalid nowrap with white-space css
  phpBB/adm/style/acp_users_warnings.html
Labels: Styles 🎨, 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6449 [ticket/17039] Use correct template var for group colour in ucp groups manage
  phpBB/styles/prosilver/template/ucp_groups_manage.html
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6450 [ticket/17071] Switch to jsdelivr CDN for twemoji emojis
  phpBB/phpbb/textformatter/s9e/factory.php
  tests/text_formatter/s9e/default_formatting_test.php
  tests/text_processing/tickets_data/PHPBB3-15348.html
  tests/text_processing/tickets_data/PHPBB3-16074.html
Labels: Blocker :warning:, 3.3 (Proteus) 🌑

#6436 [ticket/17068] ALLOW_CDN_EXPLAIN: Refines and expands the description
  phpBB/language/en/acp/board.php
Labels: 3.3 (Proteus) 🌑

#6452 [ticket/17091] Limit doctrine/instantiator to 1.x versions
  .github/setup-phpbb.sh
  .github/workflows/tests.yml
  phpBB/cron.php
  phpBB/phpbb/session.php
Labels: 3.3 (Proteus) 🌑

#6453 [ticket/17092] Check for Spamhaus error codes
  phpBB/language/en/acp/common.php
  phpBB/phpbb/session.php
Labels: 3.3 (Proteus) 🌑

#6455 [ticket/17092] Check for Spamhaus error codes
  phpBB/language/en/acp/common.php
  phpBB/phpbb/session.php
Labels: 4.0 (Triton) 🔮

#6447 [ticket/17085] Fix invalid icon names
  phpBB/styles/prosilver/template/mcp_post.html
  phpBB/styles/prosilver/template/ucp_main_front.html
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6451 [ticket/17086] Add GitHub Codespaces support to phpBB (3.3.x branch)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/resources/phpbb-config.yml
  .devcontainer/resources/setup.sh
  .devcontainer/resources/xdebug.ini
  .vscode/launch.json
  .vscode/settings.json
  README.md
  phpBB/docs/codespaces.md
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6441 [ticket/16913] Add Search Index Progress Bar with Stats [master]
  phpBB/adm/style/acp_search_index.html
  phpBB/adm/style/acp_search_index_inprogress.html
  phpBB/adm/style/acp_search_index_progress.html
  phpBB/includes/acp/acp_search.php
  phpBB/language/en/acp/search.php
  tests/functional/search/base.php
Labels: 4.0 (Triton) 🔮

#6456 [ticket/17025] Move post destination topic field should not be populated with a zero
  phpBB/includes/mcp/mcp_topic.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6457 [ticket/16796] Fixing misalignment of header items in category on index
  phpBB/styles/prosilver/theme/content.css
Labels: 3.3 (Proteus) 🌑

#6458 [ticket/16796] Fixing misalignment of header items in category on index -- master version
  phpBB/styles/prosilver/theme/content.css
Labels: 4.0 (Triton) 🔮
