Repository phpbb/phpbb, pull requests merged in 2023-07, with the labels that each got.

#6497 [ticket/17150] Set max width for forum-image img
  phpBB/styles/prosilver/theme/content.css
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6503 [ticket/17152] Add template event to viewtopic_body.html
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/viewtopic_body.html
Labels: Event 🔌

#6508 [ticket/17154] Update composer and dependencies
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6509 [ticket/17154] Update composer and dependencies -- master version
  composer.phar
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6511 [ticket/17053] Add simple check for writable cache directory
  phpBB/common.php
  phpBB/phpbb/di/container_builder.php
Labels: 3.3 (Proteus) 🌑

#6512 [ticket/8777] Discourage deleting user from group with only one group
  phpBB/adm/style/acp_users.html
  phpBB/includes/acp/acp_users.php
Labels: 3.3 (Proteus) 🌑

#6500 [ticket/15687] Add attachment filename to attachment URL
  phpBB/config/default/routing/storage.yml
  phpBB/download/file.php
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions_content.php
  phpBB/includes/functions_posting.php
  phpBB/includes/message_parser.php
  phpBB/includes/ucp/ucp_attachments.php
  phpBB/phpbb/storage/controller/attachment.php
  tests/functional/acp_attachments_test.php
Labels: 4.0 (Triton) 🔮

#6513 [ticket/17160] Add missing mark column header
  phpBB/styles/prosilver/template/mcp_front.html
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6514 [ticket/11765] Support IPv4 embedded IPv6 addresses in short_ipv6()
  phpBB/includes/functions.php
  tests/functions/short_ipv6__test.php
Labels: 3.3 (Proteus) 🌑

#6515 [ticket/11184] Add note about effect of admin permissions for founders
  phpBB/language/en/acp/permissions.php
Labels: 3.3 (Proteus) 🌑, Language/Text 🌐

#6496 [ticket/17151] Adjust form macros to adhere to coding guidelines
  phpBB/phpbb/template/twig/extension/forms.php
  phpBB/styles/all/template/macros/forms/input.twig
  phpBB/styles/all/template/macros/forms/select.twig
  phpBB/styles/all/template/macros/forms/textarea.twig
Labels: 4.0 (Triton) 🔮

#6519 [ticket/17171] Remove unsupported CSS rules for placeholder
  phpBB/styles/prosilver/theme/responsive.css
Labels: 3.3 (Proteus) 🌑

#6520 [ticket/17171] Remove unsupported CSS rules for placeholder -- master version
  phpBB/styles/prosilver/theme/responsive.css
Labels: 4.0 (Triton) 🔮
