Repository phpbb/phpbb, pull requests merged in 2023-04, with the labels that each got.

#6475 [ticket/17125] use box-sizing for message box text areas
  phpBB/styles/prosilver/theme/forms.css
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6473 [ticket/17115] Fix PHP warning for space+hyphen ending search query - master
  phpBB/phpbb/search/backend/fulltext_native.php
  tests/functional/search/base.php
Labels: 4.0 (Triton) 🔮

#6474 Fix filename in instructions about running all tests
  tests/RUNNING_TESTS.md
Labels: 3.3 (Proteus) 🌑

#6476 [ticket/17108] Update composer dependencies and expect trigger error code
  phpBB/adm/style/acp_search_index.html
  phpBB/composer.lock
  phpBB/includes/acp/acp_search.php
  phpBB/phpbb/template/twig/extension.php
  tests/functional/search/base.php
  tests/test_framework/phpbb_test_case_helpers.php
Labels: 4.0 (Triton) 🔮

#6477 [ticket/17127] Do not purge guest sessions when resetting password
  phpBB/includes/ucp/ucp_profile.php
  phpBB/phpbb/ucp/controller/reset_password.php
Labels: 3.3 (Proteus) 🌑

#6392 [ticket/8071] Add sql_last_inserted_id alias for sql_nextid
  phpBB/phpbb/db/driver/driver.php
  phpBB/phpbb/db/driver/driver_interface.php
  phpBB/phpbb/db/driver/factory.php
  phpBB/phpbb/db/driver/mssql_odbc.php
  phpBB/phpbb/db/driver/mssqlnative.php
  phpBB/phpbb/db/driver/mysqli.php
  phpBB/phpbb/db/driver/oracle.php
  phpBB/phpbb/db/driver/postgres.php
  phpBB/phpbb/db/driver/sqlite3.php
Labels: 3.3 (Proteus) 🌑
