Repository phpbb/phpbb, pull requests merged in 2023-10, with the labels that each got.

#6526 [ticket/17029] Update post count when changing post visibility
  phpBB/includes/functions_posting.php
  phpBB/phpbb/content_visibility.php
  tests/content_visibility/delete_post_test.php
  tests/content_visibility/fixtures/delete_post.xml
  tests/content_visibility/set_post_visibility_test.php
Labels: 3.3 (Proteus) 🌑

#6552 [ticket/12904] Do not display info about required fields without any
  phpBB/phpbb/profilefields/manager.php
  phpBB/styles/prosilver/template/ucp_register.html
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6546 [Ticket/17189] Improve installer file permission checks
  phpBB/install/startup.php
  phpBB/phpbb/cache/driver/file.php
  phpBB/phpbb/filesystem/filesystem.php
  phpBB/phpbb/install/module/requirements/task/check_filesystem.php
Labels: 3.3 (Proteus) 🌑

#6521 [ticket/13399] Add separate plural rules for characters count
  phpBB/includes/acp/acp_users.php
  phpBB/includes/ucp/ucp_profile.php
  phpBB/includes/ucp/ucp_register.php
  phpBB/language/en/common.php
Labels: 3.3 (Proteus) 🌑

#6531 [ticket/17188] Allow request variable to check multiline unicode
  phpBB/phpbb/request/type_cast_helper.php
  tests/request/type_cast_helper_test.php
Labels: 3.3 (Proteus) 🌑

#6527 [ticket/16877] Use replacement library for oauth
  .github/workflows/tests.yml
  phpBB/common.php
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/docs/INSTALL.html
  phpBB/docs/README.html
  phpBB/includes/acp/acp_main.php
  phpBB/includes/startup.php
  phpBB/install/app.php
  phpBB/language/en/install.php
  phpBB/phpbb/install/module/requirements/task/check_server_environment.php
Labels: 3.3 (Proteus) 🌑

#6540 [ticket/17184] Remove subfolders option in local storage
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/storage.php
  phpBB/phpbb/db/migration/data/v400/storage_adapter_local_subfolders_remove.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/provider/local.php
  tests/storage/adapter/local_subfolders_test.php
  tests/storage/adapter/local_test.php
Labels: 4.0 (Triton) 🔮

#6543 [ticket/17187] Repair mcp link to first unread post
  phpBB/includes/mcp/mcp_forum.php
  phpBB/includes/mcp/mcp_topic.php
  phpBB/styles/prosilver/template/mcp_topic.html
Labels: 3.3 (Proteus) 🌑

#6556 [ticket/17200] Fix color parse error in viewonline legend
  phpBB/viewonline.php
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6553 [ticket/17201] Do not run dirname() on dir path during install redirect
  phpBB/common.php
  phpBB/includes/functions.php
  tests/functions/phpbb_get_install_redirect_test.php
Labels: 3.3 (Proteus) 🌑

#6534 [ticket/17191] New config values to language/en/composer.json
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/language/en/captcha_recaptcha.php
  phpBB/language/en/common.php
  phpBB/language/en/composer.json
  phpBB/phpbb/feed/controller/feed.php
  phpBB/phpbb/language/language.php
  phpBB/phpbb/language/language_file_helper.php
  phpBB/phpbb/language/language_file_loader.php
Labels: 4.0 (Triton) 🔮

#6554 [ticket/17202] Include bidi.css to print only in RTL languages
  phpBB/styles/prosilver/template/viewtopic_print.html
Labels: 3.3 (Proteus) 🌑

#6555 [ticket/17203] Add CSS ol for group desc
  phpBB/styles/prosilver/theme/content.css
Labels: Styles 🎨, 3.3 (Proteus) 🌑
