Repository phpbb/phpbb, pull requests merged in 2024-12, with the labels that each got.

#6749 [ticket/17433] Clarify wording for use system cron ACP setting
  phpBB/includes/acp/acp_board.php
  phpBB/language/en/acp/board.php
Labels: 3.3 (Proteus) 🌑

#6759 [ticket/17449] Better handling of emoji and mb chars in PWA manifest
  phpBB/adm/style/admin.js
  phpBB/phpbb/manifest.php
  phpBB/styles/prosilver/template/overall_header.html
Labels: 4.0 (Triton) 🔮

#6756 [ticket/17446] Add acp_account_activation_edit_add event
  phpBB/includes/acp/acp_board.php
Labels: Event 🔌, 3.3 (Proteus) 🌑

#6757 [ticket/17446] Master: Add acp_account_activation_edit_add event
  phpBB/includes/acp/acp_board.php
Labels: Event 🔌, 4.0 (Triton) 🔮

#6754 [ticket/17443] Fix various Guzzle client issues for version checks
  phpBB/phpbb/file_downloader.php
  phpBB/phpbb/version_helper.php
Labels: 3.3 (Proteus) 🌑

#6764 [ticket/17457] Protect manifest request by CORS to prevent guest sessions
  phpBB/styles/prosilver/template/overall_header.html
Labels: 4.0 (Triton) 🔮

#6765 [ticket/17457] Cache manifest file
  phpBB/config/default/container/services.yml
  phpBB/phpbb/manifest.php
  tests/functional/manifest_test.php
Labels: 4.0 (Triton) 🔮

#6762 [ticket/17454] Fix displaying emojis in sitename within webpush header
  phpBB/phpbb/ucp/controller/webpush.php
Labels: 4.0 (Triton) 🔮

#6761 [ticket/17450] Remove obsolete requirement for JSON extension
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6746 [ticket/17429] Added trigger for event "group_add_user_before"
  phpBB/includes/functions_user.php
Labels: Event 🔌, 3.3 (Proteus) 🌑
