Repository phpbb/phpbb, pull requests merged in 2024-09, with the labels that each got.

#6709 [ticket/17386] Fix resulting permission for user-based tracing
  phpBB/phpbb/auth/auth.php
  tests/functional/acp_permissions_test.php
Labels: 3.3 (Proteus) 🌑

#6713 [ticket/17386] Unify user based permissions test for 3.3.x and master branches
  tests/functional/acp_permissions_test.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6712 [ticket/17387] Fix PHP warnings in search results
  phpBB/includes/functions_content.php
  tests/functions_content/get_context_test.php
Labels: 3.3 (Proteus) 🌑

#6694 [ticket/17373] Remove extra separator and change all separators to solid lines
  phpBB/styles/prosilver/template/navbar_header.html
  phpBB/styles/prosilver/theme/common.css
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6716 [ticket/17394] Check mergeability of 3.3.x PRs
  .github/workflows/tests.yml
Labels: WIP :construction:, 3.3 (Proteus) 🌑

#6717 [ticket/17396] Add workflow for merging 3.3.x into master
  .github/workflows/check_merge_to_master.yml
  .github/workflows/merge_3.3.x_to_master.yml
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6718 [ticket/17396] Only try pushing if merge was successful
  .github/workflows/merge_3.3.x_to_master.yml
Labels: 3.3 (Proteus) 🌑

#6720 [ticket/17396] Fetch full history and branch 3.3.x if merging to master
  .github/workflows/merge_3.3.x_to_master.yml
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6714 [ticket/17390] Fix unset template variable for topic approval in mcp
  phpBB/includes/mcp/mcp_queue.php
Labels: 3.3 (Proteus) 🌑

#6723 [ticket/17394] Merge local 3.3.x and not remote into master
  .github/workflows/check_merge_to_master.yml
Labels: 3.3 (Proteus) 🌑

#6726 [ticket/17405] Fix getting UTC date/time information logic
  phpBB/includes/functions.php
Labels: 3.3 (Proteus) 🌑

#6727 [ticket/17396] Use GitHub App to merge to master
  .github/workflows/merge_3.3.x_to_master.yml
Labels: 3.3 (Proteus) 🌑

#6725 [ticket/17404] Update workflow test badges
  README.md
Labels: 3.3 (Proteus) 🌑

#6721 [ticket/17400] Use fixed version for mssql 2017 tests
  .github/workflows/tests.yml
Labels: WIP :construction:, 4.0 (Triton) 🔮

#6724 [ticket/17403] Update composer and node dependencies
  package-lock.json
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6705 [ticket/17383] Fix HELO/EHLO error in email messenger on PHP8
  phpBB/includes/functions_messenger.php
Labels: 3.3 (Proteus) 🌑

#6715 [ticket/17385] Backport file_downloader with guzzle for versioncheck with redirect support
  phpBB/phpbb/file_downloader.php
  tests/version/fixture/30x.txt
  tests/version/version_helper_remote_test.php
Labels: 3.3 (Proteus) 🌑

#6702 [ticket/16777] Remove remainders of max image size
  phpBB/includes/acp/acp_board.php
  phpBB/includes/message_parser.php
  phpBB/includes/questionnaire/questionnaire.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/phpbb/db/migration/data/v400/remove_max_img_size.php
  phpBB/phpbb/textformatter/parser_interface.php
  phpBB/phpbb/textformatter/s9e/factory.php
  tests/functional/manifest_test.php
  tests/text_processing/message_parser_test.php
Labels: 4.0 (Triton) 🔮

#6704 [ticket/17382] Update the find a member FAQ text to fix grammar
  phpBB/language/en/help/faq.php
Labels: 3.3 (Proteus) 🌑
