Repository phpbb/phpbb, pull requests merged in 2024-03, with the labels that each got.

#6587 [ticket/17291] Use icon function in ACP templates
  phpBB/adm/images/alert_close.png
  phpBB/adm/images/arrow_down.gif
  phpBB/adm/images/arrow_left.gif
  phpBB/adm/images/arrow_right.gif
  phpBB/adm/images/arrow_up.gif
  phpBB/adm/images/bg_button.gif
  phpBB/adm/images/bg_hash1.gif
  phpBB/adm/images/bg_hash2.gif
  phpBB/adm/images/bg_hash3.gif
  phpBB/adm/images/bg_hash4.gif
  phpBB/adm/images/bg_header.gif
  phpBB/adm/images/bg_header.jpg
  phpBB/adm/images/bg_tabs_alt1.gif
  phpBB/adm/images/bg_tabs_alt2.gif
  phpBB/adm/images/cellpic3.gif
  phpBB/adm/images/file_conflict.gif
  phpBB/adm/images/file_modified.gif
  phpBB/adm/images/file_new.gif
  phpBB/adm/images/file_new_conflict.gif
  phpBB/adm/images/file_not_modified.gif
  phpBB/adm/images/file_up_to_date.gif
  phpBB/adm/images/gradient2b.gif
  phpBB/adm/images/icon_delete.gif
  phpBB/adm/images/icon_delete_disabled.gif
  phpBB/adm/images/icon_down.gif
  phpBB/adm/images/icon_down_disabled.gif
  phpBB/adm/images/icon_edit.gif
  phpBB/adm/images/icon_edit_disabled.gif
  phpBB/adm/images/icon_folder.gif
  phpBB/adm/images/icon_folder_link.gif
  phpBB/adm/images/icon_folder_lock.gif
  phpBB/adm/images/icon_subfolder.gif
  phpBB/adm/images/icon_sync.gif
  phpBB/adm/images/icon_sync_disabled.gif
  phpBB/adm/images/icon_trace.gif
  phpBB/adm/images/icon_up.gif
  phpBB/adm/images/icon_up_disabled.gif
  phpBB/adm/images/innerbox_bg.gif
  phpBB/adm/images/loading.gif
  phpBB/adm/images/phpbb_logo.png
  phpBB/adm/index.php
  phpBB/adm/style/acp_avatar_options_upload.html
  phpBB/adm/style/acp_ext_list.html
  phpBB/adm/style/acp_forums.html
  phpBB/adm/style/acp_help_phpbb.html
  phpBB/adm/style/acp_modules.html
  phpBB/adm/style/admin.css
  phpBB/adm/style/installer_header.html
  phpBB/adm/style/installer_update_file_status.html
  phpBB/adm/style/overall_footer.html
  phpBB/adm/style/permission_mask.html
  phpBB/includes/acp/acp_forums.php
  phpBB/includes/acp/acp_modules.php
  phpBB/includes/functions_acp.php
  phpBB/phpbb/install/controller/helper.php
  phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
  phpBB/phpbb/template/twig/extension/icon.php
  tests/template/extension_test.php
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6588 [ticket/17296] Reduce complexity of relative paths on adm pages
  phpBB/adm/index.php
  phpBB/phpbb/event/kernel_exception_subscriber.php
  phpBB/phpbb/path_helper.php
  tests/functional/session_page_update_test.php
Labels: 3.3 (Proteus) 🌑

#6590 [ticket/17296] Reduce complexity of relative paths on adm pages
  phpBB/adm/index.php
  phpBB/phpbb/event/kernel_exception_subscriber.php
  phpBB/phpbb/path_helper.php
  tests/functional/session_page_update_test.php
Labels: 4.0 (Triton) 🔮

#6589 [ticket/17284] Add viewtopic_body_online_list_after template event
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/viewtopic_body.html
Labels: Event 🔌
