Repository phpbb/phpbb, pull requests merged in 2024-04, with the labels that each got.

#6416 [ticket/17010] Implement notification method for web push
  .github/check-js.sh
  .github/workflows/tests.yml
  package-lock.json
  package.json
  phpBB/adm/style/ajax.js
  phpBB/assets/javascript/core.js
  phpBB/assets/javascript/webpush.js
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_notification.yml
  phpBB/config/default/container/services_ucp.yml
  phpBB/config/default/container/tables.yml
  phpBB/config/default/routing/ucp.yml
  phpBB/includes/acp/acp_board.php
  phpBB/includes/acp/info/acp_board.php
  phpBB/includes/functions.php
  phpBB/includes/ucp/ucp_notifications.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/acp/common.php
  phpBB/language/en/ucp.php
  phpBB/phpbb/db/migration/data/v400/add_webpush.php
  phpBB/phpbb/form/form_helper.php
  phpBB/phpbb/notification/method/extended_method_interface.php
  phpBB/phpbb/notification/method/webpush.php
  phpBB/phpbb/notification/type/type_interface.php
  phpBB/phpbb/ucp/controller/webpush.php
  phpBB/styles/all/js/push_worker.js.twig
  phpBB/styles/prosilver/template/ucp_notifications.html
  phpBB/styles/prosilver/template/ucp_notifications_options.html
  phpBB/styles/prosilver/template/ucp_notifications_webpush.html
  phpBB/styles/prosilver/theme/buttons.css
  tests/migrations/migrations_check_config_added_test.php
  tests/notification/base.php
  tests/notification/fixtures/webpush_notification.type.post.xml
  tests/notification/notification_method_email_test.php
  tests/notification/notification_method_webpush_test.php
  tests/notification/submit_post_base.php
Labels: 4.0 (Triton) 🔮

#6593 [ticket/17302] Fix password reset function
  phpBB/phpbb/ucp/controller/reset_password.php
Labels: 3.3 (Proteus) 🌑

#6592 [ticket/17299] Allow event to modify email core vars before sending a message
  phpBB/includes/functions_messenger.php
Labels: Event 🔌

#6591 [ticket/17297] Fix broken no avatar source tag in HTML
  phpBB/phpbb/avatar/helper.php
Labels: 4.0 (Triton) 🔮

#6598 [ticket/17305] Improve queries for unanswered posts/topics
  phpBB/search.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6596 [ticket/17303] Update jQuery to the version 3.7.1 - 3.3.x version
  phpBB/adm/style/installer_footer.html
  phpBB/adm/style/overall_footer.html
  phpBB/adm/style/simple_footer.html
  phpBB/assets/javascript/jquery-3.6.0.min.js
  phpBB/assets/javascript/jquery-3.7.1.min.js
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/install/schemas/schema_data.sql
  phpBB/phpbb/db/migration/data/v33x/jquery_update_v3.php
  phpBB/phpbb/install/controller/helper.php
  phpBB/styles/prosilver/template/overall_footer.html
  phpBB/styles/prosilver/template/simple_footer.html
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6601 [ticket/17305] Change sql_sort to be more in line with previous code
  phpBB/search.php
Labels: 3.3 (Proteus) 🌑

#6603 [ticket/17305] Add missing space to sql_sort
  phpBB/search.php
Labels: 3.3 (Proteus) 🌑

#6599 [ticket/12960] Remove broken captcha and add incomplete captcha as placeholder
  phpBB/adm/style/acp_main.html
  phpBB/adm/style/captcha_gd_acp.html
  phpBB/adm/style/captcha_recaptcha.html
  phpBB/config/default/container/services_captcha.yml
  phpBB/includes/acp/acp_main.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/acp/common.php
  phpBB/language/en/common.php
  phpBB/phpbb/captcha/char_cube3d.php
  phpBB/phpbb/captcha/colour_manager.php
  phpBB/phpbb/captcha/gd.php
  phpBB/phpbb/captcha/gd_wave.php
  phpBB/phpbb/captcha/non_gd.php
  phpBB/phpbb/captcha/plugins/gd.php
  phpBB/phpbb/captcha/plugins/gd_wave.php
  phpBB/phpbb/captcha/plugins/incomplete.php
  phpBB/phpbb/captcha/plugins/nogd.php
  phpBB/phpbb/captcha/plugins/recaptcha.php
  phpBB/phpbb/captcha/plugins/recaptcha_v3.php
  phpBB/phpbb/db/migration/data/v400/remove_broken_captcha.php
  phpBB/phpbb/install/module/install_database/task/add_config_settings.php
  phpBB/styles/prosilver/template/captcha_incomplete.html
  tests/auth/provider_db_test.php
  tests/captcha/incomplete_test.php
  tests/functions/user_delete_test.php
  tests/session/garbage_collection_test.php
Labels: 4.0 (Triton) 🔮
