Repository phpbb/phpbb, pull requests merged in 2024-01, with the labels that each got.

#6563 [ticket/17212] Support updating session info when editing post with p=
  phpBB/phpbb/session.php
  phpBB/posting.php
  tests/functional/viewonline_test.php
Labels: 3.3 (Proteus) 🌑

#6580 [ticket/17117] Do not load non-existent/disabled notification methods
  phpBB/phpbb/notification/manager.php
  tests/notification/fixtures/submit_post_notification.type.bookmark.xml
Labels: 3.3 (Proteus) 🌑

#6568 [ticket/17235] missing autocomplete for username
  phpBB/styles/prosilver/template/index_body.html
  phpBB/styles/prosilver/template/login_body.html
  phpBB/styles/prosilver/template/ucp_login_link.html
  phpBB/styles/prosilver/template/ucp_register.html
  phpBB/styles/prosilver/template/viewforum_body.html
Labels: Styles 🎨

#6579 [ticket/17281] Update to psalm 5.x
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/includes/functions_content.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/avatar/manager.php
  phpBB/phpbb/captcha/non_gd.php
  phpBB/phpbb/config/config.php
  phpBB/phpbb/config/db.php
  phpBB/phpbb/cron/manager.php
  phpBB/phpbb/cron/task/core/tidy_plupload.php
  phpBB/phpbb/db/doctrine/type_converter.php
  phpBB/phpbb/db/driver/mssql_odbc.php
  phpBB/phpbb/db/migration/exception.php
  phpBB/phpbb/db/migration/tool/module.php
  phpBB/phpbb/di/container_builder.php
  phpBB/phpbb/di/extension/container_configuration.php
  phpBB/phpbb/extension/provider.php
  phpBB/phpbb/feed/topics_active.php
  phpBB/phpbb/filesystem/filesystem.php
  phpBB/phpbb/filesystem/helper.php
  phpBB/phpbb/install/installer.php
  phpBB/phpbb/install/installer_configuration.php
  phpBB/phpbb/install/module/install_database/task/create_schema_file.php
  phpBB/phpbb/install/module_base.php
  phpBB/phpbb/install/updater_configuration.php
  phpBB/phpbb/notification/manager.php
  phpBB/phpbb/notification/method/method_interface.php
  phpBB/phpbb/pagination.php
  phpBB/phpbb/passwords/driver/helper.php
  phpBB/phpbb/plupload/plupload.php
  phpBB/phpbb/report/controller/report.php
  phpBB/phpbb/request/deactivated_super_global.php
  phpBB/phpbb/routing/file_locator.php
  phpBB/phpbb/search/backend/fulltext_native.php
  phpBB/phpbb/session.php
  phpBB/phpbb/template/base.php
  phpBB/phpbb/template/context.php
  phpBB/phpbb/template/template.php
  phpBB/phpbb/template/twig/extension/icon.php
  phpBB/phpbb/tree/nestedset.php
  phpBB/phpbb/user.php
  psalm.xml
Labels: 4.0 (Triton) 🔮
