Repository phpbb/phpbb, pull requests merged in 2024-07, with the labels that each got.

#6667 [ticket/17362] Declare property to avoid PHP 8.2 deprecation notice
  phpBB/phpbb/extension/manager.php
Labels: 3.3 (Proteus) 🌑

#6655 [ticket/17352] Fix overflow of long rank titles on profile page
  phpBB/styles/prosilver/template/memberlist_view.html
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/responsive.css
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6668 [ticket/17347] Fix psalm error for user delete by ID command
  phpBB/phpbb/console/command/user/delete_id.php
Labels: 4.0 (Triton) 🔮

#6669 [ticket/17363] Add web app manifest
  phpBB/config/default/container/services.yml
  phpBB/config/default/routing/routing.yml
  phpBB/includes/acp/acp_board.php
  phpBB/includes/functions.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/phpbb/manifest.php
  phpBB/styles/prosilver/template/overall_header.html
  tests/functional/manifest_test.php
Labels: 4.0 (Triton) 🔮

#6656 [ticket/17350] Add IP Address of user during install process
  phpBB/phpbb/install/module/install_finish/task/install_extensions.php
  phpBB/phpbb/install/module/update_database/task/update_extensions.php
Labels: 3.3 (Proteus) 🌑

#6661 [ticket/17356] Correctly handle errors hidden with at
  phpBB/includes/functions.php
  phpBB/install/startup.php
Labels: 3.3 (Proteus) 🌑

#6676 [ticket/16890] Deny access to config file and folder in nginx sample
  phpBB/docs/lighttpd.sample.conf
  phpBB/docs/nginx.sample.conf
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6671 [ticket/17364] Correctly handle styles list in ACP Forums
  phpBB/adm/style/acp_forums.html
  phpBB/includes/acp/acp_board.php
Labels: 4.0 (Triton) 🔮

#6685 [ticket/17369] Add forum id to approve action url for redirection
  phpBB/viewtopic.php
Labels: 3.3 (Proteus) 🌑

#6679 [ticket/17341] Remove no longer used files and references
  phpBB/adm/style/acp_forums_copy_perm.html
  phpBB/includes/acp/acp_forums.php
Labels: 4.0 (Triton) 🔮

#6678 [ticket/13916] Add notify to fields to store during save draft
  phpBB/posting.php
Labels: 3.3 (Proteus) 🌑

#6684 [ticket/17365] Prevent search limit being bypassed with operators
  phpBB/phpbb/search/fulltext_native.php
  tests/search/native_test.php
Labels: 3.3 (Proteus) 🌑

#6642 [ticket/17338] Prefer user_last_active to display user last activity info
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions_display.php
  phpBB/memberlist.php
  phpBB/phpbb/session.php
Labels: 3.3 (Proteus) 🌑

#6677 [ticket/16907] Adjust request filtering for phpbb paths
  phpBB/web.config
Labels: 3.3 (Proteus) 🌑

#5385 [ticket/15043] Rewrite get_context()
  phpBB/includes/functions_content.php
  phpBB/includes/utf/utf_tools.php
  tests/functional/search/base.php
  tests/functions_content/get_context_test.php
Labels: 3.3 (Proteus) 🌑

#6660 [ticket/17353] Get gravatar img src and fix incorrect treatment of height
  phpBB/phpbb/avatar/driver/gravatar.php
  tests/avatar/driver_gravatar_test.php
Labels: 3.3 (Proteus) 🌑

#6670 [ticket/17353] Get gravatar img src and fix incorrect treatment of height -- master version
  phpBB/phpbb/avatar/driver/gravatar.php
  tests/avatar/driver_gravatar_test.php
Labels: 4.0 (Triton) 🔮

#6687 [ticket/12479] Remove deprecated functions
  .github/workflows/tests.yml
  phpBB/includes/bbcode.php
  phpBB/includes/compatibility_globals.php
  phpBB/includes/functions_compatibility.php
  phpBB/phpbb/file_downloader.php
  phpBB/phpbb/files/filespec.php
  phpBB/phpbb/filesystem.php
  phpBB/phpbb/php/ini.php
  phpBB/phpbb/plupload/plupload.php
  phpBB/phpbb/request/request.php
  phpBB/phpbb/request/request_interface.php
  tests/auth/provider_apache_test.php
  tests/config/db_test.php
  tests/controller/common_helper_route.php
  tests/functions/build_hidden_fields_for_query_params_test.php
  tests/functions/get_remote_file_test.php
  tests/log/function_add_log_test.php
  tests/privmsgs/delete_user_pms_test.php
  tests/request/request_var_test.php
  tests/search/native_test.php
  tests/security/hash_test.php
  tests/text_processing/generate_text_for_display_test.php
  tests/text_processing/generate_text_for_storage_test.php
  tests/version/fixture/30x.txt
  tests/version/version_helper_remote_test.php
Labels: 4.0 (Triton) 🔮

#6697 [ticket/17022] Fix SQL report link
  phpBB/includes/functions.php
Labels: 4.0 (Triton) 🔮

#6696 [ticket/17374] Only delete marked logs if entries have been marked
  phpBB/includes/acp/acp_logs.php
Labels: 3.3 (Proteus) 🌑

#6689 [ticket/17370] Move delete cookies functionality to controller
  phpBB/config/default/container/services_ucp.yml
  phpBB/config/default/routing/ucp.yml
  phpBB/includes/functions.php
  phpBB/phpbb/ucp/controller/delete_cookies.php
  phpBB/ucp.php
Labels: 3.3 (Proteus) 🌑

#6688 [ticket/14454] Handle special case of testing user permissions in ACP modules
  phpBB/includes/functions_module.php
  tests/functional/switch_permissions_test.php
Labels: 3.3 (Proteus) 🌑

#6686 [ticket/15576] Handle subject max length same as in form input
  phpBB/includes/functions_privmsgs.php
Labels: 3.3 (Proteus) 🌑

#6681 [ticket/16213] Add .htaccess for phpbb and vendor folders
  build/build.xml
  phpBB/phpbb/.htaccess
Labels: 3.3 (Proteus) 🌑

#6680 [ticket/17366] Resolve issues with form submissions and recaptcha
  phpBB/phpbb/captcha/plugins/recaptcha_v3.php
  phpBB/styles/prosilver/template/ajax.js
  phpBB/styles/prosilver/template/posting_editor.html
Labels: 3.3 (Proteus) 🌑

#6691 [ticket/13933] Extend tokens' definitions in ACP bbcodes
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/language/en/acp/posting.php
Labels: 3.3 (Proteus) 🌑
