Repository phpbb/phpbb, pull requests merged in 2024-02, with the labels that each got.

#6541 [ticket/17093] Add ACP setting to limit access to disabled board
  phpBB/includes/acp/acp_board.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/phpbb/db/migration/data/v400/add_disable_board_access_config.php
  phpBB/phpbb/user.php
  tests/functional/browse_disabled_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6564 [ticket/13162] Add truncate table functionality to database tools
  phpBB/config/default/container/services_console.yml
  phpBB/config/default/container/services_search.yml
  phpBB/develop/fill.php
  phpBB/develop/repair_bots.php
  phpBB/includes/acp/acp_forums.php
  phpBB/includes/acp/acp_icons.php
  phpBB/includes/acp/acp_main.php
  phpBB/includes/acp/acp_permissions.php
  phpBB/includes/functions_admin.php
  phpBB/includes/functions_compatibility.php
  phpBB/includes/functions_convert.php
  phpBB/includes/functions_user.php
  phpBB/install/convert/controller/convertor.php
  phpBB/install/convert/convertor.php
  phpBB/phpbb/console/command/cache/purge.php
  phpBB/phpbb/db/tools/doctrine.php
  phpBB/phpbb/db/tools/tools_interface.php
  phpBB/phpbb/install/module/install_data/task/create_search_index.php
  phpBB/phpbb/search/backend/fulltext_native.php
  tests/console/cache/purge_test.php
  tests/dbal/db_tools_test.php
  tests/search/native_test.php
Labels: 4.0 (Triton) 🔮

#6585 [ticket/17293] Update composer and dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6584 [ticket/17292] Use new spamhaus.org check url
  phpBB/phpbb/session.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑
