Repository phpbb/phpbb, pull requests merged in 2024-06, with the labels that each got.

#6628 [ticket/17327] Use class name from use statement
  phpBB/phpbb/console/command/user/add.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6629 [ticket/17328] Update requires for exporting events
  phpBB/develop/export_events_for_bbcode.php
  phpBB/develop/export_events_for_rst.php
  phpBB/develop/export_events_for_wiki.php
Labels: 4.0 (Triton) 🔮

#6631 [ticket/17321] Add versioning to push worker to force updates
  phpBB/phpbb/notification/method/webpush.php
  phpBB/phpbb/ucp/controller/webpush.php
  phpBB/styles/all/js/push_worker.js.twig
Labels: 4.0 (Triton) 🔮

#6533 [ticket/17151] Make settings forms use macros
  phpBB/adm/style/acp_bots.html
  phpBB/adm/style/acp_users_prefs.html
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/acp/acp_board.php
  phpBB/includes/acp/acp_bots.php
  phpBB/includes/acp/acp_users.php
  phpBB/includes/functions.php
  phpBB/includes/functions_acp.php
  phpBB/includes/ucp/ucp_prefs.php
  phpBB/phpbb/template/twig/extension/forms.php
  phpBB/styles/all/template/macros/forms/input.twig
  phpBB/styles/all/template/macros/forms/radio_buttons.twig
  phpBB/styles/all/template/macros/forms/select.twig
  phpBB/styles/all/template/macros/forms/textarea.twig
  phpBB/styles/prosilver/template/ucp_prefs_personal.html
  tests/acp_board/select_auth_method_test.php
  tests/avatar/manager_test.php
  tests/functional/acp_main_test.php
  tests/functional/extension_module_test.php
  tests/functional/fixtures/ext/foo/bar/acp/main_module.php
  tests/functions/style_select_test.php
  tests/functions_acp/build_cfg_template_test.php
  tests/functions_acp/h_radio_test.php
Labels: 4.0 (Triton) 🔮

#6504 [ticket/17153] Use avatar classes and twig to render avatars
  phpBB/config/default/container/services_avatar.yml
  phpBB/config/default/container/services_twig.yml
  phpBB/config/installer/container/services.yml
  phpBB/config/installer/container/services_avatar.yml
  phpBB/includes/functions.php
  phpBB/includes/functions_compatibility.php
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/phpbb/template/twig/extension/avatar.php
  phpBB/styles/all/template/macros/avatar.twig
  tests/avatar/manager_test.php
  tests/template/extension_test.php
  tests/template/templates/avatar_group.html
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6634 [ticket/17330] Handle mozilla not properly handling webpush padding
  phpBB/phpbb/notification/method/webpush.php
  tests/notification/notification_method_webpush_test.php
Labels: 4.0 (Triton) 🔮

#6632 [ticket/17333] UX Enhancements for Web Push Subscribing
  phpBB/includes/acp/acp_board.php
  phpBB/includes/functions.php
  phpBB/install/schemas/schema_data.sql
  phpBB/language/en/acp/board.php
  phpBB/language/en/common.php
  phpBB/phpbb/db/migration/data/v400/add_webpush_options.php
  phpBB/phpbb/notification/method/webpush.php
  phpBB/styles/prosilver/template/notification_dropdown.html
  phpBB/styles/prosilver/template/overall_header.html
  phpBB/styles/prosilver/template/ucp_notifications_options.html
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/colours.css
  phpBB/styles/prosilver/theme/common.css
  tests/functional/notification_webpush_test.php
Labels: Styles 🎨, 4.0 (Triton) 🔮

#5270 [ticket/15699] Move files between storages when configuration is changed
  .gitignore
  phpBB/adm/style/acp_storage.html
  phpBB/adm/style/acp_storage_update_inprogress.html
  phpBB/adm/style/acp_storage_update_progress.html
  phpBB/config/default/container/services_storage.yml
  phpBB/includes/acp/acp_database.php
  phpBB/includes/acp/acp_storage.php
  phpBB/includes/functions_user.php
  phpBB/language/en/acp/common.php
  phpBB/language/en/acp/storage.php
  phpBB/phpbb/attachment/delete.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/avatar/driver/upload.php
  phpBB/phpbb/db/migration/data/v400/storage_track.php
  phpBB/phpbb/files/filespec_storage.php
  phpBB/phpbb/storage/adapter/adapter_interface.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/adapter_factory.php
  phpBB/phpbb/storage/controller/controller.php
  phpBB/phpbb/storage/exception/action_in_progress_exception.php
  phpBB/phpbb/storage/exception/no_action_in_progress_exception.php
  phpBB/phpbb/storage/exception/storage_exception.php
  phpBB/phpbb/storage/file_info.php
  phpBB/phpbb/storage/helper.php
  phpBB/phpbb/storage/provider/local.php
  phpBB/phpbb/storage/state_helper.php
  phpBB/phpbb/storage/storage.php
  phpBB/phpbb/storage/stream_interface.php
  phpBB/phpbb/storage/update_type.php
  tests/attachment/delete_test.php
  tests/functional/acp_storage_settings_test.php
Labels: 4.0 (Triton) 🔮, GSOC 🎓

#6636 [ticket/17336] Fix dev extensions not showing versions correctly in catalog
  phpBB/phpbb/composer/installer.php
Labels: 4.0 (Triton) 🔮

#6643 [ticket/17340] Update composer and dependencies
  composer.phar
  phpBB/composer.lock
Labels: 3.3 (Proteus) 🌑

#6644 [ticket/17340] Update composer and dependencies -- master version
  composer.phar
  phpBB/composer.json
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6633 [ticket/17332] Fix permission migrator tool to work with copied permissions
  phpBB/phpbb/db/migration/tool/permission.php
  tests/dbal/migrator_tool_permission_role_test.php
Labels: 3.3 (Proteus) 🌑

#6647 [ticket/17342] Add tests for PHP 8.4 to GitHub Actions
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6645 [ticket/17342] Add tests for PHP 8.4 to GitHub Actions
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮

#6639 [ticket/17301] Ensure reading invalid cache files is aborted
  phpBB/phpbb/cache/driver/file.php
  tests/cache/file_driver_test.php
Labels: 3.3 (Proteus) 🌑

#6640 [ticket/17301] Ensure reading invalid cache files is aborted -- master version
  phpBB/phpbb/cache/driver/file.php
  tests/cache/file_driver_test.php
Labels: 4.0 (Triton) 🔮

#6635 [ticket/17335] Fix language var issues in the extension manager
  phpBB/adm/style/acp_ext_list.html
  phpBB/language/en/acp/extensions.php
  phpBB/phpbb/template/twig/extension.php
  tests/template/template_test.php
  tests/template/templates/lang_twig.html
Labels: 4.0 (Triton) 🔮

#6641 [ticket/17339] Support receiving push notifications if not logged in
  phpBB/phpbb/db/migration/data/v400/add_webpush_token.php
  phpBB/phpbb/notification/method/webpush.php
  phpBB/phpbb/ucp/controller/webpush.php
  phpBB/styles/all/js/push_worker.js.twig
Labels: 4.0 (Triton) 🔮

#6646 Ticket/17344 User Experience improvements to web push subscriptions
  phpBB/assets/javascript/webpush.js
  phpBB/language/en/common.php
  phpBB/styles/prosilver/template/notification_dropdown.html
  phpBB/styles/prosilver/template/ucp_notifications_options.html
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/colours.css
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/responsive.css
  tests/functional/notification_webpush_test.php
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6658 [ticket/17351] Correctly handle md5 passwords rehashing - 3.3.x
  phpBB/phpbb/console/command/fixup/update_hashes.php
  phpBB/phpbb/cron/task/core/update_hashes.php
Labels: 3.3 (Proteus) 🌑

#6651 [ticket/17347] Add console command to delete users by user IDs
  phpBB/config/default/container/services_console.yml
  phpBB/language/en/cli.php
  phpBB/phpbb/console/command/user/delete_id.php
  tests/console/user/delete_id_test.php
  tests/console/user/fixtures/config.xml
Labels: 3.3 (Proteus) 🌑
