Repository phpbb/phpbb, pull requests merged in 2024-08, with the labels that each got.

#6662 [ticket/17358] Properly handle Redis cache expiration time - 3.3.x
  phpBB/phpbb/cache/driver/redis.php
Labels: 3.3 (Proteus) 🌑

#6663 [ticket/17358] Properly handle Redis cache expiration time - master
  phpBB/phpbb/cache/driver/redis.php
Labels: 4.0 (Triton) 🔮

#6698 [ticket/17375] Ensure user last visit does not get updated for active sessions in session gc
  phpBB/phpbb/session.php
Labels: 3.3 (Proteus) 🌑

#6700 [ticket/17377] Use specific mssql docker images to have uniform builds
  .github/workflows/tests.yml
Labels: WIP :construction:, 3.3 (Proteus) 🌑

#6701 [ticket/17377] Use specific mssql docker images to have uniform builds
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮

#6692 [ticket/17371] Web Push UX Updates
  phpBB/assets/javascript/webpush.js
  phpBB/language/en/common.php
  phpBB/phpbb/ucp/controller/webpush.php
  phpBB/styles/prosilver/imgs/svg/toggle-off.svg
  phpBB/styles/prosilver/imgs/svg/toggle-on.svg
  phpBB/styles/prosilver/template/notification_dropdown.html
  phpBB/styles/prosilver/template/ucp_notifications_options.html
  phpBB/styles/prosilver/theme/colours.css
  phpBB/styles/prosilver/theme/icons.css
Labels: 4.0 (Triton) 🔮

#6707 [ticket/17384] Handle E_USER_ERROR for PHP 8.4 tests - master
  tests/test_framework/phpbb_test_case.php
Labels: 4.0 (Triton) 🔮

#6695 [ticket/17181] Remove unused PM report code
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Labels: 3.3 (Proteus) 🌑

#6710 [ticket/17384] Stop overriding error handler in test case
  tests/test_framework/phpbb_test_case.php
Labels: 3.3 (Proteus) 🌑

#6711 [ticket/17384] Stop overriding error handler in test case and ignore E_DEPRECATED for expecting errors
  tests/test_framework/phpbb_test_case.php
  tests/test_framework/phpbb_test_case_helpers.php
Labels: 4.0 (Triton) 🔮

#6703 [ticket/17379] Use correct number of predefined BBCodes in posting editor
  phpBB/adm/style/acp_posting_buttons.html
  phpBB/includes/constants.php
  phpBB/styles/prosilver/template/posting_buttons.html
Labels: 4.0 (Triton) 🔮
