Repository phpbb/phpbb, pull requests merged in 2025-02, with the labels that each got.

#6771 [ticket/17463] Remove extraneous '&' from search page urls
  phpBB/search.php
Labels: 3.3 (Proteus) 🌑

#6777 [ticket/17468] Send reset password link to email only
  phpBB/phpbb/ucp/controller/reset_password.php
Labels: 3.3 (Proteus) 🌑

#6779 [ticket/17465] Add unit tests for handling of web push notifications
  phpBB/phpbb/ucp/controller/webpush.php
  tests/ucp/controller_webpush_test.php
  tests/ucp/fixtures/webpush.xml
Labels: 4.0 (Triton) 🔮

#6775 [ticket/17467] Provide TLS v.1.3 support for SMTP connections
  phpBB/includes/functions_messenger.php
Labels: 3.3 (Proteus) 🌑

#6544 [ticket/15851] Automatic update downloader
  .github/workflows/tests.yml
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/config/default/container/parameters.yml
  phpBB/config/default/container/services.yml
  phpBB/config/default/container/services_updater.yml
  phpBB/includes/acp/acp_update.php
  phpBB/language/en/install.php
  phpBB/phpbb/install/module/requirements/task/check_server_environment.php
  phpBB/phpbb/update/controller.php
  phpBB/phpbb/update/get_updates.php
  tests/update/controller_test.php
  tests/update/get_updates_test.php
Labels: 4.0 (Triton) 🔮

#6768 [ticket/17459] Improve prosilver font sizes and backgrounds
  phpBB/docs/events.md
  phpBB/phpbb/event/md_exporter.php
  phpBB/styles/prosilver/template/ajax.js
  phpBB/styles/prosilver/template/faq_body.html
  phpBB/styles/prosilver/template/index_body.html
  phpBB/styles/prosilver/template/navbar_header.html
  phpBB/styles/prosilver/theme/base.css
  phpBB/styles/prosilver/theme/buttons.css
  phpBB/styles/prosilver/theme/colours.css
  phpBB/styles/prosilver/theme/common.css
  phpBB/styles/prosilver/theme/content.css
  phpBB/styles/prosilver/theme/cp.css
  phpBB/styles/prosilver/theme/forms.css
  phpBB/styles/prosilver/theme/icons.css
  phpBB/styles/prosilver/theme/links.css
  phpBB/styles/prosilver/theme/responsive.css
  tests/event/fixtures/normal_events.md.test
  tests/event/md_exporter_test.php
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6657 [ticket/17326] Add font icon field for custom BBCodes
  phpBB/adm/style/acp_bbcodes.html
  phpBB/adm/style/admin.js
  phpBB/includes/acp/acp_bbcodes.php
  phpBB/includes/functions_display.php
  phpBB/language/en/acp/posting.php
  phpBB/language/en/common.php
  phpBB/phpbb/db/migration/data/v400/add_bbcode_font_icon.php
  phpBB/styles/prosilver/template/posting_buttons.html
  tests/functional/acp_bbcodes_test.php
Labels: 4.0 (Triton) 🔮

#6780 [ticket/17470] Feed enable config not enforced
  phpBB/phpbb/feed/controller/feed.php
  tests/functional/feed_test.php
Labels: 3.3 (Proteus) 🌑

#6782 [ticket/17470] Fix feed functional tests for master
  tests/functional/feed_test.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6753 [ticket/17361] Improve storage
  phpBB/adm/style/acp_storage.html
  phpBB/config/default/container/services_console.yml
  phpBB/config/default/container/services_storage.yml
  phpBB/includes/acp/acp_database.php
  phpBB/includes/acp/acp_main.php
  phpBB/includes/acp/acp_storage.php
  phpBB/includes/functions_user.php
  phpBB/language/en/acp/storage.php
  phpBB/phpbb/attachment/upload.php
  phpBB/phpbb/console/command/thumbnail/delete.php
  phpBB/phpbb/console/command/thumbnail/generate.php
  phpBB/phpbb/console/command/thumbnail/recreate.php
  phpBB/phpbb/db/migration/data/v400/storage_attachment.php
  phpBB/phpbb/db/migration/data/v400/storage_avatar.php
  phpBB/phpbb/db/migration/data/v400/storage_backup.php
  phpBB/phpbb/db/migration/data/v400/storage_backup_data.php
  phpBB/phpbb/db/migration/data/v400/storage_track.php
  phpBB/phpbb/db/migration/data/v400/storage_track_index.php
  phpBB/phpbb/files/filespec_storage.php
  phpBB/phpbb/filesystem/temp.php
  phpBB/phpbb/language/language.php
  phpBB/phpbb/storage/adapter/adapter_interface.php
  phpBB/phpbb/storage/adapter/local.php
  phpBB/phpbb/storage/adapter_factory.php
  phpBB/phpbb/storage/controller/attachment.php
  phpBB/phpbb/storage/controller/avatar.php
  phpBB/phpbb/storage/controller/controller.php
  phpBB/phpbb/storage/exception/storage_exception.php
  phpBB/phpbb/storage/file_tracker.php
  phpBB/phpbb/storage/helper.php
  phpBB/phpbb/storage/provider/local.php
  phpBB/phpbb/storage/provider/provider_interface.php
  phpBB/phpbb/storage/storage.php
  phpBB/phpbb/storage/stream_interface.php
  phpBB/phpbb/template/twig/extension/forms.php
  tests/console/thumbnail_test.php
  tests/storage/adapter/local_test.php
Labels: 4.0 (Triton) 🔮
