Repository phpbb/phpbb, pull requests merged in 2025-03, with the labels that each got.

#6783 [ticket/17461] Add core events to acp_main
  phpBB/includes/acp/acp_main.php
Labels: Event 🔌

#6772 [ticket/17227] Fix rows duplication in memberlist
  phpBB/memberlist.php
Labels: 3.3 (Proteus) 🌑

#6758 [ticket/17381] Topic view count validation
  phpBB/phpbb/db/migration/data/v33x/topic_views_update.php
Labels: 3.3 (Proteus) 🌑

#6785 [ticket/17478] Add security policy file
  SECURITY.md
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6786 [ticket/17480] Fix PHP fatal error in version check failure
  phpBB/includes/acp/acp_extensions.php
  phpBB/includes/acp/acp_main.php
Labels: 3.3 (Proteus) 🌑
