Repository phpbb/phpbb, pull requests merged in 2025-09, with the labels that each got.

#6842 [ticket/17537] Cache extensions paths as metadata for ConfigCache
  phpBB/phpbb/di/container_builder.php
Labels: 4.0 (Triton) 🔮

#6844 [ticket/17451] Web push service worker shouldn't update user activity
  phpBB/phpbb/session.php
Labels: 4.0 (Triton) 🔮

#6849 [ticket/17543] Update composer and dependencies and provide better support for PHP 8.5
  .github/phpunit-mariadb-github.xml
  .github/phpunit-mssql-github.xml
  .github/phpunit-mysql-github.xml
  .github/phpunit-postgres-github.xml
  .github/phpunit-psql-windows-github.xml
  .github/phpunit-sqlite3-github.xml
  .github/workflows/tests.yml
  composer.phar
  phpBB/composer.lock
  phpBB/includes/functions_posting.php
  phpBB/phpbb/captcha/plugins/recaptcha_v3.php
  phpBB/phpbb/db/doctrine/connection_parameter_factory.php
  phpBB/phpbb/notification/type/post.php
  phpBB/phpbb/search/backend/fulltext_native.php
  phpunit.xml.dist
  tests/avatar/driver_gravatar_test.php
  tests/ban/ban_manager_test.php
  tests/cache/file_driver_test.php
  tests/captcha/turnstile_test.php
  tests/datetime/from_format_test.php
  tests/dbal/db_tools_test.php
  tests/email/email_parsing_test.php
  tests/extension/extension_base_test.php
  tests/files/types_local_test.php
  tests/files/upload_test.php
  tests/filesystem/helper_realpath_test.php
  tests/filesystem/realpath_test.php
  tests/group/helper_test_case.php
  tests/language/language_test.php
  tests/messenger/queue_test.php
  tests/migrator/get_callable_from_step_test.php
  tests/notification/notification_method_email_test.php
  tests/notification/notification_method_webpush_test.php
  tests/profilefields/type_bool_test.php
  tests/profilefields/type_dropdown_test.php
  tests/template/extension_test.php
  tests/template/template_test_case.php
  tests/template/twig_test.php
  tests/text_reparser/plugins/post_text_test.php
  tests/text_reparser/plugins/test_row_based_plugin.php
  tests/ucp/controller_webpush_test.php
  tests/upload/filespec_test.php
Labels: 4.0 (Triton) 🔮

#6848 [ticket/17542] Mock event dispatcher override early exits
  tests/mock/event_dispatcher.php
Labels: 4.0 (Triton) 🔮

#6837 [ticket/17157] Fix for allowing user to see search results for topics if f_list_topics = yes
  phpBB/search.php
  phpBB/styles/prosilver/template/search_results.html
  phpBB/styles/prosilver/template/viewforum_body.html
  phpBB/viewforum.php
Labels: 3.3 (Proteus) 🌑

#6852 [ticket/17543] Optimize functional tests running time
  tests/functional/acp_permissions_test.php
  tests/functional/acp_registration_test.php
  tests/functional/auth_test.php
  tests/functional/download_test.php
  tests/functional/extension_controller_test.php
  tests/functional/extension_module_test.php
  tests/functional/extension_template_event_order_test.php
  tests/functional/feed_test.php
  tests/functional/forum_style_test.php
  tests/functional/mcp/mcp_main_test.php
  tests/functional/metadata_manager_test.php
  tests/functional/plupload_test.php
  tests/functional/prune_shadow_topic_test.php
  tests/functional/search/base.php
  tests/functional/search/mysql_test.php
  tests/functional/search/postgres_test.php
  tests/functional/search/sphinx_test.php
  tests/functional/session_page_update_test.php
  tests/functional/smilies_test.php
  tests/functional/subforum_test.php
  tests/functional/switch_permissions_test.php
  tests/functional/ucp_allow_pm_test.php
  tests/functional/ucp_groups_test.php
  tests/functional/ucp_profile_test.php
  tests/functional/user_password_reset_test.php
  tests/functional/viewforum_paging_test.php
  tests/functional/viewonline_test.php
  tests/functional/visibility_disapprove_test.php
  tests/functional/visibility_reapprove_test.php
  tests/functional/visibility_softdelete_test.php
  tests/functional/visibility_unapproved_posts_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6187 [ticket/16005] Remove phpBB2 converter
  phpBB/includes/functions_convert.php
  phpBB/install/convertors/convert_phpbb20.php
  phpBB/install/convertors/functions_phpbb20.php
  phpBB/install/convertors/index.htm
Labels: 4.0 (Triton) 🔮

#6866 [ticket/17477] Support non-prefixed whois servers
  phpBB/includes/functions_user.php
  tests/functions_user/whois_test.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑
