Repository phpbb/phpbb, pull requests merged in 2025-06, with the labels that each got.

#6823 [ticket/17516] Remove dependency on topological sort library
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/phpbb/db/migration/schema_generator.php
Labels: 4.0 (Triton) 🔮

#6821 [ticket/17509] Bump DBMS supported versions
  phpBB/composer.json
  phpBB/composer.lock
  phpBB/language/en/install.php
  phpBB/phpbb/db/doctrine/connection_parameter_factory.php
  phpBB/phpbb/db/driver/sqlite3.php
  phpBB/phpbb/db/tools/doctrine.php
  phpBB/phpbb/install/helper/database.php
Labels: 4.0 (Triton) 🔮

#6819 [ticket/17515] Add template event before PM text - master
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Labels: Event 🔌

#6818 [ticket/17515] Add template event before PM text - 3.3.x
  phpBB/docs/events.md
  phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Labels: Event 🔌

#6770 [ticket/15214] Add event & functionality for assigning template event priority
  phpBB/phpbb/template/twig/environment.php
  phpBB/phpbb/template/twig/node/event.php
  phpBB/phpbb/template/twig/tokenparser/event.php
  tests/functional/extension_controller_test.php
  tests/functional/extension_global_lang_test.php
  tests/functional/extension_module_test.php
  tests/functional/extension_permission_lang_test.php
  tests/functional/extension_template_event_order_test.php
  tests/functional/fixtures/ext/foo/bar/config/services.yml
  tests/functional/fixtures/ext/foo/bar/event/template_event_order.php
  tests/functional/fixtures/ext/foo/bar/event/template_event_order_higher.php
  tests/functional/fixtures/ext/foo/bar/styles/prosilver/template/event/index_body_forumlist_body_before.html
  tests/functional/fixtures/ext/foo/bar/styles/prosilver/template/event/navbar_header_quick_links_after.html
  tests/functional/fixtures/ext/foo/foo/config/services.yml
  tests/functional/fixtures/ext/foo/foo/event/template_event_order.php
  tests/functional/fixtures/ext/foo/foo/event/template_event_order_lower.php
  tests/functional/fixtures/ext/foo/foo/styles/prosilver/template/event/index_body_forumlist_body_before.html
  tests/functional/fixtures/ext/foo/foo/styles/prosilver/template/event/navbar_header_quick_links_after.html
  tests/functional/metadata_manager_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6829 [ticket/17399] Fix selected language bug in installer
  phpBB/adm/style/installer_header.html
  phpBB/phpbb/install/controller/helper.php
  phpBB/phpbb/language/language_file_helper.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6831 [ticket/17527] Add Twig extensions existence check while registering
  phpBB/phpbb/template/twig/twig.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6826 [ticket/17522] Add event to member list to modify template vars
  phpBB/memberlist.php
Labels: 3.3 (Proteus) 🌑
