Repository phpbb/phpbb, pull requests merged in 2025-07, with the labels that each got.

#6830 [ticket/17525] Correctly handle Doctrine DB tools exceptions, enrich error info
  phpBB/adm/style/acp_ext_delete_data.html
  phpBB/adm/style/acp_ext_enable.html
  phpBB/develop/create_schema_files.php
  phpBB/includes/acp/acp_extensions.php
  phpBB/includes/functions.php
  phpBB/install/startup.php
  phpBB/phpbb/db/doctrine/table_helper.php
  phpBB/phpbb/db/migration/data/v400/rename_duplicated_index_names.php
  phpBB/phpbb/db/migration/helper.php
  phpBB/phpbb/db/migration/migration.php
  phpBB/phpbb/db/migration/schema_generator.php
  phpBB/phpbb/db/tools/doctrine.php
  phpBB/phpbb/db/tools/tools_interface.php
  phpBB/phpbb/install/helper/database.php
  phpBB/phpbb/install/installer.php
  phpBB/phpbb/install/module/install_database/task/add_tables.php
  phpBB/phpbb/install/module/install_database/task/create_schema_file.php
  tests/dbal/auto_increment_test.php
  tests/dbal/db_tools_test.php
  tests/dbal/migration/schema_index.php
  tests/dbal/migrator_test.php
  tests/extension/manager_test.php
  tests/extension/metadata_manager_test.php
  tests/migrations/migrations_check_config_added_test.php
  tests/migrator/get_callable_from_step_test.php
  tests/migrator/schema_generator_test.php
  tests/test_framework/phpbb_database_test_case.php
  tests/test_framework/phpbb_database_test_connection_manager.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6834 [ticket/17528] Fix uncaught exception on adding autoincrement column on PostgreSQL/MySQL platforms
  phpBB/phpbb/db/doctrine/connection_parameter_factory.php
  phpBB/phpbb/db/doctrine/mysql_platform.php
  phpBB/phpbb/db/doctrine/postgresql_platform.php
  phpBB/phpbb/db/migration/data/v400/remove_jabber.php
  phpBB/phpbb/db/migration/schema_generator.php
  phpBB/phpbb/db/migration/tool/module.php
  phpBB/phpbb/db/tools/doctrine.php
  tests/dbal/migration/schema_add_autoincrement.php
  tests/dbal/migrator_test.php
  tests/migrations/fixtures/migration_remove_jabber.xml
  tests/migrations/migration_test_base.php
  tests/migrations/remove_jabber_migration_test.php
  tests/notification/fixtures/email_notification.type.post.xml
  tests/notification/fixtures/submit_post_notification.type.bookmark.xml
  tests/notification/fixtures/submit_post_notification.type.forum.xml
  tests/notification/fixtures/submit_post_notification.type.mention.xml
  tests/notification/fixtures/submit_post_notification.type.post.xml
  tests/notification/fixtures/submit_post_notification.type.post_in_queue.xml
  tests/notification/fixtures/submit_post_notification.type.quote.xml
  tests/notification/fixtures/submit_post_notification.type.topic.xml
  tests/notification/fixtures/webpush_notification.type.post.xml
Labels: 4.0 (Triton) 🔮

#6791 [ticket/17110] Change "slanderous" to "libellous" in T&C
  phpBB/language/en/ucp.php
Labels: 4.0 (Triton) 🔮, 3.3 (Proteus) 🌑

#6840 [ticket/17034] Fix minimum posts rank validation
  phpBB/adm/style/acp_ranks.html
Labels: 3.3 (Proteus) 🌑
