Repository phpbb/phpbb, pull requests merged in 2025-04, with the labels that each got.

#6792 [ticket/17486] Fix SQL error on phpBB v.3.0 to v.3.3 upgrade
  phpBB/phpbb/db/migration/data/v310/bot_update.php
Labels: 3.3 (Proteus) 🌑

#6789 [ticket/17475] Fix MSSQL arithmetic overflow error on counting attachments size
  phpBB/includes/acp/acp_attachments.php
  phpBB/includes/acp/acp_forums.php
  phpBB/includes/acp/acp_main.php
  phpBB/includes/functions_convert.php
Labels: 3.3 (Proteus) 🌑

#6794 [ticket/17489] Fix various messenger issues
  phpBB/includes/acp/acp_email.php
  phpBB/includes/acp/acp_inactive.php
  phpBB/includes/ucp/ucp_activate.php
  phpBB/includes/ucp/ucp_resend.php
  phpBB/phpbb/message/message.php
  phpBB/phpbb/messenger/method/base.php
  phpBB/phpbb/messenger/method/email.php
  phpBB/phpbb/messenger/method/messenger_interface.php
  phpBB/phpbb/messenger/queue.php
  phpBB/phpbb/notification/method/messenger_base.php
  tests/functional/memberlist_test.php
Labels: 4.0 (Triton) 🔮

#6796 [ticket/17490] Add unit tests for symfony mailer classes
  phpBB/phpbb/messenger/method/base.php
  phpBB/phpbb/messenger/method/email.php
  tests/messenger/method_base_test.php
  tests/messenger/method_email_test.php
  tests/messenger/method_jabber_test.php
  tests/messenger/queue_test.php
Labels: 4.0 (Triton) 🔮

#6797 [ticket/17492] Unintuitive checkbox status inverted for forum/topic subscriptions
  phpBB/styles/prosilver/template/navbar_footer.html
  phpBB/styles/prosilver/template/viewtopic_topic_tools.html
Labels: Styles 🎨, 3.3 (Proteus) 🌑

#6798 [ticket/17492] Show current state of topic subscription in dropdown -- master version
  phpBB/styles/prosilver/template/navbar_footer.html
  phpBB/styles/prosilver/template/viewtopic_topic_tools.html
Labels: Styles 🎨, 4.0 (Triton) 🔮

#6804 [ticket/17498] Move to Ubuntu 22.04 runner images for SQLite and MSSQL tests - 3.3.x
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑

#6805 [ticket/17498] Move to Ubuntu 22.04 runner images for SQLite and MSSQL tests - master
  .github/workflows/tests.yml
Labels: 4.0 (Triton) 🔮

#6795 [ticket/17488] Fix PHP error when MySQL PDO driver is not enabled
  phpBB/phpbb/db/doctrine/connection_parameter_factory.php
Labels: 4.0 (Triton) 🔮

#6787 [ticket/17481] Make build package directory version independent
  build/build.xml
  build/build_changelog.php
  build/build_helper.php
  build/compare.sh
Labels: 4.0 (Triton) 🔮

#6807 [ticket/16941] Add sphinx tests to 3.3.x
  .github/setup-sphinx.sh
  .github/workflows/tests.yml
  phpBB/phpbb/search/fulltext_sphinx.php
  tests/functional/search/base.php
  tests/functional/search/sphinx_test.php
  tests/functional/visibility_softdelete_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 3.3 (Proteus) 🌑

#6808 [ticket/16941] Add sphinx tests - master
  .github/setup-sphinx.sh
  phpBB/phpbb/search/backend/fulltext_sphinx.php
  tests/functional/search/base.php
  tests/functional/search/sphinx_test.php
  tests/functional/visibility_softdelete_test.php
  tests/test_framework/phpbb_functional_test_case.php
Labels: 4.0 (Triton) 🔮

#6809 [ticket/17503] Update composer dependencies to latest versions
  composer.phar
  phpBB/composer.lock
Labels: 4.0 (Triton) 🔮

#6810 [ticket/17504] Fix tests failure caused by ondrej/php PPA repo label changed
  .github/setup-exiftool.sh
  .github/setup-sphinx.sh
  .github/setup-unbuffer.sh
  .github/setup-webserver.sh
  .github/workflows/tests.yml
Labels: 3.3 (Proteus) 🌑
